export const VENTURE_SYSTEMS_ARCHITECTURE_VERSION = "venture_systems_architecture_v1";

export const VENTURE_OPERATING_MODELS = [
  "HOME_CONTRACTOR",
  "LOCAL_SERVICE",
  "SAAS",
  "MARKETPLACE",
  "ECOMMERCE",
  "LEAD_GENERATION",
  "DIGITAL_PRODUCT",
  "SERVICE_PLATFORM",
  "CONTENT_BUSINESS",
  "AMBIGUOUS",
] as const;

export type VentureOperatingModel = (typeof VENTURE_OPERATING_MODELS)[number];

export const VENTURE_STAGES = [
  "EXPERIMENTAL",
  "PRE_REVENUE",
  "EARLY_REVENUE",
  "MATURE",
  "SPINOUT_CANDIDATE",
] as const;

export type VentureStage = (typeof VENTURE_STAGES)[number];

export const SYSTEM_FAMILIES = [
  "PAYMENTS",
  "CRM",
  "LEAD_CAPTURE",
  "CUSTOMER_ACQUISITION",
  "TRANSACTIONAL_EMAIL",
  "MARKETING_EMAIL",
  "SMS",
  "SCHEDULING",
  "IDENTITY_AND_ACCOUNTS",
  "AUTHORIZATION_AND_ROLES",
  "ENTITLEMENTS",
  "CONTENT_AND_DISTRIBUTION",
  "SEO",
  "SOCIAL_DISTRIBUTION",
  "ANALYTICS",
  "ATTRIBUTION",
  "CUSTOMER_SUPPORT",
  "CUSTOMER_SUCCESS",
  "REPUTATION_AND_REVIEWS",
  "OPERATIONS",
  "COMMERCE_AND_FULFILLMENT",
  "LEGAL_AND_COMPLIANCE",
  "SECURITY_AND_RISK",
  "LIFECYCLE_AUTOMATION",
  "EXPERIMENTATION",
  "AFFILIATE_AND_PARTNERS",
  "LOCALIZATION",
  "HUMAN_OPERATIONS",
] as const;

export type SystemFamily = (typeof SYSTEM_FAMILIES)[number];

export const SYSTEM_PRIORITIES = [
  "FOUNDATION",
  "REVENUE_PATH",
  "OPERATIONS",
  "MEASUREMENT",
  "GROWTH",
  "OPTIONAL",
] as const;

export type SystemPriority = (typeof SYSTEM_PRIORITIES)[number];

export const CRM_CAPABILITIES = [
  "CRM_CONTACTS",
  "CRM_COMPANIES",
  "CRM_PIPELINE",
  "CRM_DEALS",
  "CRM_NOTES",
  "CRM_TASKS",
  "CRM_LIFECYCLE_STAGE",
  "CRM_LEAD_SOURCE",
  "CRM_LEAD_SCORING",
  "CRM_CUSTOM_FIELDS",
  "CRM_FORM_SYNC",
  "CRM_ACTIVITY_HISTORY",
] as const;

export type CrmCapability = (typeof CRM_CAPABILITIES)[number];

export const COMMUNICATION_CAPABILITIES = [
  "TRANSACTIONAL_EMAIL",
  "MARKETING_EMAIL",
  "AUTOMATED_NURTURE",
  "REACTIVATION",
  "SMS",
  "APPOINTMENT_REMINDERS",
  "REVIEW_REQUESTS",
  "CUSTOMER_NOTIFICATIONS",
] as const;

export type CommunicationCapability = (typeof COMMUNICATION_CAPABILITIES)[number];

export const IDENTITY_MODELS = [
  "CUSTOMER_ACCOUNT",
  "ADMIN_ACCOUNT",
  "TEAM_MEMBER",
  "BUYER",
  "SELLER",
  "SERVICE_PROVIDER",
  "CLIENT_PORTAL",
  "ROLE_BASED_ACCESS",
  "ORGANIZATION_ACCOUNT",
  "MULTI_TENANT_ACCOUNT",
  "ARTIST_IDENTITY",
  "COLLECTOR_IDENTITY",
] as const;

export type IdentityModel = (typeof IDENTITY_MODELS)[number];

export const ANALYTICS_EVENTS = [
  "PAGE_VIEW",
  "LEAD",
  "SIGNUP",
  "CHECKOUT",
  "PURCHASE",
  "SUBSCRIPTION",
  "REVENUE",
  "CAMPAIGN_SOURCE",
  "UTM_ATTRIBUTION",
  "SEO_LANDING_PAGE",
  "CONVERSION_FUNNEL",
  "RETENTION",
  "CHURN",
  "LTV",
  "CAC",
  "GMV",
  "TAKE_RATE",
] as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[number];

export const SUPPORT_CAPABILITIES = [
  "HELP_CENTER",
  "SUPPORT_TICKET",
  "CONTACT_SUPPORT",
  "CHAT_SUPPORT",
  "CUSTOMER_HISTORY",
  "ESCALATION",
  "REFUND_SUPPORT",
  "DISPUTE_SUPPORT",
  "KNOWLEDGE_BASE",
  "ONBOARDING_SUPPORT",
] as const;

export type SupportCapability = (typeof SUPPORT_CAPABILITIES)[number];

export const REPUTATION_CAPABILITIES = [
  "CUSTOMER_REVIEWS",
  "SELLER_RATINGS",
  "SERVICE_PROVIDER_RATINGS",
  "TESTIMONIALS",
  "REVIEW_REQUEST_AUTOMATION",
  "MODERATION",
  "FRAUD_SIGNAL",
  "TRUST_BADGES",
  "VERIFICATION_STATE",
] as const;

export type ReputationCapability = (typeof REPUTATION_CAPABILITIES)[number];

export const SCHEDULING_CAPABILITIES = [
  "APPOINTMENT_BOOKING",
  "ESTIMATE_SCHEDULING",
  "CONSULTATION_BOOKING",
  "JOB_SCHEDULING",
  "RESOURCE_CALENDAR",
  "REMINDER",
  "CANCELLATION",
  "RESCHEDULING",
] as const;

export type SchedulingCapability = (typeof SCHEDULING_CAPABILITIES)[number];

export const CONTENT_CAPABILITIES = [
  "SEO_CONTENT",
  "PROGRAMMATIC_SEO",
  "BLOG",
  "LOCATION_PAGES",
  "SERVICE_PAGES",
  "EMAIL_NEWSLETTER",
  "SOCIAL_CONTENT",
  "LANDING_PAGES",
  "CONTENT_REFRESH",
  "CONTENT_CALENDAR",
  "CONTENT_PRODUCTION",
] as const;

export type ContentCapability = (typeof CONTENT_CAPABILITIES)[number];

export const SEO_CAPABILITIES = [
  "URL_STRUCTURE",
  "INTERNAL_LINKING",
  "CONTENT_HUBS",
  "LOCATION_ARCHITECTURE",
  "SERVICE_ARCHITECTURE",
  "SCHEMA",
  "METADATA",
  "SITEMAP",
  "INDEXATION",
  "CONTENT_REFRESH",
  "SEARCH_CONSOLE",
  "RANK_TRACKING",
] as const;

export type SeoCapability = (typeof SEO_CAPABILITIES)[number];

export const LIFECYCLE_EVENTS = [
  "LEAD_CREATED",
  "LEAD_CONTACTED",
  "TRIAL_STARTED",
  "TRIAL_ENDING",
  "SUBSCRIPTION_STARTED",
  "PAYMENT_FAILED",
  "CUSTOMER_INACTIVE",
  "PURCHASE_COMPLETED",
  "JOB_COMPLETED",
  "REVIEW_REQUEST_DUE",
  "RENEWAL_DUE",
  "CHURN_RISK",
  "SELLER_ONBOARDING_INCOMPLETE",
] as const;

export type LifecycleEvent = (typeof LIFECYCLE_EVENTS)[number];

export const COMPLIANCE_REQUIREMENTS = [
  "PRIVACY_POLICY",
  "TERMS_OF_SERVICE",
  "COOKIE_CONSENT",
  "EMAIL_CONSENT",
  "SMS_CONSENT",
  "DATA_RETENTION_POLICY",
  "REFUND_POLICY",
  "MARKETPLACE_TERMS",
  "SELLER_TERMS",
  "AGE_RESTRICTIONS",
  "INDUSTRY_COMPLIANCE_REVIEW",
  "ACCESSIBILITY_REQUIREMENTS",
] as const;

export type ComplianceRequirement = (typeof COMPLIANCE_REQUIREMENTS)[number];

export const SECURITY_REQUIREMENTS = [
  "AUTHENTICATION",
  "AUTHORIZATION",
  "RATE_LIMITING",
  "INPUT_VALIDATION",
  "ABUSE_PREVENTION",
  "FRAUD_DETECTION",
  "AUDIT_LOGGING",
  "SECRET_MANAGEMENT",
  "BACKUP_REQUIREMENTS",
  "INCIDENT_MONITORING",
  "ERROR_MONITORING",
  "DATA_ISOLATION",
] as const;

export type SecurityRequirement = (typeof SECURITY_REQUIREMENTS)[number];

export const PAYMENT_SYSTEM_CAPABILITIES = [
  "DEPOSIT_PAYMENT",
  "FINAL_PAYMENT",
  "ONE_TIME_CHECKOUT",
  "SUBSCRIPTIONS",
  "MARKETPLACE_PAYMENTS",
  "SELLER_ONBOARDING",
] as const;

export type PaymentSystemCapability = (typeof PAYMENT_SYSTEM_CAPABILITIES)[number];

export const TENANCY_STRATEGIES = [
  "SHARED",
  "SHARED_WITH_LOGICAL_ISOLATION",
  "DEDICATED_PER_VENTURE",
  "DEDICATED_PER_COMPANY",
  "DEFERRED",
  "REQUIRES_POLICY_DECISION",
] as const;

export type TenancyStrategy = (typeof TENANCY_STRATEGIES)[number];

export const PROCUREMENT_STATUSES = [
  "NOT_REQUIRED",
  "DEFERRED",
  "FREE_TIER",
  "TRIAL_ELIGIBLE",
  "BUDGET_REVIEW_REQUIRED",
  "TREASURY_ELIGIBLE",
  "LIVE_PURCHASE_GATED",
  "LIVE_ACTIVE",
] as const;

export type ProcurementStatus = (typeof PROCUREMENT_STATUSES)[number];

export const PROVIDER_CATEGORIES = [
  "CRM",
  "EMAIL",
  "SMS",
  "ANALYTICS",
  "SUPPORT",
  "SCHEDULING",
  "PAYMENTS",
  "SEO",
  "IDENTITY",
] as const;

export type ProviderCategory = (typeof PROVIDER_CATEGORIES)[number];

export const UNRESOLVED_SYSTEM_POLICY_CODES = [
  "BUSINESS_MODEL_AMBIGUOUS",
  "REGULATED_INDUSTRY_COMPLIANCE",
  "LEGAL_ENTITY_OBLIGATIONS",
  "TAX_LIABILITY",
  "PROFESSIONAL_LICENSING",
  "MERCHANT_OF_RECORD_LEGAL_STATUS",
  "EMAIL_CONSENT",
  "SMS_CONSENT",
  "PROVIDER_TENANCY_POLICY",
  "PAID_VENDOR_BUDGET",
] as const;

export type UnresolvedSystemPolicyCode = (typeof UNRESOLVED_SYSTEM_POLICY_CODES)[number];

export const SYSTEM_CAPABILITY_CATALOG = [
  ...CRM_CAPABILITIES,
  ...COMMUNICATION_CAPABILITIES,
  ...IDENTITY_MODELS,
  ...ANALYTICS_EVENTS,
  ...SUPPORT_CAPABILITIES,
  ...REPUTATION_CAPABILITIES,
  ...SCHEDULING_CAPABILITIES,
  ...CONTENT_CAPABILITIES,
  ...SEO_CAPABILITIES,
  ...LIFECYCLE_EVENTS,
  ...COMPLIANCE_REQUIREMENTS,
  ...SECURITY_REQUIREMENTS,
  ...PAYMENT_SYSTEM_CAPABILITIES,
  "PAGES_PER_MONTH_ENTITLEMENT",
  "DIGITAL_DELIVERY",
  "INVENTORY",
  "PHYSICAL_FULFILLMENT",
] as const;

export type SystemCapability = (typeof SYSTEM_CAPABILITY_CATALOG)[number];

export const BUILD_DEPENDENCY_ORDER = [
  "IDENTITY_AND_ACCOUNTS",
  "AUTHORIZATION_AND_ROLES",
  "SECURITY_AND_RISK",
  "LEGAL_AND_COMPLIANCE",
  "PAYMENTS",
  "ENTITLEMENTS",
  "COMMERCE_AND_FULFILLMENT",
  "LEAD_CAPTURE",
  "CRM",
  "SCHEDULING",
  "TRANSACTIONAL_EMAIL",
  "SMS",
  "MARKETING_EMAIL",
  "ANALYTICS",
  "ATTRIBUTION",
  "CUSTOMER_SUPPORT",
  "CUSTOMER_SUCCESS",
  "REPUTATION_AND_REVIEWS",
  "LIFECYCLE_AUTOMATION",
  "CONTENT_AND_DISTRIBUTION",
  "SEO",
  "CUSTOMER_ACQUISITION",
  "SOCIAL_DISTRIBUTION",
  "OPERATIONS",
  "EXPERIMENTATION",
  "AFFILIATE_AND_PARTNERS",
  "LOCALIZATION",
  "HUMAN_OPERATIONS",
] as const satisfies readonly SystemFamily[];

export const BLOCKED_SYSTEM_WRITES = [
  "createCrmAccount",
  "sendEmail",
  "sendSms",
  "createProviderAccount",
  "purchaseSubscription",
  "chargeCard",
  "moveBankFunds",
  "writeStripe",
  "writeDns",
  "writeRegistrar",
  "deploy",
  "executeExternalAction",
] as const;

export type BlockedSystemWrite = (typeof BLOCKED_SYSTEM_WRITES)[number];
