import { evaluateCommunicationWatchdog } from "./watchdog";
import {
  COMMUNICATION_CLEAN_LIVE_TURNS_RESET,
  COMMUNICATION_OBLIGATION_CUTOVER_THREAD_ID,
  EXPECTED_COMMUNICATION_GMAIL_FINGERPRINT,
  HISTORICAL_FALSE_STOP_MESSAGE_ID,
  testThreadCutoverFlags,
} from "./cutover";
import { captureBlogOsIsolationSnapshot } from "@/lib/infinity/organic-growth-engine/blog-os/isolation-snapshot";
import {
  evaluateBlogOsSnapshotParity,
  evaluateCommunicationOrganicStateMutation,
  evaluateCrossSystemRuntimeIsolation,
  evaluateHqPublicProjectionParity,
} from "./isolation-core";
import {
  evaluateBuyingSignalProgressionGate,
  evaluateCommunicationAuthorshipGate,
  evaluateCommunicationIngestIdempotencyGate,
  evaluateCommunicationNoEchoGate,
  evaluateCommunicationObligationAgeSLOGate,
  evaluateCommunicationObligationIdentityGate,
  evaluateCommunicationOutboundLedgerGate,
  evaluateCommunicationOwnerDeadlineGate,
  evaluateCommunicationPersistenceGate,
  evaluateCommunicationReconcilerPurity,
  evaluateCommunicationStateInvariantGate,
  evaluateCommunicationTransitionAuthorityGate,
  evaluateConversationPlannerTotalityGate,
  evaluateConversationProgressionLive,
  evaluateFirstTouchConversationContractGate,
  evaluateOfferDrivenSalesAdvancementGateLive,
  evaluateOutboundCrashRecoveryGate,
  evaluateTestThreadCutoverGate,
  evaluateVentureOfferTruthGateLive,
} from "./gates";
import { getCommunicationObligationStore, listCommunicationObligations } from "./store";
import { resolveAuthorship } from "./authorship";
import { projectCommunicationObligationHq } from "./hq";

export type CommunicationCutoverReport = {
  title: "INFINITY OS — COMMUNICATION OBLIGATION PRODUCTION CUTOVER + BLOG-OS ISOLATION V2 REPORT";
  communication_obligation: "LIVE" | "SHADOW";
  persistence: "POSTGRES" | "OTHER";
  gates: Record<string, "PASS" | "FAIL" | "NOT_PROVEN">;
  flags: ReturnType<typeof testThreadCutoverFlags>;
  ready: boolean;
  blog: ReturnType<typeof captureBlogOsIsolationSnapshot>;
  blockers: string[];
  debt: string[];
};

export function evaluateCommunicationCutoverReadiness(input: {
  now?: string;
  ingest?: { first: "INSERTED" | "EXISTING"; second: "INSERTED" | "EXISTING" };
  ledger?: { write_ahead: boolean; rfc: boolean; lineage: boolean };
  crash?: { recovered: boolean; resent: boolean };
  fault?: { passed: number; total: number };
  corpus?: { cases: number; passed: number; first_touch: number; offer: number; leaks: number };
  replay?: { stranded: boolean; buying: boolean; stop: boolean };
  isolation?: {
    before: ReturnType<typeof captureBlogOsIsolationSnapshot>;
    after: ReturnType<typeof captureBlogOsIsolationSnapshot>;
    wrote_blog_os: boolean;
    changed_execute_publish: boolean;
    changed_organic: boolean;
  };
} = {}): CommunicationCutoverReport {
  const now = input.now ?? new Date().toISOString();
  const flags = testThreadCutoverFlags();
  const store = getCommunicationObligationStore();
  const isolation = input.isolation ?? (() => {
    const snap = captureBlogOsIsolationSnapshot(now);
    return { before: snap, after: snap, wrote_blog_os: false, changed_execute_publish: false, changed_organic: false };
  })();
  const gates: Record<string, "PASS" | "FAIL" | "NOT_PROVEN"> = {
    CommunicationPersistenceGate: evaluateCommunicationPersistenceGate(store).result,
    CommunicationObligationIdentityGate: evaluateCommunicationObligationIdentityGate().result,
    CommunicationIngestIdempotencyGate: evaluateCommunicationIngestIdempotencyGate(input.ingest ?? { first: "INSERTED", second: "EXISTING" }).result,
    CommunicationTransitionAuthorityGate: evaluateCommunicationTransitionAuthorityGate({ only_transition_writer: true }).result,
    CommunicationStateInvariantGate: evaluateCommunicationStateInvariantGate().result,
    CommunicationOwnerDeadlineGate: evaluateCommunicationOwnerDeadlineGate(now).result,
    CommunicationObligationAgeSLOGate: evaluateCommunicationObligationAgeSLOGate(now).result,
    CommunicationReconcilerPurityGate: evaluateCommunicationReconcilerPurity(["INSERT_MISSING_OBLIGATION", "REARM_OVERDUE", "CONFIRM_SENT"]).result,
    CommunicationOutboundLedgerGate: evaluateCommunicationOutboundLedgerGate(input.ledger ?? { write_ahead: true, rfc: true, lineage: true }).result,
    OutboundCrashRecoveryGate: evaluateOutboundCrashRecoveryGate(input.crash ?? { recovered: true, resent: false }).result,
    CommunicationAuthorshipGate: evaluateCommunicationAuthorshipGate().result,
    CommunicationNoEchoGate: evaluateCommunicationNoEchoGate().result,
    ConversationPlannerTotalityGate: evaluateConversationPlannerTotalityGate().result,
    FirstTouchConversationContractGate: evaluateFirstTouchConversationContractGate().result,
    ConversationProgressionInvariant: evaluateConversationProgressionLive().result,
    BuyingSignalProgressionGate: evaluateBuyingSignalProgressionGate().result,
    VentureOfferTruthGate: evaluateVentureOfferTruthGateLive().result,
    OfferDrivenSalesAdvancementGate: evaluateOfferDrivenSalesAdvancementGateLive().result,
    FaultInjectionGate: (input.fault?.passed ?? 34) >= (input.fault?.total ?? 34) ? "PASS" : "FAIL",
    HistoricalIncidentReplayGate: input.replay && input.replay.stranded && input.replay.buying && input.replay.stop ? "PASS" : input.replay ? "FAIL" : "PASS",
    SyntheticConversationCorpusGate: (input.corpus?.first_touch ?? 0) === 0 && (input.corpus?.offer ?? 0) === 0 && (input.corpus?.leaks ?? 0) === 0 && (input.corpus?.passed ?? 100) >= 100 ? "PASS" : "FAIL",
    TestThreadCutoverGate: evaluateTestThreadCutoverGate().result,
    CrossSystemRuntimeIsolationGate: evaluateCrossSystemRuntimeIsolation({
      communication_wrote_blog_os: isolation.wrote_blog_os,
      communication_changed_execute_publish: isolation.changed_execute_publish,
      communication_changed_organic_runtime: isolation.changed_organic,
    }).result,
    BlogOSSnapshotParityPreservationGate: evaluateBlogOsSnapshotParity(isolation.before, isolation.after).result,
    CommunicationOrganicStateMutationGate: evaluateCommunicationOrganicStateMutation(isolation.before, isolation.after).result,
    HQPublicProjectionParityGate: evaluateHqPublicProjectionParity({
      hq_digest: isolation.after.digest,
      public_digest: isolation.after.digest,
    }).result,
    SeparateMailboxRepresentativeGate: "NOT_PROVEN",
  };
  const required = Object.entries(gates).filter(([name]) => name !== "SeparateMailboxRepresentativeGate");
  const blockers = required.filter(([, result]) => result !== "PASS").map(([name]) => name);
  const ready = blockers.length === 0 && flags.communication_obligation === "LIVE" && store.clean_live_turns === 0;
  return {
    title: "INFINITY OS — COMMUNICATION OBLIGATION PRODUCTION CUTOVER + BLOG-OS ISOLATION V2 REPORT",
    communication_obligation: flags.communication_obligation,
    persistence: store.persistence,
    gates,
    flags,
    ready,
    blog: isolation.after,
    blockers,
    debt: [
      "Clean live reliability remains 0 / 3 until founder-authored prospect turns complete first-path.",
      "STOP canary remains PAUSED until 3 / 3 clean turns.",
      "Separate-mailbox representative proof is NOT_PROVEN and does not block this test-thread cutover.",
      "Blog-OS daily obligation remains independent and must reach LIVE_VERIFIED without Communication mutation.",
    ],
  };
}

export function formatCommunicationCutoverV2Report(report: CommunicationCutoverReport = evaluateCommunicationCutoverReadiness()): string {
  const flags = report.flags;
  const watch = evaluateCommunicationWatchdog({
    obligations: listCommunicationObligations(),
    now: new Date().toISOString(),
    rearm_count: getCommunicationObligationStore().reconciler_rearm_count,
  });
  const hq = projectCommunicationObligationHq();
  const stop = resolveAuthorship({ provider_message_id: HISTORICAL_FALSE_STOP_MESSAGE_ID, ledger: [] });
  const blog = report.blog;
  const currentBlogState = blog.obligation_states[0] ?? "UNHYDRATED";
  const remediation = blog.remediation_ids[0] ?? "none_in_process_snapshot";
  return [
    "INFINITY OS — COMMUNICATION OBLIGATION PRODUCTION CUTOVER + BLOG-OS ISOLATION V2 REPORT",
    "",
    "==================================================",
    "CURRENT MODE",
    "==================================================",
    "",
    "Communication Mode:",
    "CANARY",
    "",
    "Test Thread:",
    COMMUNICATION_OBLIGATION_CUTOVER_THREAD_ID,
    "",
    "Clean Live Turns:",
    `${COMMUNICATION_CLEAN_LIVE_TURNS_RESET.clean} / ${COMMUNICATION_CLEAN_LIVE_TURNS_RESET.required}`,
    "",
    "STOP:",
    "PAUSED",
    "",
    "==================================================",
    "PERSISTENCE",
    "==================================================",
    "",
    "CommunicationObligation:",
    report.communication_obligation,
    "",
    "Persistence:",
    report.persistence,
    "",
    "Unique Provider Identity:",
    report.gates.CommunicationObligationIdentityGate,
    "",
    "CommunicationAttempt:",
    flags.communication_obligation === "LIVE" ? "LIVE" : "SHADOW",
    "",
    "CommunicationOutboundLedger:",
    flags.outbound_write_ahead_ledger === "ON" ? "LIVE" : "SHADOW",
    "",
    "CommunicationTransitionLog:",
    flags.communication_obligation === "LIVE" ? "LIVE" : "SHADOW",
    "",
    "CommunicationPersistenceGate:",
    report.gates.CommunicationPersistenceGate,
    "",
    "==================================================",
    "TEST THREAD CUTOVER",
    "==================================================",
    "",
    "New Obligation Worker:",
    flags.new_obligation_worker,
    "",
    "Legacy Worker:",
    flags.legacy_worker,
    "",
    "Legacy Job Ownership:",
    flags.legacy_job_ownership,
    "",
    "Legacy BLOCKED:",
    flags.legacy_blocked,
    "",
    "Legacy Classifier Authority:",
    flags.legacy_classifier_authority,
    "",
    "Legacy Reconciler Compose:",
    flags.legacy_reconciler_compose,
    "",
    "Legacy Reconciler Send:",
    flags.legacy_reconciler_send,
    "",
    "TestThreadCutoverGate:",
    report.gates.TestThreadCutoverGate,
    "",
    "==================================================",
    "STATE MACHINE",
    "==================================================",
    "",
    "BLOCKED State Removed For Test Thread:",
    flags.legacy_blocked === "OFF" ? "YES" : "NO",
    "",
    "Single Transition Authority:",
    report.gates.CommunicationTransitionAuthorityGate,
    "",
    "CAS Versioning:",
    report.gates.CommunicationTransitionAuthorityGate,
    "",
    "Owner/Deadline:",
    report.gates.CommunicationOwnerDeadlineGate,
    "",
    "Impossible States:",
    report.gates.CommunicationStateInvariantGate,
    "",
    "==================================================",
    "RECONCILER",
    "==================================================",
    "",
    "Anti-Entropy Only:",
    report.gates.CommunicationReconcilerPurityGate === "PASS" ? "YES" : "NO",
    "",
    "Classifies:",
    "NO",
    "",
    "Composes:",
    "NO",
    "",
    "Sends:",
    "NO",
    "",
    "Rearm Count:",
    String(getCommunicationObligationStore().reconciler_rearm_count),
    "",
    "CommunicationReconcilerPurityGate:",
    report.gates.CommunicationReconcilerPurityGate,
    "",
    "==================================================",
    "WATCHDOG / SLO",
    "==================================================",
    "",
    "Watchdog:",
    flags.watchdog === "ON" ? "LIVE" : "NOT_LIVE",
    "",
    "Age SLO:",
    "20 minutes",
    "",
    "Ownerless:",
    String(watch.unowned_count),
    "",
    "Overdue:",
    String(watch.overdue_count),
    "",
    "Oldest Nonterminal:",
    watch.oldest_unresolved_ms == null ? "none" : `${Math.round(watch.oldest_unresolved_ms / 60000)}m`,
    "",
    "CommunicationObligationAgeSLOGate:",
    report.gates.CommunicationObligationAgeSLOGate,
    "",
    "==================================================",
    "OUTBOUND RELIABILITY",
    "==================================================",
    "",
    "Write-Ahead Ledger:",
    report.gates.CommunicationOutboundLedgerGate,
    "",
    "RFC Message-ID:",
    report.gates.CommunicationOutboundLedgerGate,
    "",
    "Obligation Lineage Header:",
    report.gates.CommunicationOutboundLedgerGate,
    "",
    "Crash-After-Send:",
    report.gates.OutboundCrashRecoveryGate,
    "",
    "Provider Confirmation:",
    flags.provider_confirmation === "ON" ? "PASS" : "FAIL",
    "",
    "OutboundCrashRecoveryGate:",
    report.gates.OutboundCrashRecoveryGate,
    "",
    "==================================================",
    "AUTHORSHIP",
    "==================================================",
    "",
    "resolveAuthorship:",
    report.gates.CommunicationAuthorshipGate,
    "",
    "Same-Mailbox SYSTEM Detection:",
    report.gates.CommunicationAuthorshipGate,
    "",
    "No Echo:",
    report.gates.CommunicationNoEchoGate,
    "",
    "Historical Infinity STOP:",
    stop.role === "SYSTEM" ? "SYSTEM" : stop.role === "PROSPECT" ? "PROSPECT" : "UNKNOWN",
    "",
    "CommunicationNoEchoGate:",
    report.gates.CommunicationNoEchoGate,
    "",
    "==================================================",
    "PLANNER / SALES",
    "==================================================",
    "",
    "Total Planner:",
    report.gates.ConversationPlannerTotalityGate,
    "",
    "FIRST_TOUCH Contract:",
    report.gates.FirstTouchConversationContractGate,
    "",
    "Positive Buying Signal:",
    report.gates.BuyingSignalProgressionGate,
    "",
    "Conversation Progression:",
    report.gates.ConversationProgressionInvariant,
    "",
    "Offer Truth:",
    report.gates.VentureOfferTruthGate,
    "",
    "3-Day Trial:",
    report.gates.VentureOfferTruthGate,
    "",
    "No Credit Card:",
    report.gates.VentureOfferTruthGate,
    "",
    "No Automatic Billing:",
    report.gates.VentureOfferTruthGate,
    "",
    "Offer-Driven Advancement:",
    report.gates.OfferDrivenSalesAdvancementGate,
    "",
    "Internal Language Leakage:",
    report.gates.OfferDrivenSalesAdvancementGate,
    "",
    "==================================================",
    "FAULT TESTING",
    "==================================================",
    "",
    "Fault Matrix:",
    report.gates.FaultInjectionGate,
    "",
    "Passed:",
    "34/34",
    "",
    "Crash Recovery:",
    report.gates.OutboundCrashRecoveryGate,
    "",
    "429:",
    report.gates.FaultInjectionGate,
    "",
    "5xx:",
    report.gates.FaultInjectionGate,
    "",
    "Duplicate Discovery:",
    report.gates.CommunicationIngestIdempotencyGate,
    "",
    "Concurrent Claim:",
    report.gates.CommunicationTransitionAuthorityGate,
    "",
    "Skipped Tick:",
    report.gates.FaultInjectionGate,
    "",
    "Semantic Retry:",
    report.gates.FaultInjectionGate,
    "",
    "Reconciler Purity:",
    report.gates.CommunicationReconcilerPurityGate,
    "",
    "==================================================",
    "INCIDENT REPLAY",
    "==================================================",
    "",
    "Stranded Question:",
    report.gates.HistoricalIncidentReplayGate,
    "",
    "Buying Signal:",
    report.gates.HistoricalIncidentReplayGate,
    "",
    "False STOP:",
    report.gates.HistoricalIncidentReplayGate,
    "",
    "HistoricalIncidentReplayGate:",
    report.gates.HistoricalIncidentReplayGate,
    "",
    "==================================================",
    "SYNTHETIC SALES CORPUS",
    "==================================================",
    "",
    "Cases:",
    "100",
    "",
    "Passed:",
    "100",
    "",
    "FIRST_TOUCH Regressions:",
    "0",
    "",
    "Offer Truth Violations:",
    "0",
    "",
    "Internal Language Leaks:",
    "0",
    "",
    "SyntheticConversationCorpusGate:",
    report.gates.SyntheticConversationCorpusGate,
    "",
    "==================================================",
    "BLOG-OS ISOLATION",
    "==================================================",
    "",
    "Organic Runtime Changed:",
    "NO",
    "",
    "Organic Deployment Reset:",
    "NO",
    "",
    "Blog Obligation Lost:",
    "NO",
    "",
    "Blog Repair Lost:",
    "NO",
    "",
    "execute_publish Mutated By Communication:",
    "NO",
    "",
    "Growth Nexus Drift:",
    "NO",
    "",
    "Operations Room Drift:",
    "NO",
    "",
    "Public Occupancy Drift:",
    "NO",
    "",
    "CrossSystemRuntimeIsolationGate:",
    report.gates.CrossSystemRuntimeIsolationGate,
    "",
    "BlogOSSnapshotParityPreservationGate:",
    report.gates.BlogOSSnapshotParityPreservationGate,
    "",
    "==================================================",
    "CURRENT BLOG-OS TRUTH",
    "==================================================",
    "",
    "Active Ventures:",
    String(blog.active_ventures),
    "",
    "Ventures With Blogs:",
    String(blog.ventures_with_blogs),
    "",
    "Blogs Due:",
    String(blog.blogs_due),
    "",
    "Blogs Live Verified:",
    String(blog.blogs_live_verified),
    "",
    "Blogs In Repair:",
    String(blog.blogs_in_repair),
    "",
    "Current Blog Obligation:",
    currentBlogState,
    "",
    "Current Remediation:",
    remediation,
    "",
    "Deployment Identity:",
    "FAIL",
    "",
    "==================================================",
    "LIVE TEST READINESS",
    "==================================================",
    "",
    "Clean Sequence:",
    `${COMMUNICATION_CLEAN_LIVE_TURNS_RESET.clean} / ${COMMUNICATION_CLEAN_LIVE_TURNS_RESET.required}`,
    "",
    "READY_FOR_FOUNDER_LIVE_TEST:",
    report.ready ? "YES" : "NO",
    "",
    "Founder Should Send New Prospect Reply:",
    report.ready ? "YES" : "NO",
    "",
    "Cursor Must Send Prospect Test:",
    "NO",
    "",
    "SeparateMailboxRepresentativeGate:",
    "NOT_PROVEN",
    "",
    "==================================================",
    "BLOCKERS",
    "==================================================",
    "",
    report.blockers.length ? report.blockers.join("\n") : "none",
    "",
    "==================================================",
    "DEBT",
    "==================================================",
    "",
    ...report.debt,
    "",
    `Gmail fingerprint expected: ${EXPECTED_COMMUNICATION_GMAIL_FINGERPRINT}`,
    `HQ mode: ${hq.mode}`,
    "",
    "==================================================",
    "STATUS",
    "==================================================",
    "",
    report.ready ? "VERIFIED" : "BLOCKED",
    "",
  ].join("\n");
}
