import type { VentureSandbox } from "@/lib/infinity/product-asset-builder/workspace/sandbox";

async function writeScaffoldFile(
  sandbox: VentureSandbox,
  files: string[],
  relativePath: string,
  content: string,
): Promise<void> {
  await sandbox.writeTextFile(relativePath, content);
  files.push(relativePath);
}

function lines(...parts: string[]): string {
  return `${parts.join("\n")}\n`;
}

function generatePackageJson(): string {
  return `${JSON.stringify(
    {
      name: "creator-marketplace",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        test: "vitest run",
      },
      dependencies: {
        next: "16.2.11",
        react: "19.2.4",
        "react-dom": "19.2.4",
        bcryptjs: "^3.0.2",
        jose: "^6.0.11",
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        "@types/bcryptjs": "^2.4.6",
        vitest: "^3.2.4",
      },
    },
    null,
    2,
  )}\n`;
}

function generateNextConfig(): string {
  return lines(
    `/** @type {import('next').NextConfig} */`,
    `const nextConfig = {`,
    `  typescript: { ignoreBuildErrors: false },`,
    `  turbopack: { root: import.meta.dirname },`,
    `};`,
    `export default nextConfig;`,
  );
}

function generateTsConfig(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2,
  )}\n`;
}

function generateVitestConfig(): string {
  return lines(
    `import path from "node:path";`,
    `import { defineConfig } from "vitest/config";`,
    ``,
    `export default defineConfig({`,
    `  test: { environment: "node" },`,
    `  resolve: { alias: { "@": path.resolve(__dirname, ".") } },`,
    `});`,
  );
}

function generateStoreTs(): string {
  return lines(
    `import { mkdir, readFile, writeFile } from "node:fs/promises";`,
    `import path from "node:path";`,
    ``,
    `export type UserRole = "creator" | "consumer";`,
    `export type PostStatus = "published" | "hidden" | "removed";`,
    `export type ListingStatus = "active" | "draft" | "removed";`,
    `export type TransactionStatus = "pending" | "paid" | "completed" | "cancelled" | "refunded";`,
    `export type SubscriptionStatus = "active" | "cancelled" | "expired";`,
    `export type ReportStatus = "open" | "resolved" | "dismissed";`,
    ``,
    `export type User = {`,
    `  id: string;`,
    `  email: string;`,
    `  passwordHash: string;`,
    `  role: UserRole;`,
    `  isModerator: boolean;`,
    `  displayName: string;`,
    `  createdAt: string;`,
    `};`,
    ``,
    `export type SessionRecord = {`,
    `  id: string;`,
    `  userId: string;`,
    `  tokenId: string;`,
    `  expiresAt: string;`,
    `  createdAt: string;`,
    `};`,
    ``,
    `export type CreatorProfile = {`,
    `  id: string;`,
    `  userId: string;`,
    `  headline: string;`,
    `  bio: string;`,
    `  avatarUrl: string;`,
    `  updatedAt: string;`,
    `};`,
    ``,
    `export type Post = {`,
    `  id: string;`,
    `  creatorId: string;`,
    `  title: string;`,
    `  body: string;`,
    `  mediaUrl: string;`,
    `  status: PostStatus;`,
    `  createdAt: string;`,
    `  updatedAt: string;`,
    `};`,
    ``,
    `export type Like = { id: string; userId: string; postId: string; createdAt: string };`,
    `export type Comment = { id: string; userId: string; postId: string; body: string; createdAt: string };`,
    `export type Follow = { id: string; followerId: string; creatorId: string; createdAt: string };`,
    ``,
    `export type Listing = {`,
    `  id: string;`,
    `  creatorId: string;`,
    `  title: string;`,
    `  description: string;`,
    `  priceCents: number;`,
    `  status: ListingStatus;`,
    `  createdAt: string;`,
    `  updatedAt: string;`,
    `};`,
    ``,
    `export type Transaction = {`,
    `  id: string;`,
    `  listingId: string;`,
    `  buyerId: string;`,
    `  sellerId: string;`,
    `  amountCents: number;`,
    `  commissionCents: number;`,
    `  sellerPayoutCents: number;`,
    `  status: TransactionStatus;`,
    `  createdAt: string;`,
    `  updatedAt: string;`,
    `};`,
    ``,
    `export type Subscription = {`,
    `  id: string;`,
    `  userId: string;`,
    `  planId: string;`,
    `  status: SubscriptionStatus;`,
    `  startedAt: string;`,
    `  expiresAt: string;`,
    `};`,
    ``,
    `export type Report = {`,
    `  id: string;`,
    `  reporterId: string;`,
    `  targetType: "post" | "listing" | "comment" | "user";`,
    `  targetId: string;`,
    `  reason: string;`,
    `  status: ReportStatus;`,
    `  createdAt: string;`,
    `};`,
    ``,
    `export type ModerationAction = {`,
    `  id: string;`,
    `  moderatorId: string;`,
    `  targetType: "post" | "listing" | "comment" | "user" | "report";`,
    `  targetId: string;`,
    `  action: "hide" | "remove" | "restore" | "dismiss" | "resolve";`,
    `  note: string;`,
    `  createdAt: string;`,
    `};`,
    ``,
    `export type DataStore = {`,
    `  users: User[];`,
    `  sessions: SessionRecord[];`,
    `  creatorProfiles: CreatorProfile[];`,
    `  posts: Post[];`,
    `  likes: Like[];`,
    `  comments: Comment[];`,
    `  follows: Follow[];`,
    `  listings: Listing[];`,
    `  transactions: Transaction[];`,
    `  subscriptions: Subscription[];`,
    `  reports: Report[];`,
    `  moderationActions: ModerationAction[];`,
    `};`,
    ``,
    `const STORE_PATH = path.join(process.cwd(), "data", "store.json");`,
    ``,
    `export function emptyStore(): DataStore {`,
    `  return {`,
    `    users: [],`,
    `    sessions: [],`,
    `    creatorProfiles: [],`,
    `    posts: [],`,
    `    likes: [],`,
    `    comments: [],`,
    `    follows: [],`,
    `    listings: [],`,
    `    transactions: [],`,
    `    subscriptions: [],`,
    `    reports: [],`,
    `    moderationActions: [],`,
    `  };`,
    `}`,
    ``,
    `export async function readStore(): Promise<DataStore> {`,
    `  await mkdir(path.dirname(STORE_PATH), { recursive: true });`,
    `  try {`,
    `    const raw = await readFile(STORE_PATH, "utf8");`,
    `    return JSON.parse(raw) as DataStore;`,
    `  } catch {`,
    `    const initial = emptyStore();`,
    `    await writeFile(STORE_PATH, JSON.stringify(initial, null, 2), "utf8");`,
    `    return initial;`,
    `  }`,
    `}`,
    ``,
    `export async function writeStore(store: DataStore): Promise<void> {`,
    `  await mkdir(path.dirname(STORE_PATH), { recursive: true });`,
    `  await writeFile(STORE_PATH, JSON.stringify(store, null, 2), "utf8");`,
    `}`,
    ``,
    `export async function mutateStore<T>(fn: (store: DataStore) => T): Promise<T> {`,
    `  const store = await readStore();`,
    `  const result = fn(store);`,
    `  await writeStore(store);`,
    `  return result;`,
    `}`,
    ``,
    `export function createId(prefix: string): string {`,
    `  return \`\${prefix}_\${Date.now()}_\${Math.random().toString(36).slice(2, 9)}\`;`,
    `}`,
    ``,
    `export function findUserByEmail(store: DataStore, email: string): User | undefined {`,
    `  return store.users.find((user) => user.email.toLowerCase() === email.toLowerCase());`,
    `}`,
    ``,
    `export function findUserById(store: DataStore, userId: string): User | undefined {`,
    `  return store.users.find((user) => user.id === userId);`,
    `}`,
    ``,
    `export function canUserEditPost(userId: string, post: Post): boolean {`,
    `  return post.creatorId === userId;`,
    `}`,
    ``,
    `export function canUserEditListing(userId: string, listing: Listing): boolean {`,
    `  return listing.creatorId === userId;`,
    `}`,
    ``,
    `export function applyModerationAction(`,
    `  store: DataStore,`,
    `  action: Omit<ModerationAction, "id" | "createdAt">,`,
    `): ModerationAction {`,
    `  const record: ModerationAction = {`,
    `    ...action,`,
    `    id: createId("mod"),`,
    `    createdAt: new Date().toISOString(),`,
    `  };`,
    `  store.moderationActions.push(record);`,
    `  if (action.targetType === "post" && (action.action === "hide" || action.action === "remove")) {`,
    `    const post = store.posts.find((item) => item.id === action.targetId);`,
    `    if (post) {`,
    `      post.status = action.action === "hide" ? "hidden" : "removed";`,
    `      post.updatedAt = record.createdAt;`,
    `    }`,
    `  }`,
    `  if (action.targetType === "listing" && action.action === "remove") {`,
    `    const listing = store.listings.find((item) => item.id === action.targetId);`,
    `    if (listing) {`,
    `      listing.status = "removed";`,
    `      listing.updatedAt = record.createdAt;`,
    `    }`,
    `  }`,
    `  if (action.targetType === "report") {`,
    `    const report = store.reports.find((item) => item.id === action.targetId);`,
    `    if (report) {`,
    `      report.status = action.action === "dismiss" ? "dismissed" : "resolved";`,
    `    }`,
    `  }`,
    `  return record;`,
    `}`,
  );
}

function generateAuthPasswordTs(): string {
  return lines(
    `import bcrypt from "bcryptjs";`,
    ``,
    `const ROUNDS = 10;`,
    ``,
    `export async function hashPassword(password: string): Promise<string> {`,
    `  return bcrypt.hash(password, ROUNDS);`,
    `}`,
    ``,
    `export async function verifyPassword(password: string, passwordHash: string): Promise<boolean> {`,
    `  return bcrypt.compare(password, passwordHash);`,
    `}`,
  );
}

function generateAuthSessionTs(): string {
  return lines(
    `import { SignJWT, jwtVerify } from "jose";`,
    `import { cookies } from "next/headers";`,
    `import { findUserById, readStore, type User } from "@/lib/db/store";`,
    ``,
    `export const SESSION_COOKIE = "marketplace_session";`,
    `const SESSION_TTL_SECONDS = 60 * 60 * 24 * 7;`,
    ``,
    `export type SessionPayload = {`,
    `  userId: string;`,
    `  role: User["role"];`,
    `  isModerator: boolean;`,
    `  tokenId: string;`,
    `};`,
    ``,
    `function getSecret(): Uint8Array {`,
    `  const secret = process.env.JWT_SECRET ?? "marketplace-dev-secret-change-me";`,
    `  return new TextEncoder().encode(secret);`,
    `}`,
    ``,
    `export async function createSessionToken(payload: SessionPayload): Promise<string> {`,
    `  return new SignJWT(payload)`,
    `    .setProtectedHeader({ alg: "HS256" })`,
    `    .setIssuedAt()`,
    `    .setExpirationTime(\`\${SESSION_TTL_SECONDS}s\`)`,
    `    .sign(getSecret());`,
    `}`,
    ``,
    `export async function verifySessionToken(token: string): Promise<SessionPayload | null> {`,
    `  try {`,
    `    const { payload } = await jwtVerify(token, getSecret());`,
    `    return payload as SessionPayload;`,
    `  } catch {`,
    `    return null;`,
    `  }`,
    `}`,
    ``,
    `export async function setSessionCookie(token: string): Promise<void> {`,
    `  const cookieStore = await cookies();`,
    `  cookieStore.set(SESSION_COOKIE, token, {`,
    `    httpOnly: true,`,
    `    sameSite: "lax",`,
    `    secure: process.env.NODE_ENV === "production",`,
    `    path: "/",`,
    `    maxAge: SESSION_TTL_SECONDS,`,
    `  });`,
    `}`,
    ``,
    `export async function clearSessionCookie(): Promise<void> {`,
    `  const cookieStore = await cookies();`,
    `  cookieStore.set(SESSION_COOKIE, "", { httpOnly: true, path: "/", maxAge: 0 });`,
    `}`,
    ``,
    `export async function getCurrentUser(): Promise<User | null> {`,
    `  const cookieStore = await cookies();`,
    `  const token = cookieStore.get(SESSION_COOKIE)?.value;`,
    `  if (!token) return null;`,
    `  const payload = await verifySessionToken(token);`,
    `  if (!payload) return null;`,
    `  const store = await readStore();`,
    `  return findUserById(store, payload.userId) ?? null;`,
    `}`,
    ``,
    `export async function requireCurrentUser(): Promise<User> {`,
    `  const user = await getCurrentUser();`,
    `  if (!user) throw new Error("Unauthorized");`,
    `  return user;`,
    `}`,
  );
}

function generateCommissionTs(): string {
  return lines(
    `export type CommissionResult = { commissionCents: number; sellerPayoutCents: number };`,
    ``,
    `export function calculateCommission(amountCents: number, takeRate: number): CommissionResult {`,
    `  if (amountCents < 0) throw new Error("Amount must be non-negative");`,
    `  if (takeRate < 0 || takeRate > 1) throw new Error("Take rate must be between 0 and 1");`,
    `  const commissionCents = Math.round(amountCents * takeRate);`,
    `  const sellerPayoutCents = amountCents - commissionCents;`,
    `  return { commissionCents, sellerPayoutCents };`,
    `}`,
  );
}

function generateTransactionsTs(): string {
  return lines(
    `import { calculateCommission } from "@/lib/marketplace/commission";`,
    `import { createId, type Transaction, type TransactionStatus } from "@/lib/db/store";`,
    ``,
    `export type { TransactionStatus };`,
    ``,
    `export const DEFAULT_TAKE_RATE = 0.15;`,
    ``,
    `const ALLOWED: Record<TransactionStatus, TransactionStatus[]> = {`,
    `  pending: ["paid", "cancelled"],`,
    `  paid: ["completed", "refunded"],`,
    `  completed: [],`,
    `  cancelled: [],`,
    `  refunded: [],`,
    `};`,
    ``,
    `export function canTransition(from: TransactionStatus, to: TransactionStatus): boolean {`,
    `  return ALLOWED[from].includes(to);`,
    `}`,
    ``,
    `export function transitionTransaction(transaction: Transaction, to: TransactionStatus): Transaction {`,
    `  if (!canTransition(transaction.status, to)) {`,
    `    throw new Error(\`Invalid transition from \${transaction.status} to \${to}\`);`,
    `  }`,
    `  return { ...transaction, status: to, updatedAt: new Date().toISOString() };`,
    `}`,
    ``,
    `export function initiateTransaction(input: {`,
    `  listingId: string;`,
    `  buyerId: string;`,
    `  sellerId: string;`,
    `  amountCents: number;`,
    `  takeRate?: number;`,
    `}): Transaction {`,
    `  const { commissionCents, sellerPayoutCents } = calculateCommission(`,
    `    input.amountCents,`,
    `    input.takeRate ?? DEFAULT_TAKE_RATE,`,
    `  );`,
    `  const now = new Date().toISOString();`,
    `  return {`,
    `    id: createId("txn"),`,
    `    listingId: input.listingId,`,
    `    buyerId: input.buyerId,`,
    `    sellerId: input.sellerId,`,
    `    amountCents: input.amountCents,`,
    `    commissionCents,`,
    `    sellerPayoutCents,`,
    `    status: "pending",`,
    `    createdAt: now,`,
    `    updatedAt: now,`,
    `  };`,
    `}`,
  );
}

function generateAnalyticsTs(): string {
  return lines(
    `export type AnalyticsEvent = { name: string; properties?: Record<string, unknown> };`,
    ``,
    `export function trackEvent(event: AnalyticsEvent): void {`,
    `  if (process.env.NODE_ENV !== "production") {`,
    `    console.info("[analytics]", event.name, event.properties ?? {});`,
    `  }`,
    `}`,
  );
}

function generateEntitlementsTs(): string {
  return lines(
    `import type { Subscription } from "@/lib/db/store";`,
    ``,
    `export const PREMIUM_PLAN_ID = "premium_monthly";`,
    ``,
    `export function hasActiveSubscription(userId: string, subscriptions: Subscription[]): boolean {`,
    `  const now = Date.now();`,
    `  return subscriptions.some(`,
    `    (subscription) =>`,
    `      subscription.userId === userId &&`,
    `      subscription.planId === PREMIUM_PLAN_ID &&`,
    `      subscription.status === "active" &&`,
    `      Date.parse(subscription.expiresAt) > now,`,
    `  );`,
    `}`,
    ``,
    `export function createPremiumSubscription(userId: string): Subscription {`,
    `  const startedAt = new Date();`,
    `  const expiresAt = new Date(startedAt);`,
    `  expiresAt.setDate(expiresAt.getDate() + 30);`,
    `  return {`,
    `    id: \`sub_\${Date.now()}_\${Math.random().toString(36).slice(2, 9)}\`,`,
    `    userId,`,
    `    planId: PREMIUM_PLAN_ID,`,
    `    status: "active",`,
    `    startedAt: startedAt.toISOString(),`,
    `    expiresAt: expiresAt.toISOString(),`,
    `  };`,
    `}`,
  );
}

function generateMiddlewareTs(): string {
  return lines(
    `import { jwtVerify } from "jose";`,
    `import { NextResponse } from "next/server";`,
    `import type { NextRequest } from "next/server";`,
    ``,
    `const SESSION_COOKIE = "marketplace_session";`,
    ``,
    `function getSecret(): Uint8Array {`,
    `  const secret = process.env.JWT_SECRET ?? "marketplace-dev-secret-change-me";`,
    `  return new TextEncoder().encode(secret);`,
    `}`,
    ``,
    `export async function middleware(request: NextRequest) {`,
    `  const pathname = request.nextUrl.pathname;`,
    `  const needsAuth = pathname.startsWith("/dashboard") || pathname.startsWith("/admin");`,
    `  if (!needsAuth) return NextResponse.next();`,
    ``,
    `  const token = request.cookies.get(SESSION_COOKIE)?.value;`,
    `  if (!token) {`,
    `    return NextResponse.redirect(new URL("/login", request.url));`,
    `  }`,
    ``,
    `  try {`,
    `    const { payload } = await jwtVerify(token, getSecret());`,
    `    if (pathname.startsWith("/admin") && !payload.isModerator) {`,
    `      return NextResponse.redirect(new URL("/feed", request.url));`,
    `    }`,
    `    return NextResponse.next();`,
    `  } catch {`,
    `    return NextResponse.redirect(new URL("/login", request.url));`,
    `  }`,
    `}`,
    ``,
    `export const config = { matcher: ["/dashboard/:path*", "/admin/:path*"] };`,
  );
}

function generateApiHelpersTs(): string {
  return lines(
    `import { NextResponse } from "next/server";`,
    ``,
    `export function jsonOk<T>(data: T, status = 200) {`,
    `  return NextResponse.json(data, { status });`,
    `}`,
    ``,
    `export function jsonError(message: string, status = 400) {`,
    `  return NextResponse.json({ error: message }, { status });`,
    `}`,
  );
}

function generateAuthApiRoutes(): Record<string, string> {
  return {
    "app/api/auth/register/route.ts": lines(
      `import { hashPassword } from "@/lib/auth/password";`,
      `import { createSessionToken, setSessionCookie } from "@/lib/auth/session";`,
      `import { createId, findUserByEmail, mutateStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function POST(request: Request) {`,
      `  const body = (await request.json()) as {`,
      `    email?: string;`,
      `    password?: string;`,
      `    displayName?: string;`,
      `    role?: "creator" | "consumer";`,
      `  };`,
      `  if (!body.email || !body.password || !body.displayName || !body.role) {`,
      `    return jsonError("Missing required fields", 400);`,
      `  }`,
      `  if (body.password.length < 8) return jsonError("Password must be at least 8 characters", 400);`,
      ``,
      `  try {`,
      `    const user = await mutateStore((store) => {`,
      `      if (findUserByEmail(store, body.email!)) throw new Error("Email already registered");`,
      `      const now = new Date().toISOString();`,
      `      const tokenId = createId("tok");`,
      `      const record = {`,
      `        id: createId("usr"),`,
      `        email: body.email!.toLowerCase(),`,
      `        passwordHash: "",`,
      `        role: body.role!,`,
      `        isModerator: false,`,
      `        displayName: body.displayName!,`,
      `        createdAt: now,`,
      `      };`,
      `      store.users.push(record);`,
      `      if (body.role === "creator") {`,
      `        store.creatorProfiles.push({`,
      `          id: createId("prof"),`,
      `          userId: record.id,`,
      `          headline: "Creator on the marketplace",`,
      `          bio: "",`,
      `          avatarUrl: "",`,
      `          updatedAt: now,`,
      `        });`,
      `      }`,
      `      store.sessions.push({`,
      `        id: createId("ses"),`,
      `        userId: record.id,`,
      `        tokenId,`,
      `        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),`,
      `        createdAt: now,`,
      `      });`,
      `      return { user: record, tokenId };`,
      `    });`,
      `    const passwordHash = await hashPassword(body.password);`,
      `    await mutateStore((store) => {`,
      `      const target = store.users.find((item) => item.id === user.user.id);`,
      `      if (target) target.passwordHash = passwordHash;`,
      `      return true;`,
      `    });`,
      `    const token = await createSessionToken({`,
      `      userId: user.user.id,`,
      `      role: user.user.role,`,
      `      isModerator: user.user.isModerator,`,
      `      tokenId: user.tokenId,`,
      `    });`,
      `    await setSessionCookie(token);`,
      `    trackEvent({ name: "user_registered", properties: { role: user.user.role } });`,
      `    return jsonOk({ user: { id: user.user.id, email: user.user.email, role: user.user.role, displayName: user.user.displayName } }, 201);`,
      `  } catch (error) {`,
      `    return jsonError(error instanceof Error ? error.message : "Registration failed", 400);`,
      `  }`,
      `}`,
    ),
    "app/api/auth/login/route.ts": lines(
      `import { verifyPassword } from "@/lib/auth/password";`,
      `import { createSessionToken, setSessionCookie } from "@/lib/auth/session";`,
      `import { createId, findUserByEmail, mutateStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function POST(request: Request) {`,
      `  const body = (await request.json()) as { email?: string; password?: string };`,
      `  if (!body.email || !body.password) return jsonError("Email and password required", 400);`,
      `  const storeUser = await mutateStore((store) => findUserByEmail(store, body.email!));`,
      `  if (!storeUser) return jsonError("Invalid credentials", 401);`,
      `  const valid = await verifyPassword(body.password, storeUser.passwordHash);`,
      `  if (!valid) return jsonError("Invalid credentials", 401);`,
      `  const tokenId = createId("tok");`,
      `  await mutateStore((store) => {`,
      `    store.sessions.push({`,
      `      id: createId("ses"),`,
      `      userId: storeUser.id,`,
      `      tokenId,`,
      `      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),`,
      `      createdAt: new Date().toISOString(),`,
      `    });`,
      `    return true;`,
      `  });`,
      `  const token = await createSessionToken({`,
      `    userId: storeUser.id,`,
      `    role: storeUser.role,`,
      `    isModerator: storeUser.isModerator,`,
      `    tokenId,`,
      `  });`,
      `  await setSessionCookie(token);`,
      `  trackEvent({ name: "user_logged_in", properties: { userId: storeUser.id } });`,
      `  return jsonOk({ user: { id: storeUser.id, email: storeUser.email, role: storeUser.role, displayName: storeUser.displayName } });`,
      `}`,
    ),
    "app/api/auth/logout/route.ts": lines(
      `import { clearSessionCookie, getCurrentUser } from "@/lib/auth/session";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function POST() {`,
      `  const user = await getCurrentUser();`,
      `  if (user) trackEvent({ name: "user_logged_out", properties: { userId: user.id } });`,
      `  await clearSessionCookie();`,
      `  return jsonOk({ ok: true });`,
      `}`,
    ),
    "app/api/auth/me/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  return jsonOk({`,
      `    user: {`,
      `      id: user.id,`,
      `      email: user.email,`,
      `      role: user.role,`,
      `      displayName: user.displayName,`,
      `      isModerator: user.isModerator,`,
      `    },`,
      `  });`,
      `}`,
    ),
  };
}

function generateContentApiRoutes(): Record<string, string> {
  return {
    "app/api/posts/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, mutateStore, readStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const store = await readStore();`,
      `  const posts = store.posts.filter((post) => post.status === "published");`,
      `  return jsonOk({ posts });`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  if (user.role !== "creator") return jsonError("Only creators can publish posts", 403);`,
      `  const body = (await request.json()) as { title?: string; body?: string; mediaUrl?: string };`,
      `  if (!body.title || !body.body) return jsonError("Title and body required", 400);`,
      `  const post = await mutateStore((store) => {`,
      `    const now = new Date().toISOString();`,
      `    const record = {`,
      `      id: createId("post"),`,
      `      creatorId: user.id,`,
      `      title: body.title!,`,
      `      body: body.body!,`,
      `      mediaUrl: body.mediaUrl ?? "",`,
      `      status: "published" as const,`,
      `      createdAt: now,`,
      `      updatedAt: now,`,
      `    };`,
      `    store.posts.unshift(record);`,
      `    return record;`,
      `  });`,
      `  trackEvent({ name: "post_created", properties: { postId: post.id, creatorId: user.id } });`,
      `  return jsonOk({ post }, 201);`,
      `}`,
    ),
    "app/api/posts/[id]/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { canUserEditPost, mutateStore, readStore } from "@/lib/db/store";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `type Params = { params: Promise<{ id: string }> };`,
      ``,
      `export async function GET(_request: Request, { params }: Params) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const post = store.posts.find((item) => item.id === id);`,
      `  if (!post || post.status === "removed") return jsonError("Post not found", 404);`,
      `  return jsonOk({ post });`,
      `}`,
      ``,
      `export async function PUT(request: Request, { params }: Params) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const { id } = await params;`,
      `  const body = (await request.json()) as { title?: string; body?: string; mediaUrl?: string };`,
      `  try {`,
      `    const post = await mutateStore((store) => {`,
      `      const existing = store.posts.find((item) => item.id === id);`,
      `      if (!existing) throw new Error("Post not found");`,
      `      if (!canUserEditPost(user.id, existing)) throw new Error("Forbidden");`,
      `      if (body.title) existing.title = body.title;`,
      `      if (body.body) existing.body = body.body;`,
      `      if (body.mediaUrl !== undefined) existing.mediaUrl = body.mediaUrl;`,
      `      existing.updatedAt = new Date().toISOString();`,
      `      return existing;`,
      `    });`,
      `    return jsonOk({ post });`,
      `  } catch (error) {`,
      `    const message = error instanceof Error ? error.message : "Update failed";`,
      `    const status = message === "Forbidden" ? 403 : message === "Post not found" ? 404 : 400;`,
      `    return jsonError(message, status);`,
      `  }`,
      `}`,
      ``,
      `export async function DELETE(_request: Request, { params }: Params) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const { id } = await params;`,
      `  try {`,
      `    await mutateStore((store) => {`,
      `      const existing = store.posts.find((item) => item.id === id);`,
      `      if (!existing) throw new Error("Post not found");`,
      `      if (!canUserEditPost(user.id, existing) && !user.isModerator) throw new Error("Forbidden");`,
      `      existing.status = "removed";`,
      `      existing.updatedAt = new Date().toISOString();`,
      `      return true;`,
      `    });`,
      `    return jsonOk({ ok: true });`,
      `  } catch (error) {`,
      `    const message = error instanceof Error ? error.message : "Delete failed";`,
      `    const status = message === "Forbidden" ? 403 : message === "Post not found" ? 404 : 400;`,
      `    return jsonError(message, status);`,
      `  }`,
      `}`,
    ),
    "app/api/feed/route.ts": lines(
      `import { readStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET(request: Request) {`,
      `  const url = new URL(request.url);`,
      `  const limit = Number(url.searchParams.get("limit") ?? "20");`,
      `  const store = await readStore();`,
      `  const posts = store.posts`,
      `    .filter((post) => post.status === "published")`,
      `    .slice(0, Number.isFinite(limit) ? limit : 20);`,
      `  trackEvent({ name: "feed_viewed", properties: { count: posts.length } });`,
      `  return jsonOk({ posts });`,
      `}`,
    ),
    "app/api/search/route.ts": lines(
      `import { readStore } from "@/lib/db/store";`,
      `import { jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET(request: Request) {`,
      `  const url = new URL(request.url);`,
      `  const query = (url.searchParams.get("q") ?? "").trim().toLowerCase();`,
      `  const store = await readStore();`,
      `  const posts = store.posts.filter(`,
      `    (post) =>`,
      `      post.status === "published" &&`,
      `      (query.length === 0 ||`,
      `        post.title.toLowerCase().includes(query) ||`,
      `        post.body.toLowerCase().includes(query)),`,
      `  );`,
      `  const listings = store.listings.filter(`,
      `    (listing) =>`,
      `      listing.status === "active" &&`,
      `      (query.length === 0 ||`,
      `        listing.title.toLowerCase().includes(query) ||`,
      `        listing.description.toLowerCase().includes(query)),`,
      `  );`,
      `  const creators = store.users.filter(`,
      `    (user) =>`,
      `      user.role === "creator" &&`,
      `      (query.length === 0 || user.displayName.toLowerCase().includes(query)),`,
      `  );`,
      `  return jsonOk({ posts, listings, creators });`,
      `}`,
    ),
    "app/api/likes/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, mutateStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { postId?: string };`,
      `  if (!body.postId) return jsonError("postId required", 400);`,
      `  await mutateStore((store) => {`,
      `    const exists = store.likes.some((like) => like.userId === user.id && like.postId === body.postId);`,
      `    if (!exists) {`,
      `      store.likes.push({ id: createId("like"), userId: user.id, postId: body.postId!, createdAt: new Date().toISOString() });`,
      `    }`,
      `    return true;`,
      `  });`,
      `  trackEvent({ name: "post_liked", properties: { postId: body.postId, userId: user.id } });`,
      `  return jsonOk({ ok: true });`,
      `}`,
      ``,
      `export async function DELETE(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { postId?: string };`,
      `  if (!body.postId) return jsonError("postId required", 400);`,
      `  await mutateStore((store) => {`,
      `    store.likes = store.likes.filter((like) => !(like.userId === user.id && like.postId === body.postId));`,
      `    return true;`,
      `  });`,
      `  return jsonOk({ ok: true });`,
      `}`,
    ),
    "app/api/comments/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, mutateStore, readStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET(request: Request) {`,
      `  const url = new URL(request.url);`,
      `  const postId = url.searchParams.get("postId");`,
      `  if (!postId) return jsonError("postId required", 400);`,
      `  const store = await readStore();`,
      `  const comments = store.comments.filter((comment) => comment.postId === postId);`,
      `  return jsonOk({ comments });`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { postId?: string; body?: string };`,
      `  if (!body.postId || !body.body) return jsonError("postId and body required", 400);`,
      `  const comment = await mutateStore((store) => {`,
      `    const record = {`,
      `      id: createId("cmt"),`,
      `      userId: user.id,`,
      `      postId: body.postId!,`,
      `      body: body.body!,`,
      `      createdAt: new Date().toISOString(),`,
      `    };`,
      `    store.comments.push(record);`,
      `    return record;`,
      `  });`,
      `  trackEvent({ name: "comment_created", properties: { postId: body.postId, userId: user.id } });`,
      `  return jsonOk({ comment }, 201);`,
      `}`,
    ),
    "app/api/follow/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, findUserById, mutateStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { creatorId?: string };`,
      `  if (!body.creatorId) return jsonError("creatorId required", 400);`,
      `  await mutateStore((store) => {`,
      `    const creator = findUserById(store, body.creatorId!);`,
      `    if (!creator || creator.role !== "creator") throw new Error("Creator not found");`,
      `    if (creator.id === user.id) throw new Error("Cannot follow yourself");`,
      `    const exists = store.follows.some((follow) => follow.followerId === user.id && follow.creatorId === creator.id);`,
      `    if (!exists) {`,
      `      store.follows.push({ id: createId("fol"), followerId: user.id, creatorId: creator.id, createdAt: new Date().toISOString() });`,
      `    }`,
      `    return true;`,
      `  });`,
      `  trackEvent({ name: "creator_followed", properties: { creatorId: body.creatorId, followerId: user.id } });`,
      `  return jsonOk({ ok: true });`,
      `}`,
      ``,
      `export async function DELETE(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { creatorId?: string };`,
      `  if (!body.creatorId) return jsonError("creatorId required", 400);`,
      `  return jsonOk({ ok: true });`,
      `}`,
    ),
  };
}

function generateMarketplaceApiRoutes(): Record<string, string> {
  return {
    "app/api/listings/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, mutateStore, readStore } from "@/lib/db/store";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const store = await readStore();`,
      `  const listings = store.listings.filter((listing) => listing.status === "active");`,
      `  return jsonOk({ listings });`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  if (user.role !== "creator") return jsonError("Only creators can create listings", 403);`,
      `  const body = (await request.json()) as { title?: string; description?: string; priceCents?: number };`,
      `  if (!body.title || !body.description || typeof body.priceCents !== "number") {`,
      `    return jsonError("title, description, and priceCents required", 400);`,
      `  }`,
      `  const listing = await mutateStore((store) => {`,
      `    const now = new Date().toISOString();`,
      `    const record = {`,
      `      id: createId("lst"),`,
      `      creatorId: user.id,`,
      `      title: body.title!,`,
      `      description: body.description!,`,
      `      priceCents: Math.max(0, Math.round(body.priceCents!)),`,
      `      status: "active" as const,`,
      `      createdAt: now,`,
      `      updatedAt: now,`,
      `    };`,
      `    store.listings.unshift(record);`,
      `    return record;`,
      `  });`,
      `  return jsonOk({ listing }, 201);`,
      `}`,
    ),
    "app/api/listings/[id]/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { canUserEditListing, mutateStore, readStore } from "@/lib/db/store";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `type Params = { params: Promise<{ id: string }> };`,
      ``,
      `export async function GET(_request: Request, { params }: Params) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const listing = store.listings.find((item) => item.id === id);`,
      `  if (!listing || listing.status === "removed") return jsonError("Listing not found", 404);`,
      `  return jsonOk({ listing });`,
      `}`,
      ``,
      `export async function PUT(request: Request, { params }: Params) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const { id } = await params;`,
      `  const body = (await request.json()) as { title?: string; description?: string; priceCents?: number };`,
      `  try {`,
      `    const listing = await mutateStore((store) => {`,
      `      const existing = store.listings.find((item) => item.id === id);`,
      `      if (!existing) throw new Error("Listing not found");`,
      `      if (!canUserEditListing(user.id, existing)) throw new Error("Forbidden");`,
      `      if (body.title) existing.title = body.title;`,
      `      if (body.description) existing.description = body.description;`,
      `      if (typeof body.priceCents === "number") existing.priceCents = Math.max(0, Math.round(body.priceCents));`,
      `      existing.updatedAt = new Date().toISOString();`,
      `      return existing;`,
      `    });`,
      `    return jsonOk({ listing });`,
      `  } catch (error) {`,
      `    const message = error instanceof Error ? error.message : "Update failed";`,
      `    const status = message === "Forbidden" ? 403 : message === "Listing not found" ? 404 : 400;`,
      `    return jsonError(message, status);`,
      `  }`,
      `}`,
    ),
    "app/api/transactions/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { mutateStore, readStore } from "@/lib/db/store";`,
      `import { initiateTransaction } from "@/lib/marketplace/transactions";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const store = await readStore();`,
      `  const transactions = store.transactions.filter(`,
      `    (transaction) => transaction.buyerId === user.id || transaction.sellerId === user.id,`,
      `  );`,
      `  return jsonOk({ transactions });`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { listingId?: string };`,
      `  if (!body.listingId) return jsonError("listingId required", 400);`,
      `  try {`,
      `    const transaction = await mutateStore((store) => {`,
      `      const listing = store.listings.find((item) => item.id === body.listingId && item.status === "active");`,
      `      if (!listing) throw new Error("Listing not found");`,
      `      if (listing.creatorId === user.id) throw new Error("Cannot purchase your own listing");`,
      `      const record = initiateTransaction({`,
      `        listingId: listing.id,`,
      `        buyerId: user.id,`,
      `        sellerId: listing.creatorId,`,
      `        amountCents: listing.priceCents,`,
      `      });`,
      `      store.transactions.unshift(record);`,
      `      return record;`,
      `    });`,
      `    trackEvent({ name: "transaction_initiated", properties: { transactionId: transaction.id } });`,
      `    return jsonOk({ transaction }, 201);`,
      `  } catch (error) {`,
      `    return jsonError(error instanceof Error ? error.message : "Transaction failed", 400);`,
      `  }`,
      `}`,
    ),
    "app/api/transactions/[id]/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { mutateStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      `import { transitionTransaction, type TransactionStatus } from "@/lib/marketplace/transactions";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `type Params = { params: Promise<{ id: string }> };`,
      ``,
      `export async function PATCH(request: Request, { params }: Params) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const { id } = await params;`,
      `  const body = (await request.json()) as { status?: TransactionStatus };`,
      `  if (!body.status) return jsonError("status required", 400);`,
      `  try {`,
      `    const transaction = await mutateStore((store) => {`,
      `      const existing = store.transactions.find((item) => item.id === id);`,
      `      if (!existing) throw new Error("Transaction not found");`,
      `      const allowed = existing.buyerId === user.id || existing.sellerId === user.id || user.isModerator;`,
      `      if (!allowed) throw new Error("Forbidden");`,
      `      const next = transitionTransaction(existing, body.status!);`,
      `      const index = store.transactions.findIndex((item) => item.id === id);`,
      `      store.transactions[index] = next;`,
      `      return next;`,
      `    });`,
      `    trackEvent({ name: "revenue_event", properties: { transactionId: transaction.id, status: transaction.status } });`,
      `    return jsonOk({ transaction });`,
      `  } catch (error) {`,
      `    const message = error instanceof Error ? error.message : "Transition failed";`,
      `    const status = message === "Forbidden" ? 403 : message === "Transaction not found" ? 404 : 400;`,
      `    return jsonError(message, status);`,
      `  }`,
      `}`,
    ),
    "app/api/subscriptions/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { mutateStore, readStore } from "@/lib/db/store";`,
      `import { createPremiumSubscription, hasActiveSubscription, PREMIUM_PLAN_ID } from "@/lib/marketplace/entitlements";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const store = await readStore();`,
      `  const subscriptions = store.subscriptions.filter((subscription) => subscription.userId === user.id);`,
      `  return jsonOk({`,
      `    planId: PREMIUM_PLAN_ID,`,
      `    active: hasActiveSubscription(user.id, store.subscriptions),`,
      `    subscriptions,`,
      `  });`,
      `}`,
      ``,
      `export async function POST() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const subscription = await mutateStore((store) => {`,
      `    if (hasActiveSubscription(user.id, store.subscriptions)) throw new Error("Subscription already active");`,
      `    const record = createPremiumSubscription(user.id);`,
      `    store.subscriptions.unshift(record);`,
      `    return record;`,
      `  });`,
      `  return jsonOk({ subscription }, 201);`,
      `}`,
    ),
    "app/api/reports/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { createId, mutateStore, readStore } from "@/lib/db/store";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const store = await readStore();`,
      `  const reports = user.isModerator ? store.reports : store.reports.filter((report) => report.reporterId === user.id);`,
      `  return jsonOk({ reports });`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) return jsonError("Unauthorized", 401);`,
      `  const body = (await request.json()) as { targetType?: "post" | "listing" | "comment" | "user"; targetId?: string; reason?: string };`,
      `  if (!body.targetType || !body.targetId || !body.reason) return jsonError("targetType, targetId, and reason required", 400);`,
      `  const report = await mutateStore((store) => {`,
      `    const record = {`,
      `      id: createId("rpt"),`,
      `      reporterId: user.id,`,
      `      targetType: body.targetType!,`,
      `      targetId: body.targetId!,`,
      `      reason: body.reason!,`,
      `      status: "open" as const,`,
      `      createdAt: new Date().toISOString(),`,
      `    };`,
      `    store.reports.unshift(record);`,
      `    return record;`,
      `  });`,
      `  return jsonOk({ report }, 201);`,
      `}`,
    ),
    "app/api/moderation/route.ts": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { applyModerationAction, mutateStore, readStore } from "@/lib/db/store";`,
      `import { jsonError, jsonOk } from "@/lib/api/helpers";`,
      ``,
      `export async function GET() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user?.isModerator) return jsonError("Forbidden", 403);`,
      `  const store = await readStore();`,
      `  const queue = store.reports.filter((report) => report.status === "open");`,
      `  return jsonOk({ queue, actions: store.moderationActions.slice(0, 50) });`,
      `}`,
      ``,
      `export async function PATCH(request: Request) {`,
      `  const user = await getCurrentUser();`,
      `  if (!user?.isModerator) return jsonError("Forbidden", 403);`,
      `  const body = (await request.json()) as {`,
      `    targetType?: "post" | "listing" | "comment" | "user" | "report";`,
      `    targetId?: string;`,
      `    action?: "hide" | "remove" | "restore" | "dismiss" | "resolve";`,
      `    note?: string;`,
      `  };`,
      `  if (!body.targetType || !body.targetId || !body.action) {`,
      `    return jsonError("targetType, targetId, and action required", 400);`,
      `  }`,
      `  const moderationAction = await mutateStore((store) =>`,
      `    applyModerationAction(store, {`,
      `      moderatorId: user.id,`,
      `      targetType: body.targetType!,`,
      `      targetId: body.targetId!,`,
      `      action: body.action!,`,
      `      note: body.note ?? "",`,
      `    }),`,
      `  );`,
      `  return jsonOk({ moderationAction });`,
      `}`,
    ),
  };
}

function generateComponents(): Record<string, string> {
  return {
    "components/SiteNav.tsx": lines(
      `import Link from "next/link";`,
      `import { getCurrentUser } from "@/lib/auth/session";`,
      ``,
      `export async function SiteNav() {`,
      `  const user = await getCurrentUser();`,
      `  return (`,
      `    <nav className="site-nav">`,
      `      <Link href="/">Marketplace</Link>`,
      `      <Link href="/feed">Feed</Link>`,
      `      <Link href="/search">Search</Link>`,
      `      {user ? (`,
      `        <>`,
      `          <Link href="/dashboard/profile">Profile</Link>`,
      `          {user.isModerator ? <Link href="/admin/moderation">Moderation</Link> : null}`,
      `          <form action="/api/auth/logout" method="post">`,
      `            <button type="submit">Logout</button>`,
      `          </form>`,
      `        </>`,
      `      ) : (`,
      `        <>`,
      `          <Link href="/login">Login</Link>`,
      `          <Link href="/register">Register</Link>`,
      `        </>`,
      `      )}`,
      `    </nav>`,
      `  );`,
      `}`,
    ),
    "components/auth/AuthForm.tsx": lines(
      `"use client";`,
      ``,
      `import { useRouter } from "next/navigation";`,
      `import { useState } from "react";`,
      ``,
      `type AuthFormProps = { mode: "login" | "register" };`,
      ``,
      `export function AuthForm({ mode }: AuthFormProps) {`,
      `  const router = useRouter();`,
      `  const [email, setEmail] = useState("");`,
      `  const [password, setPassword] = useState("");`,
      `  const [displayName, setDisplayName] = useState("");`,
      `  const [role, setRole] = useState<"creator" | "consumer">("consumer");`,
      `  const [error, setError] = useState("");`,
      ``,
      `  async function onSubmit(event: React.FormEvent) {`,
      `    event.preventDefault();`,
      `    setError("");`,
      `    const endpoint = mode === "login" ? "/api/auth/login" : "/api/auth/register";`,
      `    const payload = mode === "login" ? { email, password } : { email, password, displayName, role };`,
      `    const response = await fetch(endpoint, {`,
      `      method: "POST",`,
      `      headers: { "Content-Type": "application/json" },`,
      `      body: JSON.stringify(payload),`,
      `    });`,
      `    const data = (await response.json()) as { error?: string };`,
      `    if (!response.ok) {`,
      `      setError(data.error ?? "Request failed");`,
      `      return;`,
      `    }`,
      `    router.push("/feed");`,
      `    router.refresh();`,
      `  }`,
      ``,
      `  return (`,
      `    <form onSubmit={onSubmit} className="auth-form">`,
      `      {mode === "register" ? (`,
      `        <>`,
      `          <label>`,
      `            Display name`,
      `            <input value={displayName} onChange={(event) => setDisplayName(event.target.value)} required />`,
      `          </label>`,
      `          <label>`,
      `            Role`,
      `            <select value={role} onChange={(event) => setRole(event.target.value as "creator" | "consumer")}>`,
      `              <option value="consumer">Consumer</option>`,
      `              <option value="creator">Creator</option>`,
      `            </select>`,
      `          </label>`,
      `        </>`,
      `      ) : null}`,
      `      <label>`,
      `        Email`,
      `        <input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required />`,
      `      </label>`,
      `      <label>`,
      `        Password`,
      `        <input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={8} />`,
      `      </label>`,
      `      {error ? <p className="error">{error}</p> : null}`,
      `      <button type="submit">{mode === "login" ? "Sign in" : "Create account"}</button>`,
      `    </form>`,
      `  );`,
      `}`,
    ),
    "components/marketplace/PurchaseButton.tsx": lines(
      `"use client";`,
      ``,
      `import { useRouter } from "next/navigation";`,
      `import { useState } from "react";`,
      ``,
      `export function PurchaseButton({ listingId }: { listingId: string }) {`,
      `  const router = useRouter();`,
      `  const [message, setMessage] = useState("");`,
      ``,
      `  async function purchase() {`,
      `    setMessage("");`,
      `    const response = await fetch("/api/transactions", {`,
      `      method: "POST",`,
      `      headers: { "Content-Type": "application/json" },`,
      `      body: JSON.stringify({ listingId }),`,
      `    });`,
      `    const data = (await response.json()) as { error?: string; transaction?: { id: string } };`,
      `    if (!response.ok) {`,
      `      setMessage(data.error ?? "Purchase failed");`,
      `      return;`,
      `    }`,
      `    setMessage(\`Sandbox transaction \${data.transaction?.id} created\`);`,
      `    router.refresh();`,
      `  }`,
      ``,
      `  return (`,
      `    <div>`,
      `      <button type="button" onClick={purchase}>Buy (sandbox)</button>`,
      `      {message ? <p>{message}</p> : null}`,
      `    </div>`,
      `  );`,
      `}`,
    ),
    "components/moderation/ModerationPanel.tsx": lines(
      `"use client";`,
      ``,
      `import { useRouter } from "next/navigation";`,
      `import { useState } from "react";`,
      ``,
      `type QueueItem = { id: string; targetType: string; targetId: string; reason: string };`,
      ``,
      `export function ModerationPanel({ queue }: { queue: QueueItem[] }) {`,
      `  const router = useRouter();`,
      `  const [status, setStatus] = useState("");`,
      ``,
      `  async function act(item: QueueItem, action: "hide" | "remove" | "dismiss" | "resolve") {`,
      `    setStatus("");`,
      `    const response = await fetch("/api/moderation", {`,
      `      method: "PATCH",`,
      `      headers: { "Content-Type": "application/json" },`,
      `      body: JSON.stringify({`,
      `        targetType: item.targetType === "post" ? "post" : "report",`,
      `        targetId: action === "dismiss" || action === "resolve" ? item.id : item.targetId,`,
      `        action,`,
      `        note: "Moderator action",`,
      `      }),`,
      `    });`,
      `    const data = (await response.json()) as { error?: string };`,
      `    if (!response.ok) {`,
      `      setStatus(data.error ?? "Action failed");`,
      `      return;`,
      `    }`,
      `    setStatus("Action applied");`,
      `    router.refresh();`,
      `  }`,
      ``,
      `  if (queue.length === 0) return <p>No open reports.</p>;`,
      ``,
      `  return (`,
      `    <div>`,
      `      {status ? <p>{status}</p> : null}`,
      `      <ul>`,
      `        {queue.map((item) => (`,
      `          <li key={item.id}>`,
      `            <strong>{item.targetType}</strong> {item.targetId} — {item.reason}`,
      `            <div>`,
      `              {item.targetType === "post" ? (`,
      `                <>`,
      `                  <button type="button" onClick={() => act(item, "hide")}>Hide</button>`,
      `                  <button type="button" onClick={() => act(item, "remove")}>Remove</button>`,
      `                </>`,
      `              ) : null}`,
      `              <button type="button" onClick={() => act(item, "dismiss")}>Dismiss</button>`,
      `              <button type="button" onClick={() => act(item, "resolve")}>Resolve</button>`,
      `            </div>`,
      `          </li>`,
      `        ))}`,
      `      </ul>`,
      `    </div>`,
      `  );`,
      `}`,
    ),
  };
}

function generatePages(): Record<string, string> {
  return {
    "app/globals.css": lines(
      `:root { color-scheme: light; font-family: system-ui, sans-serif; }`,
      `body { margin: 0; background: #f8fafc; color: #0f172a; }`,
      `.site-nav { display: flex; gap: 1rem; padding: 1rem 1.5rem; background: #0f172a; color: #fff; }`,
      `.site-nav a { color: #e2e8f0; text-decoration: none; }`,
      `.container { max-width: 960px; margin: 0 auto; padding: 1.5rem; }`,
      `.card { background: #fff; border: 1px solid #e2e8f0; border-radius: 0.75rem; padding: 1rem; margin-bottom: 1rem; }`,
      `.auth-form, form { display: grid; gap: 0.75rem; max-width: 420px; }`,
      `.error { color: #b91c1c; }`,
      `button { cursor: pointer; }`,
    ),
    "app/layout.tsx": lines(
      `import "./globals.css";`,
      `import type { Metadata } from "next";`,
      `import { SiteNav } from "@/components/SiteNav";`,
      `import seo from "@/content/seo-metadata.json";`,
      ``,
      `export const metadata: Metadata = {`,
      `  title: seo.title,`,
      `  description: seo.description,`,
      `};`,
      ``,
      `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
      `  return (`,
      `    <html lang="en">`,
      `      <body>`,
      `        <SiteNav />`,
      `        <div className="container">{children}</div>`,
      `      </body>`,
      `    </html>`,
      `  );`,
      `}`,
    ),
    "app/page.tsx": lines(
      `import Link from "next/link";`,
      `import seo from "@/content/seo-metadata.json";`,
      ``,
      `export default function LandingPage() {`,
      `  return (`,
      `    <main>`,
      `      <section className="card">`,
      `        <h1>{seo.title}</h1>`,
      `        <p>{seo.description}</p>`,
      `        <p>Discover creators, collect artwork, and support artists in a sandbox marketplace.</p>`,
      `        <div style={{ display: "flex", gap: "1rem" }}>`,
      `          <Link href="/feed">Browse feed</Link>`,
      `          <Link href="/register">Join as creator or collector</Link>`,
      `        </div>`,
      `      </section>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/feed/page.tsx": lines(
      `import Link from "next/link";`,
      `import { findUserById, readStore } from "@/lib/db/store";`,
      ``,
      `export default async function FeedPage() {`,
      `  const store = await readStore();`,
      `  const posts = store.posts.filter((post) => post.status === "published");`,
      `  return (`,
      `    <main>`,
      `      <h1>Community feed</h1>`,
      `      {posts.length === 0 ? <p className="card">No posts yet. Creators can publish from their dashboard.</p> : null}`,
      `      {posts.map((post) => {`,
      `        const creator = findUserById(store, post.creatorId);`,
      `        return (`,
      `          <article key={post.id} className="card">`,
      `            <h2><Link href={\`/post/\${post.id}\`}>{post.title}</Link></h2>`,
      `            <p>{post.body.slice(0, 180)}{post.body.length > 180 ? "..." : ""}</p>`,
      `            <p>By <Link href={\`/creator/\${post.creatorId}\`}>{creator?.displayName ?? "Creator"}</Link></p>`,
      `          </article>`,
      `        );`,
      `      })}`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/login/page.tsx": lines(
      `import Link from "next/link";`,
      `import { AuthForm } from "@/components/auth/AuthForm";`,
      ``,
      `export default function LoginPage() {`,
      `  return (`,
      `    <main>`,
      `      <h1>Sign in</h1>`,
      `      <AuthForm mode="login" />`,
      `      <p><Link href="/register">Create an account</Link></p>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/register/page.tsx": lines(
      `import Link from "next/link";`,
      `import { AuthForm } from "@/components/auth/AuthForm";`,
      ``,
      `export default function RegisterPage() {`,
      `  return (`,
      `    <main>`,
      `      <h1>Create account</h1>`,
      `      <AuthForm mode="register" />`,
      `      <p><Link href="/login">Already have an account?</Link></p>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/post/[id]/page.tsx": lines(
      `import Link from "next/link";`,
      `import { findUserById, readStore } from "@/lib/db/store";`,
      `import { trackEvent } from "@/lib/marketplace/analytics";`,
      ``,
      `type PageProps = { params: Promise<{ id: string }> };`,
      ``,
      `export default async function PostPage({ params }: PageProps) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const post = store.posts.find((item) => item.id === id && item.status !== "removed");`,
      `  if (!post) return <main><p>Post not found.</p></main>;`,
      `  trackEvent({ name: "post_viewed", properties: { postId: post.id } });`,
      `  const creator = findUserById(store, post.creatorId);`,
      `  const comments = store.comments.filter((comment) => comment.postId === post.id);`,
      `  const likes = store.likes.filter((like) => like.postId === post.id).length;`,
      `  return (`,
      `    <main>`,
      `      <article className="card">`,
      `        <h1>{post.title}</h1>`,
      `        <p>{post.body}</p>`,
      `        {post.mediaUrl ? <img src={post.mediaUrl} alt={post.title} style={{ maxWidth: "100%" }} /> : null}`,
      `        <p>By <Link href={\`/creator/\${post.creatorId}\`}>{creator?.displayName ?? "Creator"}</Link></p>`,
      `        <p>{likes} likes · {comments.length} comments</p>`,
      `      </article>`,
      `      <section className="card">`,
      `        <h2>Comments</h2>`,
      `        {comments.length === 0 ? <p>No comments yet.</p> : null}`,
      `        <ul>{comments.map((comment) => <li key={comment.id}>{comment.body}</li>)}</ul>`,
      `      </section>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/creator/[id]/page.tsx": lines(
      `import Link from "next/link";`,
      `import { findUserById, readStore } from "@/lib/db/store";`,
      ``,
      `type PageProps = { params: Promise<{ id: string }> };`,
      ``,
      `export default async function CreatorPage({ params }: PageProps) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const creator = findUserById(store, id);`,
      `  if (!creator || creator.role !== "creator") return <main><p>Creator not found.</p></main>;`,
      `  const profile = store.creatorProfiles.find((item) => item.userId === creator.id);`,
      `  const posts = store.posts.filter((post) => post.creatorId === creator.id && post.status === "published");`,
      `  const followers = store.follows.filter((follow) => follow.creatorId === creator.id).length;`,
      `  return (`,
      `    <main>`,
      `      <section className="card">`,
      `        <h1>{creator.displayName}</h1>`,
      `        <p>{profile?.headline ?? "Creator profile"}</p>`,
      `        <p>{profile?.bio ?? "No bio yet."}</p>`,
      `        <p>{followers} followers</p>`,
      `        <Link href={\`/creator/\${creator.id}/store\`}>Visit storefront</Link>`,
      `      </section>`,
      `      <section>`,
      `        <h2>Posts</h2>`,
      `        {posts.map((post) => (`,
      `          <article key={post.id} className="card">`,
      `            <h3><Link href={\`/post/\${post.id}\`}>{post.title}</Link></h3>`,
      `          </article>`,
      `        ))}`,
      `      </section>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/creator/[id]/store/page.tsx": lines(
      `import Link from "next/link";`,
      `import { findUserById, readStore } from "@/lib/db/store";`,
      ``,
      `type PageProps = { params: Promise<{ id: string }> };`,
      ``,
      `export default async function CreatorStorePage({ params }: PageProps) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const creator = findUserById(store, id);`,
      `  if (!creator || creator.role !== "creator") return <main><p>Store not found.</p></main>;`,
      `  const listings = store.listings.filter((listing) => listing.creatorId === creator.id && listing.status === "active");`,
      `  return (`,
      `    <main>`,
      `      <h1>{creator.displayName}&apos;s store</h1>`,
      `      {listings.length === 0 ? <p className="card">No active listings.</p> : null}`,
      `      {listings.map((listing) => (`,
      `        <article key={listing.id} className="card">`,
      `          <h2><Link href={\`/listing/\${listing.id}\`}>{listing.title}</Link></h2>`,
      `          <p>{listing.description}</p>`,
      `          <p>\${(listing.priceCents / 100).toFixed(2)}</p>`,
      `        </article>`,
      `      ))}`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/listing/[id]/page.tsx": lines(
      `import { findUserById, readStore } from "@/lib/db/store";`,
      `import { PurchaseButton } from "@/components/marketplace/PurchaseButton";`,
      ``,
      `type PageProps = { params: Promise<{ id: string }> };`,
      ``,
      `export default async function ListingPage({ params }: PageProps) {`,
      `  const { id } = await params;`,
      `  const store = await readStore();`,
      `  const listing = store.listings.find((item) => item.id === id && item.status === "active");`,
      `  if (!listing) return <main><p>Listing not found.</p></main>;`,
      `  const creator = findUserById(store, listing.creatorId);`,
      `  return (`,
      `    <main className="card">`,
      `      <h1>{listing.title}</h1>`,
      `      <p>{listing.description}</p>`,
      `      <p>Price: \${(listing.priceCents / 100).toFixed(2)} (sandbox)</p>`,
      `      <p>Seller: {creator?.displayName ?? "Creator"}</p>`,
      `      <PurchaseButton listingId={listing.id} />`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/search/page.tsx": lines(
      `import Link from "next/link";`,
      `import { readStore } from "@/lib/db/store";`,
      ``,
      `type PageProps = { searchParams: Promise<{ q?: string }> };`,
      ``,
      `export default async function SearchPage({ searchParams }: PageProps) {`,
      `  const { q = "" } = await searchParams;`,
      `  const query = q.trim().toLowerCase();`,
      `  const store = await readStore();`,
      `  const posts = store.posts.filter(`,
      `    (post) => post.status === "published" && (query.length === 0 || post.title.toLowerCase().includes(query)),`,
      `  );`,
      `  const listings = store.listings.filter(`,
      `    (listing) => listing.status === "active" && (query.length === 0 || listing.title.toLowerCase().includes(query)),`,
      `  );`,
      `  return (`,
      `    <main>`,
      `      <h1>Search</h1>`,
      `      <form method="get">`,
      `        <input name="q" defaultValue={q} placeholder="Search posts and listings" />`,
      `        <button type="submit">Search</button>`,
      `      </form>`,
      `      <section>`,
      `        <h2>Posts</h2>`,
      `        {posts.map((post) => (`,
      `          <article key={post.id} className="card">`,
      `            <Link href={\`/post/\${post.id}\`}>{post.title}</Link>`,
      `          </article>`,
      `        ))}`,
      `      </section>`,
      `      <section>`,
      `        <h2>Listings</h2>`,
      `        {listings.map((listing) => (`,
      `          <article key={listing.id} className="card">`,
      `            <Link href={\`/listing/\${listing.id}\`}>{listing.title}</Link>`,
      `          </article>`,
      `        ))}`,
      `      </section>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/dashboard/profile/page.tsx": lines(
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { hasActiveSubscription, PREMIUM_PLAN_ID } from "@/lib/marketplace/entitlements";`,
      `import { readStore } from "@/lib/db/store";`,
      `import { redirect } from "next/navigation";`,
      ``,
      `export default async function ProfileDashboardPage() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user) redirect("/login");`,
      `  const store = await readStore();`,
      `  const profile = store.creatorProfiles.find((item) => item.userId === user.id);`,
      `  const premium = hasActiveSubscription(user.id, store.subscriptions);`,
      `  return (`,
      `    <main>`,
      `      <h1>Your profile</h1>`,
      `      <section className="card">`,
      `        <p><strong>{user.displayName}</strong> ({user.role})</p>`,
      `        <p>{user.email}</p>`,
      `        {user.role === "creator" ? <p>{profile?.bio ?? "Add a bio from the API."}</p> : null}`,
      `        <p>Premium plan ({PREMIUM_PLAN_ID}): {premium ? "active" : "inactive"}</p>`,
      `        {!premium ? (`,
      `          <form action="/api/subscriptions" method="post">`,
      `            <button type="submit">Activate sandbox premium</button>`,
      `          </form>`,
      `        ) : null}`,
      `      </section>`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/admin/moderation/page.tsx": lines(
      `import { ModerationPanel } from "@/components/moderation/ModerationPanel";`,
      `import { getCurrentUser } from "@/lib/auth/session";`,
      `import { readStore } from "@/lib/db/store";`,
      `import { redirect } from "next/navigation";`,
      ``,
      `export default async function ModerationPage() {`,
      `  const user = await getCurrentUser();`,
      `  if (!user?.isModerator) redirect("/feed");`,
      `  const store = await readStore();`,
      `  const queue = store.reports.filter((report) => report.status === "open");`,
      `  return (`,
      `    <main>`,
      `      <h1>Moderation queue</h1>`,
      `      <ModerationPanel queue={queue} />`,
      `    </main>`,
      `  );`,
      `}`,
    ),
    "app/sitemap.ts": lines(
      `import type { MetadataRoute } from "next";`,
      `import seo from "@/content/seo-metadata.json";`,
      ``,
      `export default function sitemap(): MetadataRoute.Sitemap {`,
      `  const base = seo.siteUrl;`,
      `  return [`,
      `    { url: base, lastModified: new Date() },`,
      `    { url: \`\${base}/feed\`, lastModified: new Date() },`,
      `    { url: \`\${base}/search\`, lastModified: new Date() },`,
      `    { url: \`\${base}/login\`, lastModified: new Date() },`,
      `    { url: \`\${base}/register\`, lastModified: new Date() },`,
      `  ];`,
      `}`,
    ),
    "app/robots.ts": lines(
      `import type { MetadataRoute } from "next";`,
      `import seo from "@/content/seo-metadata.json";`,
      ``,
      `export default function robots(): MetadataRoute.Robots {`,
      `  return {`,
      `    rules: { userAgent: "*", allow: "/" },`,
      `    sitemap: \`\${seo.siteUrl}/sitemap.xml\`,`,
      `  };`,
      `}`,
    ),
  };
}

function generateTests(): Record<string, string> {
  return {
    "__tests__/marketplace/commission.test.ts": lines(
      `import { describe, expect, it } from "vitest";`,
      `import { calculateCommission } from "@/lib/marketplace/commission";`,
      ``,
      `describe("calculateCommission", () => {`,
      `  it("computes platform take and seller payout", () => {`,
      `    const result = calculateCommission(10000, 0.15);`,
      `    expect(result.commissionCents).toBe(1500);`,
      `    expect(result.sellerPayoutCents).toBe(8500);`,
      `  });`,
      ``,
      `  it("rejects invalid take rates", () => {`,
      `    expect(() => calculateCommission(1000, 1.5)).toThrow();`,
      `  });`,
      `});`,
    ),
    "__tests__/marketplace/auth-ownership.test.ts": lines(
      `import { describe, expect, it } from "vitest";`,
      `import { canUserEditPost, type Post } from "@/lib/db/store";`,
      ``,
      `const samplePost: Post = {`,
      `  id: "post_1",`,
      `  creatorId: "usr_creator",`,
      `  title: "Artwork",`,
      `  body: "Description",`,
      `  mediaUrl: "",`,
      `  status: "published",`,
      `  createdAt: new Date().toISOString(),`,
      `  updatedAt: new Date().toISOString(),`,
      `};`,
      ``,
      `describe("auth ownership", () => {`,
      `  it("allows creators to edit their own posts", () => {`,
      `    expect(canUserEditPost("usr_creator", samplePost)).toBe(true);`,
      `  });`,
      ``,
      `  it("denies edits from other users", () => {`,
      `    expect(canUserEditPost("usr_other", samplePost)).toBe(false);`,
      `  });`,
      `});`,
    ),
    "__tests__/marketplace/transaction.test.ts": lines(
      `import { describe, expect, it } from "vitest";`,
      `import { initiateTransaction, transitionTransaction, canTransition } from "@/lib/marketplace/transactions";`,
      ``,
      `describe("transaction state machine", () => {`,
      `  it("creates a pending sandbox transaction with commission", () => {`,
      `    const transaction = initiateTransaction({`,
      `      listingId: "lst_1",`,
      `      buyerId: "usr_buyer",`,
      `      sellerId: "usr_seller",`,
      `      amountCents: 2000,`,
      `    });`,
      `    expect(transaction.status).toBe("pending");`,
      `    expect(transaction.commissionCents).toBe(300);`,
      `    expect(transaction.sellerPayoutCents).toBe(1700);`,
      `  });`,
      ``,
      `  it("allows valid transitions only", () => {`,
      `    expect(canTransition("pending", "paid")).toBe(true);`,
      `    expect(canTransition("pending", "completed")).toBe(false);`,
      `    const transaction = initiateTransaction({`,
      `      listingId: "lst_1",`,
      `      buyerId: "usr_buyer",`,
      `      sellerId: "usr_seller",`,
      `      amountCents: 1000,`,
      `    });`,
      `    const paid = transitionTransaction(transaction, "paid");`,
      `    expect(paid.status).toBe("paid");`,
      `    expect(() => transitionTransaction(paid, "cancelled")).toThrow();`,
      `  });`,
      `});`,
    ),
    "__tests__/marketplace/moderation.test.ts": lines(
      `import { describe, expect, it } from "vitest";`,
      `import { applyModerationAction, emptyStore, type Post } from "@/lib/db/store";`,
      ``,
      `describe("moderation", () => {`,
      `  it("hides reported posts and resolves reports", () => {`,
      `    const store = emptyStore();`,
      `    const post: Post = {`,
      `      id: "post_1",`,
      `      creatorId: "usr_1",`,
      `      title: "Flagged",`,
      `      body: "Content",`,
      `      mediaUrl: "",`,
      `      status: "published",`,
      `      createdAt: new Date().toISOString(),`,
      `      updatedAt: new Date().toISOString(),`,
      `    };`,
      `    store.posts.push(post);`,
      `    store.reports.push({`,
      `      id: "rpt_1",`,
      `      reporterId: "usr_2",`,
      `      targetType: "post",`,
      `      targetId: post.id,`,
      `      reason: "Spam",`,
      `      status: "open",`,
      `      createdAt: new Date().toISOString(),`,
      `    });`,
      `    applyModerationAction(store, {`,
      `      moderatorId: "mod_1",`,
      `      targetType: "post",`,
      `      targetId: post.id,`,
      `      action: "hide",`,
      `      note: "Hidden after review",`,
      `    });`,
      `    expect(store.posts[0]?.status).toBe("hidden");`,
      `    applyModerationAction(store, {`,
      `      moderatorId: "mod_1",`,
      `      targetType: "report",`,
      `      targetId: "rpt_1",`,
      `      action: "resolve",`,
      `      note: "Reviewed",`,
      `    });`,
      `    expect(store.reports[0]?.status).toBe("resolved");`,
      `  });`,
      `});`,
    ),
  };
}

function generateSeoMetadata(): string {
  return `${JSON.stringify(
    {
      title: "Creator Marketplace",
      description: "Discover creators, collect artwork, and support artists in a sandbox marketplace.",
      siteUrl: "https://marketplace.local",
      ogType: "website",
    },
    null,
    2,
  )}\n`;
}

function generateInitialStore(): string {
  return `${JSON.stringify(
    {
      users: [],
      sessions: [],
      creatorProfiles: [],
      posts: [],
      likes: [],
      comments: [],
      follows: [],
      listings: [],
      transactions: [],
      subscriptions: [],
      reports: [],
      moderationActions: [],
    },
    null,
    2,
  )}\n`;
}

async function writeGeneratedFiles(
  sandbox: VentureSandbox,
  files: string[],
  entries: Record<string, string>,
): Promise<void> {
  for (const [relativePath, content] of Object.entries(entries)) {
    await writeScaffoldFile(sandbox, files, relativePath, content);
  }
}

export async function writeMarketplaceApplication(sandbox: VentureSandbox): Promise<string[]> {
  const files: string[] = [];

  await writeScaffoldFile(sandbox, files, "package.json", generatePackageJson());
  await writeScaffoldFile(sandbox, files, "next.config.mjs", generateNextConfig());
  await writeScaffoldFile(sandbox, files, "tsconfig.json", generateTsConfig());
  await writeScaffoldFile(sandbox, files, "vitest.config.mts", generateVitestConfig());
  await writeScaffoldFile(
    sandbox,
    files,
    "next-env.d.ts",
    lines(
      `/// <reference types="next" />`,
      `/// <reference types="next/image-types/global" />`,
    ),
  );
  await writeScaffoldFile(sandbox, files, "data/store.json", generateInitialStore());
  await writeScaffoldFile(sandbox, files, "content/seo-metadata.json", generateSeoMetadata());
  await writeScaffoldFile(sandbox, files, "lib/db/store.ts", generateStoreTs());
  await writeScaffoldFile(sandbox, files, "lib/auth/password.ts", generateAuthPasswordTs());
  await writeScaffoldFile(sandbox, files, "lib/auth/session.ts", generateAuthSessionTs());
  await writeScaffoldFile(sandbox, files, "lib/api/helpers.ts", generateApiHelpersTs());
  await writeScaffoldFile(sandbox, files, "lib/marketplace/commission.ts", generateCommissionTs());
  await writeScaffoldFile(sandbox, files, "lib/marketplace/transactions.ts", generateTransactionsTs());
  await writeScaffoldFile(sandbox, files, "lib/marketplace/analytics.ts", generateAnalyticsTs());
  await writeScaffoldFile(sandbox, files, "lib/marketplace/entitlements.ts", generateEntitlementsTs());
  await writeScaffoldFile(sandbox, files, "middleware.ts", generateMiddlewareTs());

  await writeGeneratedFiles(sandbox, files, generateAuthApiRoutes());
  await writeGeneratedFiles(sandbox, files, generateContentApiRoutes());
  await writeGeneratedFiles(sandbox, files, generateMarketplaceApiRoutes());
  await writeGeneratedFiles(sandbox, files, generateComponents());
  await writeGeneratedFiles(sandbox, files, generatePages());
  await writeGeneratedFiles(sandbox, files, generateTests());

  return files;
}
