import type { VentureTemplateType } from "../constants";

export type VentureBlueprintTemplate = {
  key: VentureTemplateType;
  displayName: string;
  version: string;
  defaultBusinessModel: string;
  defaultRevenueModel: string;
  marketingChannels: string[];
  requiredAssets: string[];
  requiredWorkers: string[];
  requiredContent: string[];
  requiredProducts: string[];
  requiredServices: string[];
  baseTimelineWeeks: number;
  baseBudgetUsd: number;
  baseRoiPercent: number;
};

export const VENTURE_BLUEPRINT_TEMPLATES: Record<VentureTemplateType, VentureBlueprintTemplate> = {
  saas: {
    key: "saas",
    displayName: "SaaS",
    version: "1.0.0",
    defaultBusinessModel: "subscription",
    defaultRevenueModel: "monthly_recurring_revenue",
    marketingChannels: ["content_marketing", "product_led_growth", "partnerships"],
    requiredAssets: ["product_spec", "pricing_page_spec", "onboarding_flow_spec"],
    requiredWorkers: ["blueprint.product_spec", "blueprint.pricing_model"],
    requiredContent: ["landing_page_copy", "feature_matrix", "faq"],
    requiredProducts: ["core_application_mvp"],
    requiredServices: ["customer_support_playbook"],
    baseTimelineWeeks: 16,
    baseBudgetUsd: 75000,
    baseRoiPercent: 120,
  },
  affiliate_site: {
    key: "affiliate_site",
    displayName: "Affiliate Site",
    version: "1.0.0",
    defaultBusinessModel: "affiliate",
    defaultRevenueModel: "affiliate_commissions",
    marketingChannels: ["seo", "email", "comparison_content"],
    requiredAssets: ["site_structure", "affiliate_disclosure_spec", "tracking_plan"],
    requiredWorkers: ["blueprint.content_plan", "blueprint.compliance_review"],
    requiredContent: ["comparison_articles", "review_templates", "disclosure_pages"],
    requiredProducts: [],
    requiredServices: ["affiliate_program_research"],
    baseTimelineWeeks: 10,
    baseBudgetUsd: 25000,
    baseRoiPercent: 90,
  },
  media_brand: {
    key: "media_brand",
    displayName: "Media Brand",
    version: "1.0.0",
    defaultBusinessModel: "media",
    defaultRevenueModel: "ads_and_sponsorships",
    marketingChannels: ["social", "newsletter", "podcast"],
    requiredAssets: ["brand_guidelines_spec", "editorial_calendar_spec"],
    requiredWorkers: ["blueprint.editorial_plan", "blueprint.brand_voice"],
    requiredContent: ["launch_editorial_pillars", "content_calendar"],
    requiredProducts: [],
    requiredServices: ["community_moderation_playbook"],
    baseTimelineWeeks: 12,
    baseBudgetUsd: 40000,
    baseRoiPercent: 85,
  },
  content_website: {
    key: "content_website",
    displayName: "Content Website",
    version: "1.0.0",
    defaultBusinessModel: "content",
    defaultRevenueModel: "ads_and_subscriptions",
    marketingChannels: ["seo", "newsletter"],
    requiredAssets: ["information_architecture_spec", "cms_requirements"],
    requiredWorkers: ["blueprint.content_plan", "blueprint.seo_brief"],
    requiredContent: ["pillar_pages", "topic_clusters"],
    requiredProducts: [],
    requiredServices: [],
    baseTimelineWeeks: 8,
    baseBudgetUsd: 20000,
    baseRoiPercent: 75,
  },
  lead_generation_website: {
    key: "lead_generation_website",
    displayName: "Lead Generation Website",
    version: "1.0.0",
    defaultBusinessModel: "lead_gen",
    defaultRevenueModel: "qualified_lead_sales",
    marketingChannels: ["paid_search", "landing_pages", "partnerships"],
    requiredAssets: ["funnel_spec", "lead_scoring_spec", "crm_integration_spec"],
    requiredWorkers: ["blueprint.funnel_design", "blueprint.compliance_review"],
    requiredContent: ["landing_pages", "lead_magnet_outline"],
    requiredProducts: [],
    requiredServices: ["lead_routing_playbook"],
    baseTimelineWeeks: 6,
    baseBudgetUsd: 30000,
    baseRoiPercent: 110,
  },
  local_service_business: {
    key: "local_service_business",
    displayName: "Local Service Business",
    version: "1.0.0",
    defaultBusinessModel: "services",
    defaultRevenueModel: "service_contracts",
    marketingChannels: ["local_seo", "referrals", "google_business_profile"],
    requiredAssets: ["service_menu_spec", "booking_flow_spec"],
    requiredWorkers: ["blueprint.operations_plan", "blueprint.local_marketing"],
    requiredContent: ["service_pages", "testimonial_framework"],
    requiredProducts: [],
    requiredServices: ["scheduling_and_dispatch_playbook"],
    baseTimelineWeeks: 8,
    baseBudgetUsd: 35000,
    baseRoiPercent: 95,
  },
  ecommerce: {
    key: "ecommerce",
    displayName: "E-commerce",
    version: "1.0.0",
    defaultBusinessModel: "ecommerce",
    defaultRevenueModel: "product_sales",
    marketingChannels: ["paid_social", "email", "marketplace_listings"],
    requiredAssets: ["catalog_spec", "checkout_flow_spec", "fulfillment_plan"],
    requiredWorkers: ["blueprint.catalog_plan", "blueprint.operations_plan"],
    requiredContent: ["product_descriptions", "policy_pages"],
    requiredProducts: ["sku_catalog_mvp"],
    requiredServices: ["fulfillment_vendor_evaluation"],
    baseTimelineWeeks: 14,
    baseBudgetUsd: 65000,
    baseRoiPercent: 100,
  },
  digital_product: {
    key: "digital_product",
    displayName: "Digital Product",
    version: "1.0.0",
    defaultBusinessModel: "digital_goods",
    defaultRevenueModel: "one_time_and_upsells",
    marketingChannels: ["email", "content", "affiliates"],
    requiredAssets: ["product_outline_spec", "delivery_platform_spec"],
    requiredWorkers: ["blueprint.product_design", "blueprint.launch_plan"],
    requiredContent: ["sales_page", "product_curriculum_or_assets_list"],
    requiredProducts: ["digital_deliverable_mvp"],
    requiredServices: ["customer_success_playbook"],
    baseTimelineWeeks: 10,
    baseBudgetUsd: 28000,
    baseRoiPercent: 130,
  },
  agency: {
    key: "agency",
    displayName: "Agency",
    version: "1.0.0",
    defaultBusinessModel: "agency",
    defaultRevenueModel: "retainer_and_projects",
    marketingChannels: ["outbound", "referrals", "case_studies"],
    requiredAssets: ["service_packages_spec", "delivery_methodology_spec"],
    requiredWorkers: ["blueprint.offer_design", "blueprint.sales_playbook"],
    requiredContent: ["case_study_templates", "proposal_templates"],
    requiredProducts: [],
    requiredServices: ["delivery_ops_playbook"],
    baseTimelineWeeks: 6,
    baseBudgetUsd: 22000,
    baseRoiPercent: 105,
  },
  marketplace: {
    key: "marketplace",
    displayName: "Marketplace",
    version: "1.0.0",
    defaultBusinessModel: "marketplace",
    defaultRevenueModel: "take_rate",
    marketingChannels: ["supply_acquisition", "demand_acquisition", "partnerships"],
    requiredAssets: ["two_sided_flow_spec", "trust_and_safety_spec", "payments_spec"],
    requiredWorkers: ["blueprint.marketplace_liquidity_plan", "blueprint.compliance_review"],
    requiredContent: ["supply_onboarding", "buyer_onboarding"],
    requiredProducts: ["marketplace_platform_mvp"],
    requiredServices: ["dispute_resolution_playbook"],
    baseTimelineWeeks: 20,
    baseBudgetUsd: 120000,
    baseRoiPercent: 140,
  },
  controlled_nextjs_website: {
    key: "controlled_nextjs_website",
    displayName: "Controlled Autonomous Next.js Website",
    version: "1.0.0",
    defaultBusinessModel: "internal_test",
    defaultRevenueModel: "none",
    marketingChannels: ["internal_validation"],
    requiredAssets: ["nextjs_app_shell"],
    requiredWorkers: ["blueprint.content_plan"],
    requiredContent: ["controlled_home_page"],
    requiredProducts: [],
    requiredServices: [],
    baseTimelineWeeks: 1,
    baseBudgetUsd: 0,
    baseRoiPercent: 0,
  },
};
