export const MISSION_ACTIVITY_MODEL = "MISSION_ACTIVITY_EVENT_V1" as const;

export const MISSION_ACTIVITY_EVENT_TYPES = [
  "MISSION_CREATED",
  "MISSION_STARTED",
  "MISSION_BLOCKED",
  "MISSION_WAITING",
  "MISSION_COMPLETED",
  "MISSION_FAILED",
  "STEP_QUEUED",
  "STEP_STARTED",
  "STEP_PROGRESS",
  "STEP_COMPLETED",
  "STEP_FAILED",
  "EXTERNAL_ACTION_STARTED",
  "EXTERNAL_ACTION_WAITING",
  "EXTERNAL_ACTION_COMPLETED",
  "EXTERNAL_ACTION_FAILED",
  "EVIDENCE_RECEIVED",
] as const;

export type MissionActivityEventType = (typeof MISSION_ACTIVITY_EVENT_TYPES)[number];

export const CANONICAL_ACTIVITY_STATUSES = [
  "QUEUED",
  "ACTIVE_WORK",
  "WAITING_INTERNAL",
  "WAITING_EXTERNAL",
  "READY_BLOCKED",
  "PRESENT_IDLE",
  "COMPLETED",
  "FAILED",
  "EMPTY",
] as const;

export type CanonicalActivityStatus = (typeof CANONICAL_ACTIVITY_STATUSES)[number];

export const ACTIVITY_EXECUTION_CLASSES = ["VENTURE_EXECUTION", "SYSTEM_DEVELOPMENT"] as const;
export type ActivityExecutionClass = (typeof ACTIVITY_EXECUTION_CLASSES)[number];

export const HQ_ACTIVITY_ROOMS = [
  "opportunity_lab",
  "research_department",
  "strategy_finance",
  "company_operations",
  "systems_architect",
  "growth_department",
  "creative_studio",
  "product_lab",
  "quality_control",
  "launch_operations",
  "intelligence_center",
  "executive_office",
] as const;

export type HqActivityRoomId = (typeof HQ_ACTIVITY_ROOMS)[number];

export const ACTIVITY_ROOM_LABELS: Record<HqActivityRoomId, string> = {
  opportunity_lab: "Venture Radar",
  research_department: "Research Grid",
  strategy_finance: "Profit Lab",
  company_operations: "Blueprint Lab",
  systems_architect: "Systems Architect",
  growth_department: "Growth Nexus",
  creative_studio: "Design Core",
  product_lab: "Creation Lab",
  quality_control: "Validation Station",
  launch_operations: "Deployment Depot",
  intelligence_center: "Signal Intelligence",
  executive_office: "Command",
};

export const ACTIVITY_ENGINE_ROOM: Record<string, HqActivityRoomId> = {
  opportunity_discovery: "opportunity_lab",
  opportunity_scanner: "opportunity_lab",
  grounded_research: "research_department",
  ai_brain: "research_department",
  multi_model_router: "research_department",
  monetization_engine: "strategy_finance",
  venture_selection: "strategy_finance",
  company_builder: "company_operations",
  venture_systems_architecture: "systems_architect",
  organic_growth: "growth_department",
  creative_media: "creative_studio",
  product_asset_builder: "product_lab",
  venture_build_orchestration: "product_lab",
  quality_control: "quality_control",
  market_validation: "quality_control",
  external_action_gateway: "launch_operations",
  hosting: "launch_operations",
  launch_gateway: "launch_operations",
  performance_intelligence: "intelligence_center",
  executive_decision: "executive_office",
  mission_runtime: "executive_office",
  command: "executive_office",
};

export const STEP_ROOM: Record<string, HqActivityRoomId> = {
  ORCHESTRATE_HOMEPAGE_HERO_LINK_CONTRAST_DEPLOY: "executive_office",
  ORCHESTRATE_SEMANTIC_NAV_WIDTH_MUTED_TEXT_DEPLOY: "executive_office",
  ORCHESTRATE_HOMEPAGE_HERO_AND_HQ_CORE_REPAIR: "executive_office",
  ORCHESTRATE_SEMANTIC_NAV_WIDTH_AND_MUTED_TEXT_REPAIR: "executive_office",
  REPRODUCE_HOMEPAGE_HERO_LINK_CONTRAST: "quality_control",
  HQ_DECISION_CORE: "product_lab",
  GENERATE_VALIDATION_ARTIFACT: "product_lab",
  GENERATE_LEGAL_ROUTES: "product_lab",
  ISOLATED_INSTALL: "product_lab",
  PRODUCTION_BUILD: "product_lab",
  PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
  PREPARE_SOURCE_BUNDLE: "launch_operations",
  UPLOAD_FILES: "launch_operations",
  CREATE_DEPLOYMENT: "launch_operations",
  PROVIDER_BUILD: "launch_operations",
  DEPLOYMENT_READY: "launch_operations",
  ACQUISITION_CHANNEL_ANALYSIS: "growth_department",
  PROSPECT_DISCOVERY: "research_department",
  PROSPECT_QUALIFICATION: "research_department",
  PROSPECT_GOVERNANCE: "quality_control",
  OUTREACH_PREPARATION: "growth_department",
  ORGANIC_VALIDATION_CONTENT: "growth_department",
  CREATIVE_ACQUISITION_ASSET: "creative_studio",
  EVIDENCE_MONITORING: "intelligence_center",
  MARKET_VALIDATION_ACQUISITION: "executive_office",
  RESEARCH_RETRY: "research_department",
  RESEARCH_TIMEOUT: "research_department",
  WEB_SEARCH: "research_department",
  PUBLIC_PAGE_FETCH: "research_department",
  EVIDENCE_EXTRACTION: "research_department",
  CONTACTABILITY_RESEARCH: "research_department",
  GOVERNANCE_PREPARATION: "executive_office",
  PUBLIC_INGEST_VALIDATION: "quality_control",
  EVIDENCE_CONTRACT_AUDIT: "quality_control",
  PERFORMANCE_HANDOFF: "intelligence_center",
  ORCHESTRATE_CRE_ACQUISITION_HANDOFF: "executive_office",
  ORCHESTRATE_CRE_COHORT_COMPLETION: "executive_office",
  ORCHESTRATE_COMMUNICATION_PROVIDER_FOUNDATION: "executive_office",
  COMMUNICATION_ARCHITECTURE: "systems_architect",
  ACQUISITION_REQUIREMENT_BIND: "growth_department",
  PROVIDER_CONNECTION_VERIFICATION: "quality_control",
  ORCHESTRATE_GMAIL_CONNECTION_READONLY: "executive_office",
  GMAIL_OAUTH_INTEGRATION: "systems_architect",
  GMAIL_IDENTITY_SCOPE_VERIFICATION: "quality_control",
  ORCHESTRATE_GMAIL_CONTROLLED_WRITE: "executive_office",
  GMAIL_CONTROLLED_WRITE_VERIFICATION: "quality_control",
  ORCHESTRATE_CRE_WAVE_1: "executive_office",
  CONTACT_REVERIFICATION: "quality_control",
  MESSAGE_STRATEGY: "growth_department",
  MESSAGE_QUALITY_VALIDATION: "quality_control",
  OUTREACH_AUTHORIZATION: "growth_department",
  PROVIDER_SEND: "growth_department",
  RESULT_PERSISTENCE: "quality_control",
  EXPERIMENT_READBACK: "quality_control",
  ORCHESTRATE_INBOUND_COMMUNICATION: "executive_office",
  INSPECT_INBOUND_SCOPES: "quality_control",
  PREPARE_TRACKED_CONVERSATIONS: "growth_department",
  INGEST_INBOUND_EVENTS: "growth_department",
  CLASSIFY_AND_POLICY: "quality_control",
  REPLY_PLANNING: "growth_department",
  HQ_INTELLIGENCE_PROJECTION: "intelligence_center",
  ORCHESTRATE_GMAIL_INBOUND_READ: "executive_office",
  OAUTH_REFRESH_AND_IDENTITY: "quality_control",
  SCOPE_GRANT_INSPECTION: "quality_control",
  PRESERVE_SEND_CAPABILITY: "quality_control",
  TRACKED_THREAD_READ: "intelligence_center",
  NARROW_SEARCH: "intelligence_center",
  HISTORY_CHECKPOINT: "intelligence_center",
  REPLY_INGEST_DRY: "quality_control",
  CLASSIFY_TRACKED_INBOUND: "growth_department",
  ORCHESTRATE_AUTONOMOUS_REPLY_WRITE: "executive_office",
  CONTROLLED_TARGET_GATE: "quality_control",
  PREPARE_VERIFICATION_CONVERSATION: "intelligence_center",
  SETUP_OR_REUSE_THREAD: "quality_control",
  INGEST_CONTROLLED_INBOUND: "intelligence_center",
  GROUNDED_REPLY_SEND: "growth_department",
  CAPABILITY_READBACK: "quality_control",
  ORCHESTRATE_CRE_INBOUND_OBSERVATION: "executive_office",
  ACTIVATE_OBSERVER: "quality_control",
  INITIALIZE_HISTORY_CHECKPOINT: "intelligence_center",
  TRACKED_THREAD_OBSERVATION: "intelligence_center",
  PROCESS_NEW_INBOUND: "growth_department",
  OBSERVER_HEALTH_READBACK: "quality_control",
  ORCHESTRATE_INBOUND_PROCESSING: "executive_office",
  INGEST_TRACKED_INBOUND: "intelligence_center",
  MARKET_DESIGN_CONTEXT: "research_department",
  DESIGN_INTELLIGENCE: "systems_architect",
  COMPOSITION_PLAN: "systems_architect",
  CREATIVE_ASSET_PLAN: "creative_studio",
  GENERATE_PREMIUM_ARTIFACT: "product_lab",
  PREMIUM_QUALITY_GATE: "quality_control",
  RESEARCH_SITE_OPPORTUNITY: "research_department",
  PLAN_TOPIC_ARCHITECTURE: "research_department",
  PLAN_SITE_ARCHITECTURE: "systems_architect",
  PLAN_INTERNAL_LINK_GRAPH: "systems_architect",
  PLAN_DESIGN: "systems_architect",
  PLAN_CREATIVE_ASSETS: "creative_studio",
  GENERATE_CONTENT: "product_lab",
  GENERATE_VISUALS: "creative_studio",
  ASSEMBLE_PAGES: "product_lab",
  GENERATE_SCHEMA: "systems_architect",
  GENERATE_SITEMAP: "product_lab",
  VALIDATE_CONTENT: "quality_control",
  VALIDATE_GEO_SEO: "quality_control",
  VALIDATE_DESIGN: "quality_control",
  VALIDATE_TECHNICAL: "quality_control",
  PACKAGE_ARTIFACT: "product_lab",
  PREMIUM_AUTHORITY_QUALITY_GATE: "quality_control",
  SITE_EXPANSION_PLAN: "intelligence_center",
  ORCHESTRATE_QUESTION_AUTHORITY_QC: "executive_office",
  DISCOVER_QUESTION_UNIVERSE: "research_department",
  RESEARCH_QUESTION_CLUSTER: "research_department",
  PLAN_URL_ARCHITECTURE: "systems_architect",
  VALIDATE_CONTENT_DEPTH: "quality_control",
  VALIDATE_ANSWER_AUTHORITY: "quality_control",
  ADVERSARIAL_PUBLISHABILITY_REVIEW: "quality_control",
  PUBLISHABILITY_REVIEW: "quality_control",
  AUTHORITY_REPAIR_PLAN: "quality_control",
  ORCHESTRATE_HQ_LIVE_WORKER_PROOF: "executive_office",
  ORCHESTRATE_HQ_CROSS_PROCESS_PROOF: "executive_office",
  ORCHESTRATE_HQ_CURRENT_EXECUTION_PROOF: "executive_office",
  DEPLOYMENT_RECONCILIATION_SIMULATION_READ_ONLY: "launch_operations",
  VALIDATION_REVIEW: "quality_control",
  ORCHESTRATE_DR_SUCCESSOR_DEPLOY: "executive_office",
  ORCHESTRATE_FINAL_REPAIR_SUCCESSOR_DEPLOY: "executive_office",
  ORCHESTRATE_COMPILE_REPAIR_SUCCESSOR_DEPLOY: "executive_office",
  ORCHESTRATE_VISUAL_SUCCESSOR_DEPLOY: "executive_office",
  ORCHESTRATE_SUCCESSOR_BUILD: "executive_office",
  QUESTION_RESEARCH: "research_department",
  SOURCE_RESEARCH: "research_department",
  SITE_ARCHITECTURE: "systems_architect",
  URL_ARCHITECTURE: "systems_architect",
  CONTENT_ARCHITECTURE: "systems_architect",
  DIRECT_RESPONSE_PLANNING: "systems_architect",
  VISUAL_PLANNING: "creative_studio",
  PAGE_GENERATION: "product_lab",
  QUESTION_MAPPING: "systems_architect",
  INTERNAL_LINKING: "systems_architect",
  METADATA_SCHEMA: "systems_architect",
  QUALITY_REVIEW: "quality_control",
  ADVERSARIAL_REVIEW: "quality_control",
  TARGETED_REPAIR: "quality_control",
  FINAL_ARTIFACT_VALIDATION: "quality_control",
  ORCHESTRATE_MISSION: "executive_office",
  RENDERED_LAYOUT_AUDIT: "creative_studio",
  RESPONSIVE_GEOMETRY_AUDIT: "quality_control",
  DESIGN_SYSTEM_REPAIR: "systems_architect",
  COMPOSITION_REPAIR: "creative_studio",
  ARTIFACT_GENERATION: "product_lab",
  RENDERED_LAYOUT_VALIDATION: "quality_control",
  ADVERSARIAL_VISUAL_REVIEW: "quality_control",
  LINEAGE_INSTRUMENTATION_AUDIT: "systems_architect",
  RENDERED_OUTPUT_VERIFICATION: "quality_control",
  SERVED_PRODUCTION_LAYOUT_GATE: "quality_control",
  ORCHESTRATE_SERVED_PRODUCTION_LAYOUT_PARITY: "executive_office",
  ORCHESTRATE_DEPLOYED_SUCCESSOR_READJUDICATION: "executive_office",
  ORCHESTRATE_COMPILE_REPAIR_SUCCESSOR_ACTIVATE: "executive_office",
  ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
  ORCHESTRATE_FULL_PAGE_AUTOREPAIR: "executive_office",
  ORCHESTRATE_FULL_PAGE_AUTOREPAIR_DEPLOY: "executive_office",
  ORCHESTRATE_PRICING_PRERENDER_REPAIR: "executive_office",
  REPRODUCE_PRICING_PRERENDER: "quality_control",
  PAGE_COMPOSE: "product_lab",
  PAGE_RENDER: "quality_control",
  PAGE_VALIDATE: "quality_control",
  PAGE_REPAIR_LOOP: "quality_control",
  PAGE_PASS: "quality_control",
  PAGE_ADMISSION: "quality_control",
  SITE_GRAPH_VALIDATION: "systems_architect",
  FULL_ROUTE_FROZEN_ARTIFACT_VALIDATION: "quality_control",
  REPEATED_FAILURE_PROMOTION: "systems_architect",
  RENDERED_LINK_CONTRAST: "quality_control",
  PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
  ORCHESTRATE_SITE_CHROME_LINK_CONTRAST_REPAIR: "executive_office",
  REPRODUCE_SITE_CHROME_LINK_CONTRAST: "quality_control",
  ORCHESTRATE_FOUNDER_FULL_SITE_VISUAL_ACCEPTANCE: "executive_office",
  RECORD_FOUNDER_ACCEPTANCE: "quality_control",
  UNLOCK_NEXT_MILESTONE: "executive_office",
  ORCHESTRATE_CONTEXT_RICH_OUTREACH_OPTIMIZATION: "executive_office",
  ORCHESTRATE_GOVERNED_CONTEXT_RICH_OUTREACH: "executive_office",
  ORCHESTRATE_CHALLENGER_OUTCOME_OBSERVATION: "executive_office",
  OUTCOME_EVALUATION: "intelligence_center",
  INGEST_CHALLENGER_INBOUND: "growth_department",
  RESEARCH_PERSONA_EVIDENCE: "research_department",
  OUTREACH_MESSAGE_STRATEGY: "growth_department",
  COMMUNICATION_POLICY_ARCHITECTURE: "systems_architect",
  PROSPECT_ELIGIBILITY_VALIDATION: "quality_control",
  ORCHESTRATE_VENTURE_OPERATING_SCALE: "executive_office",
  RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
  BACKFILL_CRE_OPERATING_RECORD: "quality_control",
  BUILD_DAILY_OPERATING_CYCLE: "intelligence_center",
  BUILD_PORTFOLIO_OPERATING_CYCLE: "intelligence_center",
  BUILD_DOMAIN_PAYMENT_FOUNDATION: "growth_department",
  EVALUATE_COMMERCIALIZATION_READINESS: "quality_control",
  ORCHESTRATE_PARALLEL_CRE_COMMERCIALIZATION: "executive_office",
  EVALUATE_MISSION_CONCURRENCY: "executive_office",
  RESEARCH_VENTURE_NAMING: "research_department",
  VERIFY_DOMAIN_PROVIDERS: "quality_control",
  GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
  VERIFY_STRIPE_CONNECTION: "quality_control",
  BUILD_PAYMENT_CONFIGURATION_PLAN: "systems_architect",
  EVALUATE_PAYMENT_READINESS: "quality_control",
  RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
  ORCHESTRATE_DOMAIN_PROVIDER_AND_STRIPE_CONFIGURATION: "executive_office",
  VERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
  RECONCILE_STRIPE_OBJECTS: "quality_control",
  CONFIGURE_STRIPE_PRODUCTS: "systems_architect",
  RECONCILE_LEGAL_SURFACES: "quality_control",
  ORCHESTRATE_CRE_COMMERCIAL_PROVIDER_ACCESS_REPAIR: "executive_office",
  CLASSIFY_PROVIDER_BLOCKS: "systems_architect",
  INSPECT_NAMECHEAP_SAFE_CONFIG: "research_department",
  REVERIFY_NAMECHEAP_DOMAIN_READS: "quality_control",
  INSPECT_STRIPE_KEY_CAPABILITIES: "quality_control",
  REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
  LOOKUP_EXISTING_STRIPE_OBJECTS: "quality_control",
  SEARCH_CANONICAL_LEGAL_FACTS: "research_department",
  ORCHESTRATE_CRE_STRIPE_REVERIFICATION_AND_COMMERCIAL_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_STRIPE_ACCOUNT_REVERIFICATION_AND_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_CLOUDFLARE_REGISTRAR_LIVE_VERIFICATION: "executive_office",
  RELOAD_CLOUDFLARE_RUNTIME_ENV: "systems_architect",
  VERIFY_CLOUDFLARE_ACCOUNT: "quality_control",
  VERIFY_REGISTRAR_API: "quality_control",
  CHECK_DOMAIN_AVAILABILITY: "research_department",
  RANK_DOMAIN_CANDIDATES: "research_department",
  ROUTE_DOMAIN_PROVIDER: "systems_architect",
  RELOAD_STRIPE_RUNTIME_ENV: "systems_architect",
  VERIFY_STRIPE_READ_CAPABILITIES: "quality_control",
  GOVERN_STRIPE_WRITE_GATES: "strategy_finance",
  PROVIDER_READBACK: "quality_control",
  IDEMPOTENT_RECONCILIATION: "quality_control",
  ORCHESTRATE_CRE_OCCUPANCYNPV_LEGAL_STRIPE_AUDIT: "executive_office",
  ORCHESTRATE_CRE_OCCUPANCYNPV_LEGAL_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_PRODUCT_PRICE_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_OCCUPANCYNPV_CHECKOUT_WEBHOOK_ANALYTICS_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_CONFIGURATION: "executive_office",
  ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_WRITE_RETRY: "executive_office",
  ORCHESTRATE_DURABLE_COMMERCIAL_PROVIDER_MUTATION_AUTHORITY: "executive_office",
  ORCHESTRATE_OCCUPANCYNPV_FIRST_PAYMENT_ACTIVATION: "executive_office",
  ORCHESTRATE_OCCUPANCYNPV_PAYMENT_SAFETY_ROLLBACK: "executive_office",
  ORCHESTRATE_OCCUPANCYNPV_FULFILLMENT_ARCHITECTURE: "executive_office",
  LOCK_GLOBAL_FULFILLMENT_PRINCIPLES: "strategy_finance",
  DISCOVER_OCCUPANCYNPV_PRODUCT_TRUTH: "quality_control",
  DEFINE_VENTURE_FULFILLMENT_CONTRACTS: "strategy_finance",
  IMPLEMENT_ENTITLEMENT_LIFECYCLE: "systems_architect",
  UPGRADE_SERVER_SIDE_FULFILLMENT_GATE: "quality_control",
  EVALUATE_READINESS_GATES: "strategy_finance",
  AUDIT_POST_ACTIVATION_TRANSACTIONS: "quality_control",
  DISABLE_CUSTOMER_PAYMENT_INITIATION: "strategy_finance",
  PRESERVE_PAYMENT_INFRASTRUCTURE: "quality_control",
  ADD_FULFILLMENT_READINESS_DEPENDENCY: "strategy_finance",
  REVERIFY_CANONICAL_PAYMENT_OBJECTS: "strategy_finance",
  REVERIFY_CANONICAL_WEBHOOK: "quality_control",
  REVERIFY_CHECKOUT_SAFETY: "quality_control",
  EVALUATE_ACTIVATION_GATES: "strategy_finance",
  ACTIVATE_PAYMENT_PATH: "strategy_finance",
  VERIFY_PURCHASE_SURFACE: "launch_operations",
  PRESERVE_PUBLIC_LAUNCH_FIREWALL: "quality_control",
  DEFINE_MUTATION_TAXONOMY: "strategy_finance",
  EVALUATE_DEFAULT_AUTONOMY_MATRIX: "strategy_finance",
  INSTANTIATE_OCCUPANCYNPV_MUTATION_POLICY: "strategy_finance",
  DEFINE_PAYMENT_ACTIVATION_POLICY: "strategy_finance",
  PRESERVE_PAYMENT_AND_LAUNCH_BLOCKERS: "quality_control",
  PROJECT_HQ_AUTHORITY_VISIBILITY: "intelligence_center",
  VERIFY_WEBHOOK_WRITE_CAPABILITY: "quality_control",
  RECONCILE_EXISTING_STRIPE_WEBHOOKS: "quality_control",
  CREATE_OR_RECONCILE_CANONICAL_WEBHOOK: "strategy_finance",
  PERSIST_WEBHOOK_SIGNING_SECRET: "systems_architect",
  READBACK_CANONICAL_WEBHOOK: "quality_control",
  VERIFY_APPLICATION_AND_LINEAGE: "intelligence_center",
  RECORD_AUTONOMY_POLICY_GAP: "strategy_finance",
  CONFIGURE_CHECKOUT_ARCHITECTURE: "strategy_finance",
  CONFIGURE_CHECKOUT_SESSION_BOUNDARY: "strategy_finance",
  CONFIGURE_SUCCESS_CANCEL_ROUTES: "product_lab",
  CONFIGURE_WEBHOOK_APPLICATION: "systems_architect",
  RECONCILE_STRIPE_WEBHOOK_ENDPOINTS: "quality_control",
  CONFIGURE_ANALYTICS_AND_REVENUE_LINEAGE: "intelligence_center",
  AUDIT_PRIVACY_AND_PUBLIC_CHECKOUT_EXPOSURE: "quality_control",
  RECONCILE_EXISTING_STRIPE_OBJECTS: "strategy_finance",
  EVALUATE_WRITE_GOVERNANCE: "strategy_finance",
  CREATE_CANONICAL_STRIPE_PRODUCTS: "strategy_finance",
  CREATE_CANONICAL_STRIPE_PRICES: "strategy_finance",
  READBACK_CANONICAL_STRIPE_OBJECTS: "quality_control",
  PERSIST_PAYMENT_BINDINGS: "quality_control",
  RECONCILE_INFRASTRUCTURE_STATE: "launch_operations",
  AUDIT_LEGAL_FACTS_AND_SURFACES: "quality_control",
  VERIFY_STRIPE_ACCOUNT_AND_CAPABILITIES: "quality_control",
  RECONCILE_CANONICAL_OFFERS: "strategy_finance",
  PLAN_CHECKOUT_WEBHOOK_AND_ANALYTICS: "quality_control",
  PERSIST_CANONICAL_LEGAL_FACTS: "quality_control",
  COMPOSE_LEGAL_SURFACE_SUCCESSOR: "product_lab",
  PUBLISH_LEGAL_SURFACES: "launch_operations",
  VALIDATE_LEGAL_SURFACES: "quality_control",
  VALIDATE_PRODUCTION_HOST_AND_ROUTES: "quality_control",
  EVALUATE_LEGAL_CONFIGURATION_GATE: "quality_control",
};

export const AUTHORIZATION_BLOCKERS = [
  "FOUNDER_AUTHORIZATION_REQUIRED",
  "PUBLIC_ARTIFACT_DEPLOYMENT_REQUIRED",
  "FOUNDER_PROSPECT_INPUT_REQUIRED",
  "EXTERNAL_VALIDATION_REQUIRED",
  "PROVIDER_CAPABILITY_UNVERIFIED",
  "UNKNOWN_COST_AUTHORIZATION_REQUIRED",
  "FOUNDER_COMMUNICATIONS_AUTHORIZATION_REQUIRED",
  "LIVE_PROSPECT_DISCOVERY_CAPABILITY_REQUIRED",
  "RESEARCH_EXECUTION_RETRY_REQUIRED",
  "RESEARCH_CAPABILITY_UNAVAILABLE",
  "RESEARCH_PROVIDER_UNAVAILABLE",
  "RESEARCH_CAPABILITY_TEMPORARILY_UNAVAILABLE",
  "NO_QUALIFIED_PUBLIC_PROSPECTS_FOUND",
  "PUBLIC_WEB_SEARCH_PROVIDER_CONFIGURATION_REQUIRED",
  "COMMUNICATION_PROVIDER_CAPABILITY_REQUIRED",
  "GMAIL_PROVIDER_CONNECTION_REQUIRED",
  "FOUNDER_GOOGLE_OAUTH_CONFIGURATION_REQUIRED",
  "CONTROLLED_WRITE_TARGET_REQUIRED",
  "CONTROLLED_WRITE_VERIFICATION_REQUIRED",
  "CONTROLLED_WRITE_VERIFICATION_FAILED",
  "COMMUNICATION_PROVIDER_CONNECTION_FAILED",
  "GMAIL_READ_ONLY_VERIFICATION_FAILED",
  "READY_FOR_BOUNDED_CRE_OUTREACH_AUTHORIZATION",
  "COMMUNICATION_PROVIDER_ARCHITECTURE_INCOMPLETE",
  "REAL_PROSPECT_COHORT_NOT_READY",
  "ACQUISITION_PREPARATION_INCOMPLETE",
  "CREATIVE_MEDIA_CAPABILITY_REQUIRED",
  "NEW_FOUNDER_PREMIUM_SUCCESSOR_DEPLOYMENT_AUTHORIZATION_REQUIRED",
  "NEW_FOUNDER_PREMIUM_AUTHORITY_SITE_DEPLOYMENT_AUTHORIZATION_REQUIRED",
  "GOVERNED_CRE_CONTEXT_RICH_OUTREACH_EXECUTION_REQUIRED",
  "CRE_CONTEXT_RICH_CHALLENGER_OUTCOME_OBSERVATION_REQUIRED",
  "CRE_CONTEXT_RICH_CHALLENGER_ADDITIONAL_OBSERVATION_REQUIRED",
  "CRE_VALIDATION_WAVE_2_DECISION_REQUIRED",
  "VENTURE_SCALE_AND_COMMERCIALIZATION_FOUNDATION_REQUIRED",
  "DOMAIN_ACQUISITION_AUTHORIZATION_REQUIRED",
  "DNS_CONFIGURATION_AUTHORIZATION_REQUIRED",
  "PRODUCTION_DOMAIN_BINDING_AUTHORIZATION_REQUIRED",
  "PAYMENT_CONFIGURATION_AUTHORIZATION_REQUIRED",
  "PAYMENT_ACTIVATION_AUTHORIZATION_REQUIRED",
  "PUBLIC_LAUNCH_AUTHORIZATION_REQUIRED",
  "DOMAIN_PURCHASE_FINANCIAL_AUTHORIZATION_REQUIRED",
  "GOVERNED_CRE_DNS_CONFIGURATION_REQUIRED",
  "GOVERNED_CRE_PAYMENT_CONFIGURATION_REQUIRED",
  "STRIPE_ACCOUNT_IDENTITY_UNVERIFIED",
  "REGISTRATION_WRITE_AUTHORITY_UNVERIFIED",
  "NAMECHEAP_ACCOUNT_ACTION_REQUIRED",
  "STRIPE_ACCOUNT_ACTION_REQUIRED",
  "FOUNDER_LEGAL_CONFIGURATION_REQUIRED",
  "GOVERNED_CRE_CHECKOUT_CONFIGURATION_REQUIRED",
  "GOVERNED_CANONICAL_STRIPE_PRODUCT_PRICE_AUTHORIZATION",
  "CHECKOUT_WEBHOOK_AND_ANALYTICS_CONFIGURATION",
  "GOVERNED_STRIPE_WEBHOOK_CONFIGURATION_AUTHORIZATION",
  "DURABLE_COMMERCIAL_PROVIDER_MUTATION_AUTHORITY_REQUIRED",
  "OCCUPANCYNPV_FIRST_PAYMENT_ACTIVATION_AUTHORIZATION",
  "VENTURE_SPECIFIC_COMMERCIAL_FULFILLMENT_ARCHITECTURE_V1",
] as const;

export const CURSOR_IS_NOT_AN_INFINITY_WORKER =
  "Cursor file editing is developer implementation work, not Infinity venture execution." as const;
