import type { HqActivityRoomId } from "./constants";

export type RuntimeWrapperAdoption = "USES_CANONICAL_MISSION_WRAPPER" | "PARTIAL" | "NOT_INTEGRATED";

export type CanonicalRuntimeMissionContract = {
  runtime: string;
  missionType: string | null;
  defaultRoom: HqActivityRoomId;
  stepToRoom: Partial<Record<string, HqActivityRoomId>>;
  usesCanonicalMissionWrapper: boolean;
  usesCanonicalStepWrapper: boolean;
  adoption: RuntimeWrapperAdoption;
  authorizationSemantics: "MISSION_BLOCKED" | "MISSION_WAITING" | "NONE";
  lineage: {
    ventureId: boolean;
    candidateId: boolean;
    artifactId: boolean;
    experimentId: boolean;
  };
};

export const CANONICAL_MISSION_WRAPPER = "runInstrumentedMission" as const;
export const CANONICAL_STEP_WRAPPER = "runInstrumentedStep" as const;
export const CANONICAL_ACTIVITY_SCHEMA = "MISSION_ACTIVITY_EVENT_V1" as const;

export function instrumentedRuntimeRegistry(): {
  wrapper: typeof CANONICAL_MISSION_WRAPPER;
  stepWrapper: typeof CANONICAL_STEP_WRAPPER;
  schema: typeof CANONICAL_ACTIVITY_SCHEMA;
  anotherTelemetryModel: false;
  contracts: Record<string, CanonicalRuntimeMissionContract>;
  runtimes: Record<string, {
    runtime: string;
    usesStepWrapper: boolean;
    usesMissionWrapper: boolean;
    adoption: RuntimeWrapperAdoption;
    futureUsesMissionWrapper?: boolean;
    consumedByQuestionDiscovery?: boolean;
    futureSiteRepairUsesMissionWrapper?: boolean;
  }>;
} {
  return {
    wrapper: CANONICAL_MISSION_WRAPPER,
    stepWrapper: CANONICAL_STEP_WRAPPER,
    schema: CANONICAL_ACTIVITY_SCHEMA,
    anotherTelemetryModel: false,
    contracts: {
      CreHubQuestionBoardLayoutRepairRuntime: {
        runtime: "CRE_HUB_QUESTION_BOARD_LAYOUT_REPAIR_V1",
        missionType: "CRE_HUB_QUESTION_BOARD_LAYOUT_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_HUB_LAYOUT_REPAIR: "executive_office",
          REPRODUCE_FOUNDER_LEFTOVER: "quality_control",
          SITE_ARCHITECTURE: "systems_architect",
          ARTIFACT_GENERATION: "product_lab",
          VALIDATE_TECHNICAL: "quality_control",
          QUALITY_REVIEW: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CrePricingPrerenderRepairRuntime: {
        runtime: "CRE_PROVIDER_EQUIVALENT_PRICING_BUILD_REPAIR_V1",
        missionType: "CRE_PROVIDER_EQUIVALENT_PRICING_BUILD_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_PRICING_PRERENDER_REPAIR: "executive_office",
          REPRODUCE_PRICING_PRERENDER: "quality_control",
          SITE_ARCHITECTURE: "systems_architect",
          ARTIFACT_GENERATION: "product_lab",
          VALIDATE_TECHNICAL: "quality_control",
          QUALITY_REVIEW: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreFullPageAutorepairDeployRuntime: {
        runtime: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V1",
        missionType: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_FULL_PAGE_AUTOREPAIR_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreSemanticNavWidthUtilizationRepairRuntime: {
        runtime: "CRE_SEMANTIC_NAV_WIDTH_UTILIZATION_REPAIR_V1",
        missionType: "CRE_SEMANTIC_NAV_WIDTH_UTILIZATION_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_SEMANTIC_NAV_WIDTH_AND_MUTED_TEXT_REPAIR: "executive_office",
          QUALITY_REVIEW: "quality_control",
          SITE_ARCHITECTURE: "systems_architect",
          ARTIFACT_GENERATION: "product_lab",
          VALIDATE_TECHNICAL: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreHomepageHeroLinkAndHqInfinityCoreRepairRuntime: {
        runtime: "CRE_HOMEPAGE_LINK_CONTRAST_AND_HQ_INFINITY_CORE_REPAIR_V1",
        missionType: "CRE_HOMEPAGE_LINK_CONTRAST_AND_HQ_INFINITY_CORE_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_HOMEPAGE_HERO_AND_HQ_CORE_REPAIR: "executive_office",
          REPRODUCE_HOMEPAGE_HERO_LINK_CONTRAST: "quality_control",
          SITE_ARCHITECTURE: "systems_architect",
          ARTIFACT_GENERATION: "product_lab",
          HQ_DECISION_CORE: "product_lab",
          VALIDATE_TECHNICAL: "quality_control",
          QUALITY_REVIEW: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreSiteChromeLinkContrastRepairRuntime: {
        runtime: "CRE_SITE_CHROME_LINK_CONTRAST_REPAIR_V1",
        missionType: "CRE_SITE_CHROME_LINK_CONTRAST_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_SITE_CHROME_LINK_CONTRAST_REPAIR: "executive_office",
          REPRODUCE_SITE_CHROME_LINK_CONTRAST: "quality_control",
          SITE_ARCHITECTURE: "systems_architect",
          ARTIFACT_GENERATION: "product_lab",
          VALIDATE_TECHNICAL: "quality_control",
          QUALITY_REVIEW: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreHubLayoutRepairDeployRuntime: {
        runtime: "GOVERNED_CRE_HUB_LAYOUT_REPAIR_DEPLOYMENT_V1",
        missionType: "GOVERNED_CRE_HUB_LAYOUT_REPAIR_DEPLOYMENT_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_HUB_LAYOUT_REPAIR_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      FounderFullSiteVisualAcceptanceRuntime: {
        runtime: "FOUNDER_PHYSICAL_FULL_SITE_VISUAL_ACCEPTANCE_AND_OUTREACH_UNLOCK_V1",
        missionType: "FOUNDER_PHYSICAL_FULL_SITE_VISUAL_ACCEPTANCE_AND_OUTREACH_UNLOCK_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_FOUNDER_FULL_SITE_VISUAL_ACCEPTANCE: "executive_office",
          RECORD_FOUNDER_ACCEPTANCE: "quality_control",
          UNLOCK_NEXT_MILESTONE: "executive_office",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      VentureScaleAndCommercializationFoundationRuntime: {
        runtime: "VentureScaleAndCommercializationFoundationRuntime",
        missionType: "VENTURE_SCALE_AND_COMMERCIALIZATION_FOUNDATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_VENTURE_OPERATING_SCALE: "executive_office",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          BACKFILL_CRE_OPERATING_RECORD: "quality_control",
          BUILD_DAILY_OPERATING_CYCLE: "intelligence_center",
          BUILD_PORTFOLIO_OPERATING_CYCLE: "intelligence_center",
          BUILD_DOMAIN_PAYMENT_FOUNDATION: "growth_department",
          EVALUATE_COMMERCIALIZATION_READINESS: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      ParallelCreCommercializationExecutionRuntime: {
        runtime: "ParallelCreCommercializationExecutionRuntime",
        missionType: "PARALLEL_CRE_COMMERCIALIZATION_EXECUTION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_PARALLEL_CRE_COMMERCIALIZATION: "executive_office",
          EVALUATE_MISSION_CONCURRENCY: "executive_office",
          RESEARCH_VENTURE_NAMING: "research_department",
          VERIFY_DOMAIN_PROVIDERS: "quality_control",
          GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
          VERIFY_STRIPE_CONNECTION: "quality_control",
          BUILD_PAYMENT_CONFIGURATION_PLAN: "systems_architect",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreProductionDomainAcquisitionRuntime: {
        runtime: "CreProductionDomainAcquisitionRuntime",
        missionType: "CRE_PRODUCTION_DOMAIN_ACQUISITION_V1",
        defaultRoom: "research_department",
        stepToRoom: {
          RESEARCH_VENTURE_NAMING: "research_department",
          VERIFY_DOMAIN_PROVIDERS: "quality_control",
          GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreStripeCapabilityAndPaymentConfigurationReadinessRuntime: {
        runtime: "CreStripeCapabilityAndPaymentConfigurationReadinessRuntime",
        missionType: "CRE_STRIPE_CAPABILITY_AND_PAYMENT_CONFIGURATION_READINESS_V1",
        defaultRoom: "quality_control",
        stepToRoom: {
          VERIFY_STRIPE_CONNECTION: "quality_control",
          BUILD_PAYMENT_CONFIGURATION_PLAN: "systems_architect",
          EVALUATE_PAYMENT_READINESS: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreStripeReverificationAndCommercialConfigurationRuntime: {
        runtime: "CreStripeReverificationAndCommercialConfigurationRuntime",
        missionType: "CRE_STRIPE_REVERIFICATION_AND_COMMERCIAL_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_STRIPE_REVERIFICATION_AND_COMMERCIAL_CONFIGURATION: "executive_office",
          RELOAD_STRIPE_RUNTIME_ENV: "systems_architect",
          VERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          VERIFY_STRIPE_READ_CAPABILITIES: "quality_control",
          RECONCILE_STRIPE_OBJECTS: "quality_control",
          GOVERN_STRIPE_WRITE_GATES: "strategy_finance",
          CONFIGURE_STRIPE_PRODUCTS: "systems_architect",
          PROVIDER_READBACK: "quality_control",
          IDEMPOTENT_RECONCILIATION: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareRegistrarLiveVerificationV2Runtime: {
        runtime: "CreCloudflareRegistrarLiveVerificationV2Runtime",
        missionType: "CRE_CLOUDFLARE_REGISTRAR_LIVE_VERIFICATION_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_REGISTRAR_LIVE_VERIFICATION: "executive_office",
          RELOAD_CLOUDFLARE_RUNTIME_ENV: "systems_architect",
          VERIFY_CLOUDFLARE_ACCOUNT: "quality_control",
          VERIFY_REGISTRAR_API: "quality_control",
          CHECK_DOMAIN_AVAILABILITY: "research_department",
          RANK_DOMAIN_CANDIDATES: "research_department",
          GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
          ROUTE_DOMAIN_PROVIDER: "systems_architect",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareRegistrarShortlistPricingV1Runtime: {
        runtime: "CreCloudflareRegistrarShortlistPricingV1Runtime",
        missionType: "CRE_CLOUDFLARE_REGISTRAR_SHORTLIST_PRICING_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_REGISTRAR_SHORTLIST_PRICING: "executive_office",
          RELOAD_CLOUDFLARE_RUNTIME_ENV: "systems_architect",
          VERIFY_CLOUDFLARE_ACCOUNT: "quality_control",
          CHECK_DOMAIN_AVAILABILITY: "research_department",
          VERIFY_DOMAIN_PRICING: "research_department",
          RANK_DOMAIN_CANDIDATES: "research_department",
          SCREEN_DOMAIN_CONFLICTS: "quality_control",
          GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
          ROUTE_DOMAIN_PROVIDER: "systems_architect",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvDomainPurchaseV2Runtime: {
        runtime: "CreOccupancynpvDomainPurchaseV2Runtime",
        missionType: "CRE_OCCUPANCYNPV_DOMAIN_PURCHASE_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_DOMAIN_PURCHASE: "executive_office",
          RELOAD_CLOUDFLARE_RUNTIME_ENV: "systems_architect",
          RECHECK_DOMAIN_AVAILABILITY: "quality_control",
          VERIFY_REGISTRATION_PREREQUISITES: "quality_control",
          GOVERN_DOMAIN_PURCHASE: "strategy_finance",
          CHECK_EXISTING_OWNERSHIP: "quality_control",
          EXECUTE_DOMAIN_REGISTRATION: "strategy_finance",
          READBACK_DOMAIN_OWNERSHIP: "quality_control",
          RECONCILE_PURCHASE_FINANCIALS: "strategy_finance",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareDnsLiveWriteVerificationV2Runtime: {
        runtime: "CreCloudflareDnsLiveWriteVerificationV2Runtime",
        missionType: "CRE_CLOUDFLARE_DNS_LIVE_WRITE_VERIFICATION_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_DNS_LIVE_WRITE_VERIFICATION: "executive_office",
          RELOAD_CLOUDFLARE_DNS_TOKEN: "systems_architect",
          VERIFY_ZONE_ACCESS: "quality_control",
          CREATE_TEMPORARY_TXT: "systems_architect",
          READBACK_TEMPORARY_TXT: "quality_control",
          DELETE_TEMPORARY_TXT: "systems_architect",
          EVALUATE_DNS_WRITE_CAPABILITY: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareDns403RootCauseDiagnosticV1Runtime: {
        runtime: "CreCloudflareDns403RootCauseDiagnosticV1Runtime",
        missionType: "CRE_CLOUDFLARE_DNS_403_ROOT_CAUSE_DIAGNOSTIC_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_DNS_403_ROOT_CAUSE_DIAGNOSTIC: "executive_office",
          VERIFY_TOKEN_IDENTITY: "quality_control",
          TRACE_ADAPTER_AUTHENTICATION: "systems_architect",
          VERIFY_PROVIDER_ZONE_ID: "quality_control",
          RAW_DNS_WRITE_PROBE: "systems_architect",
          CLASSIFY_403_ROOT_CAUSE: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvLegalStripeCommercializationAuditV2Runtime: {
        runtime: "CreOccupancynpvLegalStripeCommercializationAuditV2Runtime",
        missionType: "CRE_OCCUPANCYNPV_LEGAL_STRIPE_COMMERCIALIZATION_AUDIT_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_LEGAL_STRIPE_AUDIT: "executive_office",
          RECONCILE_INFRASTRUCTURE_STATE: "launch_operations",
          AUDIT_LEGAL_FACTS_AND_SURFACES: "quality_control",
          VERIFY_STRIPE_ACCOUNT_AND_CAPABILITIES: "quality_control",
          RECONCILE_CANONICAL_OFFERS: "strategy_finance",
          PLAN_CHECKOUT_WEBHOOK_AND_ANALYTICS: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvStripeProductPriceConfigurationV1Runtime: {
        runtime: "CreOccupancynpvStripeProductPriceConfigurationV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_STRIPE_PRODUCT_PRICE_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_PRODUCT_PRICE_CONFIGURATION: "executive_office",
          REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          RECONCILE_EXISTING_STRIPE_OBJECTS: "strategy_finance",
          EVALUATE_WRITE_GOVERNANCE: "strategy_finance",
          CREATE_CANONICAL_STRIPE_PRODUCTS: "strategy_finance",
          CREATE_CANONICAL_STRIPE_PRICES: "strategy_finance",
          READBACK_CANONICAL_STRIPE_OBJECTS: "quality_control",
          PERSIST_PAYMENT_BINDINGS: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvFirstPaymentActivationV1Runtime: {
        runtime: "CreOccupancynpvFirstPaymentActivationV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_FIRST_PAYMENT_ACTIVATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_OCCUPANCYNPV_FIRST_PAYMENT_ACTIVATION: "executive_office",
          REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          REVERIFY_CANONICAL_PAYMENT_OBJECTS: "strategy_finance",
          REVERIFY_CANONICAL_WEBHOOK: "quality_control",
          REVERIFY_CHECKOUT_SAFETY: "quality_control",
          EVALUATE_ACTIVATION_GATES: "strategy_finance",
          ACTIVATE_PAYMENT_PATH: "strategy_finance",
          VERIFY_PURCHASE_SURFACE: "launch_operations",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_PUBLIC_LAUNCH_FIREWALL: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvVentureSpecificCommercialFulfillmentArchitectureV1Runtime: {
        runtime: "CreOccupancynpvVentureSpecificCommercialFulfillmentArchitectureV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_VENTURE_SPECIFIC_COMMERCIAL_FULFILLMENT_ARCHITECTURE_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_OCCUPANCYNPV_FULFILLMENT_ARCHITECTURE: "executive_office",
          LOCK_GLOBAL_FULFILLMENT_PRINCIPLES: "strategy_finance",
          DISCOVER_OCCUPANCYNPV_PRODUCT_TRUTH: "quality_control",
          DEFINE_VENTURE_FULFILLMENT_CONTRACTS: "strategy_finance",
          IMPLEMENT_ENTITLEMENT_LIFECYCLE: "systems_architect",
          UPGRADE_SERVER_SIDE_FULFILLMENT_GATE: "quality_control",
          EVALUATE_READINESS_GATES: "strategy_finance",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_PUBLIC_LAUNCH_FIREWALL: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvPaymentSafetyRollbackV1Runtime: {
        runtime: "CreOccupancynpvPaymentSafetyRollbackV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_PAYMENT_SAFETY_ROLLBACK_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_OCCUPANCYNPV_PAYMENT_SAFETY_ROLLBACK: "executive_office",
          AUDIT_POST_ACTIVATION_TRANSACTIONS: "quality_control",
          DISABLE_CUSTOMER_PAYMENT_INITIATION: "strategy_finance",
          PRESERVE_PAYMENT_INFRASTRUCTURE: "quality_control",
          ADD_FULFILLMENT_READINESS_DEPENDENCY: "strategy_finance",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_PUBLIC_LAUNCH_FIREWALL: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvDurableCommercialProviderMutationAuthorityV1Runtime: {
        runtime: "CreOccupancynpvDurableCommercialProviderMutationAuthorityV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_DURABLE_COMMERCIAL_PROVIDER_MUTATION_AUTHORITY_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_DURABLE_COMMERCIAL_PROVIDER_MUTATION_AUTHORITY: "executive_office",
          DEFINE_MUTATION_TAXONOMY: "strategy_finance",
          EVALUATE_DEFAULT_AUTONOMY_MATRIX: "strategy_finance",
          INSTANTIATE_OCCUPANCYNPV_MUTATION_POLICY: "strategy_finance",
          DEFINE_PAYMENT_ACTIVATION_POLICY: "strategy_finance",
          PRESERVE_PAYMENT_AND_LAUNCH_BLOCKERS: "quality_control",
          PROJECT_HQ_AUTHORITY_VISIBILITY: "intelligence_center",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvStripeWebhookWriteRetryV2Runtime: {
        runtime: "CreOccupancynpvStripeWebhookWriteRetryV2Runtime",
        missionType: "CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_WRITE_RETRY_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_WRITE_RETRY: "executive_office",
          REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          VERIFY_WEBHOOK_WRITE_CAPABILITY: "quality_control",
          RECONCILE_EXISTING_STRIPE_WEBHOOKS: "quality_control",
          CREATE_OR_RECONCILE_CANONICAL_WEBHOOK: "strategy_finance",
          PERSIST_WEBHOOK_SIGNING_SECRET: "systems_architect",
          READBACK_CANONICAL_WEBHOOK: "quality_control",
          VERIFY_APPLICATION_AND_LINEAGE: "intelligence_center",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          RECORD_AUTONOMY_POLICY_GAP: "strategy_finance",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvStripeWebhookConfigurationV1Runtime: {
        runtime: "CreOccupancynpvStripeWebhookConfigurationV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_STRIPE_WEBHOOK_CONFIGURATION: "executive_office",
          REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          RECONCILE_EXISTING_STRIPE_WEBHOOKS: "quality_control",
          CREATE_OR_RECONCILE_CANONICAL_WEBHOOK: "strategy_finance",
          PERSIST_WEBHOOK_SIGNING_SECRET: "systems_architect",
          READBACK_CANONICAL_WEBHOOK: "quality_control",
          VERIFY_APPLICATION_AND_LINEAGE: "intelligence_center",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          RECORD_AUTONOMY_POLICY_GAP: "strategy_finance",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvCheckoutWebhookAnalyticsConfigurationV1Runtime: {
        runtime: "CreOccupancynpvCheckoutWebhookAnalyticsConfigurationV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_CHECKOUT_WEBHOOK_ANALYTICS_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_CHECKOUT_WEBHOOK_ANALYTICS_CONFIGURATION: "executive_office",
          CONFIGURE_CHECKOUT_ARCHITECTURE: "strategy_finance",
          CONFIGURE_CHECKOUT_SESSION_BOUNDARY: "strategy_finance",
          CONFIGURE_SUCCESS_CANCEL_ROUTES: "product_lab",
          CONFIGURE_WEBHOOK_APPLICATION: "systems_architect",
          RECONCILE_STRIPE_WEBHOOK_ENDPOINTS: "quality_control",
          CONFIGURE_ANALYTICS_AND_REVENUE_LINEAGE: "intelligence_center",
          AUDIT_PRIVACY_AND_PUBLIC_CHECKOUT_EXPOSURE: "quality_control",
          VALIDATE_PRODUCTION_HOST_AND_ROUTES: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvLegalConfigurationV1Runtime: {
        runtime: "CreOccupancynpvLegalConfigurationV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_LEGAL_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_LEGAL_CONFIGURATION: "executive_office",
          PERSIST_CANONICAL_LEGAL_FACTS: "quality_control",
          COMPOSE_LEGAL_SURFACE_SUCCESSOR: "product_lab",
          PUBLISH_LEGAL_SURFACES: "launch_operations",
          VALIDATE_LEGAL_SURFACES: "quality_control",
          VALIDATE_PRODUCTION_HOST_AND_ROUTES: "quality_control",
          EVALUATE_LEGAL_CONFIGURATION_GATE: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvVercelDeploymentBindingRepairV1Runtime: {
        runtime: "CreOccupancynpvVercelDeploymentBindingRepairV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_VERCEL_DEPLOYMENT_BINDING_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_VERCEL_BINDING_REPAIR: "executive_office",
          VERIFY_CURRENT_VERCEL_DEPLOYMENT_STATE: "launch_operations",
          VERIFY_DOMAIN_ASSIGNMENT: "launch_operations",
          IDENTIFY_ROOT_CAUSE: "quality_control",
          PRESERVE_ACCEPTED_ARTIFACT: "quality_control",
          REPAIR_DOMAIN_DEPLOYMENT_BINDING: "launch_operations",
          VALIDATE_HTTPS_HOST_AND_ROUTES: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvSslFinalizationCheckV2Runtime: {
        runtime: "CreOccupancynpvSslFinalizationCheckV2Runtime",
        missionType: "CRE_OCCUPANCYNPV_SSL_FINALIZATION_CHECK_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_SSL_FINALIZATION: "executive_office",
          CONFIRM_READONLY_DNS: "quality_control",
          QUERY_VERCEL_DOMAIN_STATUS: "launch_operations",
          VERIFY_SSL_AND_HTTPS: "quality_control",
          VALIDATE_PRODUCTION_HOST_AND_ROUTES: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvProductionDnsVercelSslExecutionV4Runtime: {
        runtime: "CreOccupancynpvProductionDnsVercelSslExecutionV4Runtime",
        missionType: "CRE_OCCUPANCYNPV_PRODUCTION_DNS_VERCEL_SSL_EXECUTION_V4",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_DNS_VERCEL_BINDING: "executive_office",
          RECONFIRM_DOMAIN_OWNERSHIP: "quality_control",
          VERIFY_CLOUDFLARE_DNS_CAPABILITY: "systems_architect",
          VERIFY_OR_CREATE_ZONE: "systems_architect",
          RECONCILE_NAMESERVERS: "quality_control",
          QUERY_VERCEL_DOMAIN_REQUIREMENTS: "launch_operations",
          BIND_VERCEL_DOMAIN: "launch_operations",
          WRITE_CLOUDFLARE_DNS: "systems_architect",
          VERIFY_DNS_AND_SSL: "quality_control",
          VALIDATE_ROUTES_AND_HOST: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareUserDnsTokenVerifyV1Runtime: {
        runtime: "CreCloudflareUserDnsTokenVerifyV1Runtime",
        missionType: "CRE_CLOUDFLARE_USER_DNS_TOKEN_VERIFY_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_USER_DNS_TOKEN_VERIFY: "executive_office",
          VERIFY_USER_TOKEN_IDENTITY: "quality_control",
          REJECT_PREVIOUS_ACCOUNT_TOKEN: "quality_control",
          USER_DNS_WRITE_PROBE: "systems_architect",
          EVALUATE_USER_DNS_TOKEN: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareDnsWriteRetryAfterTokenExpansionV3Runtime: {
        runtime: "CreCloudflareDnsWriteRetryAfterTokenExpansionV3Runtime",
        missionType: "CRE_CLOUDFLARE_DNS_WRITE_RETRY_AFTER_TOKEN_EXPANSION_V3",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_DNS_VERCEL_BINDING: "executive_office",
          RECONFIRM_DOMAIN_OWNERSHIP: "quality_control",
          VERIFY_CLOUDFLARE_DNS_CAPABILITY: "systems_architect",
          VERIFY_OR_CREATE_ZONE: "systems_architect",
          RECONCILE_NAMESERVERS: "quality_control",
          QUERY_VERCEL_DOMAIN_REQUIREMENTS: "launch_operations",
          BIND_VERCEL_DOMAIN: "launch_operations",
          WRITE_CLOUDFLARE_DNS: "systems_architect",
          VERIFY_DNS_AND_SSL: "quality_control",
          VALIDATE_ROUTES_AND_HOST: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCloudflareDnsVercelBindingV1Runtime: {
        runtime: "CreCloudflareDnsVercelBindingV1Runtime",
        missionType: "CRE_CLOUDFLARE_DNS_VERCEL_BINDING_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_CLOUDFLARE_DNS_VERCEL_BINDING: "executive_office",
          RECONFIRM_DOMAIN_OWNERSHIP: "quality_control",
          VERIFY_CLOUDFLARE_DNS_CAPABILITY: "systems_architect",
          VERIFY_OR_CREATE_ZONE: "systems_architect",
          RECONCILE_NAMESERVERS: "quality_control",
          QUERY_VERCEL_DOMAIN_REQUIREMENTS: "launch_operations",
          BIND_VERCEL_DOMAIN: "launch_operations",
          WRITE_CLOUDFLARE_DNS: "systems_architect",
          VERIFY_DNS_AND_SSL: "quality_control",
          VALIDATE_ROUTES_AND_HOST: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreOccupancynpvDomainPurchaseRetryAfterCloudflarePrerequisitesV1Runtime: {
        runtime: "CreOccupancynpvDomainPurchaseRetryAfterCloudflarePrerequisitesV1Runtime",
        missionType: "CRE_OCCUPANCYNPV_DOMAIN_PURCHASE_RETRY_AFTER_CLOUDFLARE_PREREQUISITES_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_OCCUPANCYNPV_DOMAIN_PURCHASE: "executive_office",
          RELOAD_CLOUDFLARE_RUNTIME_ENV: "systems_architect",
          RECHECK_DOMAIN_AVAILABILITY: "quality_control",
          VERIFY_REGISTRATION_PREREQUISITES: "quality_control",
          GOVERN_DOMAIN_PURCHASE: "strategy_finance",
          CHECK_EXISTING_OWNERSHIP: "quality_control",
          EXECUTE_DOMAIN_REGISTRATION: "strategy_finance",
          READBACK_DOMAIN_OWNERSHIP: "quality_control",
          RECONCILE_PURCHASE_FINANCIALS: "strategy_finance",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreStripeAccountReverificationAndConfigurationV2Runtime: {
        runtime: "CreStripeAccountReverificationAndConfigurationV2Runtime",
        missionType: "CRE_STRIPE_ACCOUNT_REVERIFICATION_AND_CONFIGURATION_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_STRIPE_ACCOUNT_REVERIFICATION_AND_CONFIGURATION: "executive_office",
          RELOAD_STRIPE_RUNTIME_ENV: "systems_architect",
          VERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          VERIFY_STRIPE_READ_CAPABILITIES: "quality_control",
          RECONCILE_STRIPE_OBJECTS: "quality_control",
          GOVERN_STRIPE_WRITE_GATES: "strategy_finance",
          CONFIGURE_STRIPE_PRODUCTS: "systems_architect",
          PROVIDER_READBACK: "quality_control",
          IDEMPOTENT_RECONCILIATION: "quality_control",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          EVALUATE_PAYMENT_READINESS: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreCommercialProviderAccessRepairRuntime: {
        runtime: "CreCommercialProviderAccessRepairRuntime",
        missionType: "CRE_COMMERCIAL_PROVIDER_ACCESS_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_COMMERCIAL_PROVIDER_ACCESS_REPAIR: "executive_office",
          CLASSIFY_PROVIDER_BLOCKS: "systems_architect",
          INSPECT_NAMECHEAP_SAFE_CONFIG: "research_department",
          REVERIFY_NAMECHEAP_DOMAIN_READS: "quality_control",
          INSPECT_STRIPE_KEY_CAPABILITIES: "quality_control",
          REVERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          LOOKUP_EXISTING_STRIPE_OBJECTS: "quality_control",
          SEARCH_CANONICAL_LEGAL_FACTS: "research_department",
          RECONCILE_LEGAL_SURFACES: "quality_control",
          RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreDomainProviderAndStripeConfigurationRuntime: {
        runtime: "CreDomainProviderAndStripeConfigurationRuntime",
        missionType: "CRE_DOMAIN_PROVIDER_AND_STRIPE_CONFIGURATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_DOMAIN_PROVIDER_AND_STRIPE_CONFIGURATION: "executive_office",
          EVALUATE_MISSION_CONCURRENCY: "executive_office",
          VERIFY_DOMAIN_PROVIDERS: "quality_control",
          RESEARCH_VENTURE_NAMING: "research_department",
          GOVERN_DOMAIN_ECONOMICS: "strategy_finance",
          VERIFY_STRIPE_ACCOUNT_IDENTITY: "quality_control",
          RECONCILE_STRIPE_OBJECTS: "quality_control",
          CONFIGURE_STRIPE_PRODUCTS: "systems_architect",
          RECONCILE_LEGAL_SURFACES: "quality_control",
          RUN_DAILY_VENTURE_OPERATING_CYCLE: "intelligence_center",
          RECONCILE_VENTURE_OPERATIONAL_RECORD: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreContextRichChallengerOutcomeObservationRuntime: {
        runtime: "CreContextRichChallengerOutcomeObservationRuntime",
        missionType: "CRE_CONTEXT_RICH_CHALLENGER_OUTCOME_OBSERVATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CHALLENGER_OUTCOME_OBSERVATION: "executive_office",
          TRACKED_THREAD_OBSERVATION: "intelligence_center",
          INGEST_CHALLENGER_INBOUND: "growth_department",
          CLASSIFY_AND_POLICY: "quality_control",
          OUTCOME_EVALUATION: "intelligence_center",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      GovernedCreContextRichOutreachExecutionRuntime: {
        runtime: "GOVERNED_CRE_CONTEXT_RICH_OUTREACH_EXECUTION_V1",
        missionType: "GOVERNED_CRE_CONTEXT_RICH_OUTREACH_EXECUTION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_GOVERNED_CONTEXT_RICH_OUTREACH: "executive_office",
          RESEARCH_PERSONA_EVIDENCE: "research_department",
          CONTACT_REVERIFICATION: "quality_control",
          OUTREACH_MESSAGE_STRATEGY: "growth_department",
          MESSAGE_QUALITY_VALIDATION: "quality_control",
          PROSPECT_ELIGIBILITY_VALIDATION: "quality_control",
          PROVIDER_SEND: "growth_department",
          RESULT_PERSISTENCE: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      ContextRichConsultativeOutreachOptimizationRuntime: {
        runtime: "CONTEXT_RICH_CONSULTATIVE_OUTREACH_OPTIMIZATION_V1",
        missionType: "CONTEXT_RICH_CONSULTATIVE_OUTREACH_OPTIMIZATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CONTEXT_RICH_OUTREACH_OPTIMIZATION: "executive_office",
          RESEARCH_PERSONA_EVIDENCE: "research_department",
          OUTREACH_MESSAGE_STRATEGY: "growth_department",
          COMMUNICATION_POLICY_ARCHITECTURE: "systems_architect",
          MESSAGE_QUALITY_VALIDATION: "quality_control",
          PROSPECT_ELIGIBILITY_VALIDATION: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
          OUTREACH_AUTHORIZATION: "growth_department",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreSemanticNavWidthMutedTextDeployRuntime: {
        runtime: "GOVERNED_CRE_SEMANTIC_NAV_WIDTH_MUTED_TEXT_DEPLOYMENT_V1",
        missionType: "GOVERNED_CRE_SEMANTIC_NAV_WIDTH_MUTED_TEXT_DEPLOYMENT_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_SEMANTIC_NAV_WIDTH_MUTED_TEXT_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreHomepageHeroLinkContrastDeployRuntime: {
        runtime: "GOVERNED_CRE_HOMEPAGE_LINK_CONTRAST_DEPLOYMENT_V1",
        missionType: "GOVERNED_CRE_HOMEPAGE_LINK_CONTRAST_DEPLOYMENT_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_HOMEPAGE_HERO_LINK_CONTRAST_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreSiteChromeLinkContrastDeployRuntime: {
        runtime: "GOVERNED_CRE_SITE_CHROME_LINK_CONTRAST_DEPLOYMENT_V1",
        missionType: "GOVERNED_CRE_SITE_CHROME_LINK_CONTRAST_DEPLOYMENT_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_SITE_CHROME_LINK_CONTRAST_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreFullPageAutorepairDeployV2Runtime: {
        runtime: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V2",
        missionType: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V2",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_FULL_PAGE_AUTOREPAIR_DEPLOY: "executive_office",
          QUALITY_REVIEW: "quality_control",
          PREPARE_SOURCE_BUNDLE: "launch_operations",
          CREATE_DEPLOYMENT: "launch_operations",
          PUBLIC_ARTIFACT_QUALITY_GATE: "quality_control",
          ACTIVATE_PUBLIC_ARTIFACT: "launch_operations",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreFullPageAutorepairRuntime: {
        runtime: "CRE_FULL_PAGE_RENDER_VALIDATE_REPAIR_V1",
        missionType: "CRE_FULL_PAGE_RENDER_VALIDATE_REPAIR_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_FULL_PAGE_AUTOREPAIR: "executive_office",
          PAGE_COMPOSE: "product_lab",
          DESIGN_SYSTEM_REPAIR: "systems_architect",
          PAGE_RENDER: "quality_control",
          PAGE_VALIDATE: "quality_control",
          PAGE_REPAIR_LOOP: "quality_control",
          REPEATED_FAILURE_PROMOTION: "systems_architect",
          PAGE_ADMISSION: "quality_control",
          FULL_ROUTE_FROZEN_ARTIFACT_VALIDATION: "quality_control",
          PRESERVE_EXPERIMENT_OBSERVER: "intelligence_center",
          PUBLISHABILITY_REVIEW: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      QuestionKnowledgeGraphQcRuntime: {
        runtime: "QUESTION_KNOWLEDGE_GRAPH_ANSWER_AUTHORITY_QC",
        missionType: "QUESTION_KNOWLEDGE_GRAPH_ANSWER_AUTHORITY_QC",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_QUESTION_AUTHORITY_QC: "executive_office",
          DISCOVER_QUESTION_UNIVERSE: "research_department",
          RESEARCH_QUESTION_CLUSTER: "research_department",
          PLAN_SITE_ARCHITECTURE: "systems_architect",
          PLAN_URL_ARCHITECTURE: "systems_architect",
          PLAN_INTERNAL_LINK_GRAPH: "systems_architect",
          VALIDATE_CONTENT_DEPTH: "quality_control",
          VALIDATE_ANSWER_AUTHORITY: "quality_control",
          VALIDATE_GEO_SEO: "quality_control",
          ADVERSARIAL_PUBLISHABILITY_REVIEW: "quality_control",
          PUBLISHABILITY_REVIEW: "quality_control",
          AUTHORITY_REPAIR_PLAN: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      MarketValidationAcquisitionRuntime: {
        runtime: "MarketValidationAcquisitionRuntime",
        missionType: "MARKET_VALIDATION_ACQUISITION",
        defaultRoom: "executive_office",
        stepToRoom: {
          PROSPECT_DISCOVERY: "research_department",
          PROSPECT_QUALIFICATION: "research_department",
          OUTREACH_PREPARATION: "growth_department",
          ACQUISITION_CHANNEL_ANALYSIS: "growth_department",
          PUBLIC_INGEST_VALIDATION: "quality_control",
          EVIDENCE_CONTRACT_AUDIT: "quality_control",
          PERFORMANCE_HANDOFF: "intelligence_center",
          GOVERNANCE_PREPARATION: "executive_office",
          ORCHESTRATE_CRE_ACQUISITION_HANDOFF: "executive_office",
        },
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: true,
        adoption: "PARTIAL",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      CreBoundedOutreachRuntime: {
        runtime: "CreBoundedOutreachRuntime",
        missionType: "CRE_WAVE_1_FRESH_CONTACT_REVERIFICATION_AND_SEND_V3",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_WAVE_1: "executive_office",
          CONTACT_REVERIFICATION: "quality_control",
          MESSAGE_STRATEGY: "growth_department",
          MESSAGE_QUALITY_VALIDATION: "quality_control",
          OUTREACH_AUTHORIZATION: "growth_department",
          PROVIDER_SEND: "growth_department",
          RESULT_PERSISTENCE: "quality_control",
          EXPERIMENT_READBACK: "quality_control",
          OUTREACH_PREPARATION: "growth_department",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      PublicWebResearchRuntime: {
        runtime: "PublicWebResearchRuntime",
        missionType: null,
        defaultRoom: "research_department",
        stepToRoom: { WEB_SEARCH: "research_department", PUBLIC_PAGE_FETCH: "research_department" },
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: true,
        adoption: "PARTIAL",
        authorizationSemantics: "MISSION_WAITING",
        lineage: { ventureId: true, candidateId: false, artifactId: false, experimentId: true },
      },
      AutonomousVentureWebsiteBuildRuntime: {
        runtime: "AutonomousVentureWebsiteBuildRuntime",
        missionType: "AUTONOMOUS_VENTURE_WEBSITE_BUILD",
        defaultRoom: "product_lab",
        stepToRoom: { GENERATE_CONTENT: "product_lab", GENERATE_PREMIUM_ARTIFACT: "product_lab" },
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: false,
        adoption: "NOT_INTEGRATED",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      deploymentRuntime: {
        runtime: "deploymentRuntime",
        missionType: "PUBLIC_DEPLOYMENT",
        defaultRoom: "launch_operations",
        stepToRoom: { CREATE_DEPLOYMENT: "launch_operations", PROVIDER_BUILD: "launch_operations" },
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: false,
        adoption: "NOT_INTEGRATED",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      PerformanceIntelligence: {
        runtime: "PerformanceIntelligence",
        missionType: "PERFORMANCE_INTELLIGENCE",
        defaultRoom: "intelligence_center",
        stepToRoom: { SITE_EXPANSION_PLAN: "intelligence_center" },
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: false,
        adoption: "NOT_INTEGRATED",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      marketValidationExperimentRuntime: {
        runtime: "marketValidationExperimentRuntime",
        missionType: "MARKET_VALIDATION_EXPERIMENT",
        defaultRoom: "quality_control",
        stepToRoom: {},
        usesCanonicalMissionWrapper: false,
        usesCanonicalStepWrapper: false,
        adoption: "PARTIAL",
        authorizationSemantics: "NONE",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      futureSiteRepairRuntime: {
        runtime: "futureSiteRepairRuntime",
        missionType: "AUTHORITY_SITE_REPAIR",
        defaultRoom: "quality_control",
        stepToRoom: { AUTHORITY_REPAIR_PLAN: "quality_control" },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      GovernedCreInboundObservationRuntime: {
        runtime: "GovernedCreInboundObservationRuntime",
        missionType: "GOVERNED_CRE_INBOUND_OBSERVATION_ACTIVATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_CRE_INBOUND_OBSERVATION: "executive_office",
          ACTIVATE_OBSERVER: "quality_control",
          INITIALIZE_HISTORY_CHECKPOINT: "intelligence_center",
          TRACKED_THREAD_OBSERVATION: "intelligence_center",
          PROCESS_NEW_INBOUND: "growth_department",
          OBSERVER_HEALTH_READBACK: "quality_control",
          ORCHESTRATE_INBOUND_PROCESSING: "executive_office",
          INGEST_TRACKED_INBOUND: "intelligence_center",
          CLASSIFY_AND_POLICY: "quality_control",
          GROUNDED_REPLY_SEND: "growth_department",
          EVIDENCE_CONTRACT_AUDIT: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: false, experimentId: true },
      },
      InboundCommunicationRuntime: {
        runtime: "InboundCommunicationRuntime",
        missionType: "INBOUND_COMMUNICATION_AUTONOMOUS_CONVERSATION_RUNTIME_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_INBOUND_COMMUNICATION: "executive_office",
          INSPECT_INBOUND_SCOPES: "quality_control",
          PREPARE_TRACKED_CONVERSATIONS: "growth_department",
          INGEST_INBOUND_EVENTS: "growth_department",
          CLASSIFY_AND_POLICY: "quality_control",
          REPLY_PLANNING: "growth_department",
          EVIDENCE_CONTRACT_AUDIT: "quality_control",
          HQ_INTELLIGENCE_PROJECTION: "intelligence_center",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
      AutonomousEmailReplyWriteVerificationRuntime: {
        runtime: "AutonomousEmailReplyWriteVerificationRuntime",
        missionType: "AUTONOMOUS_EMAIL_REPLY_WRITE_VERIFICATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_AUTONOMOUS_REPLY_WRITE: "executive_office",
          CONTROLLED_TARGET_GATE: "quality_control",
          PREPARE_VERIFICATION_CONVERSATION: "intelligence_center",
          SETUP_OR_REUSE_THREAD: "quality_control",
          INGEST_CONTROLLED_INBOUND: "intelligence_center",
          CLASSIFY_TRACKED_INBOUND: "growth_department",
          GROUNDED_REPLY_SEND: "growth_department",
          CAPABILITY_READBACK: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: false, artifactId: false, experimentId: false },
      },
      AutonomousEmailReplyWriteVerificationContinuationRuntime: {
        runtime: "AutonomousEmailReplyWriteVerificationContinuationRuntime",
        missionType: "AUTONOMOUS_EMAIL_REPLY_WRITE_VERIFICATION_CONTINUATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_AUTONOMOUS_REPLY_WRITE: "executive_office",
          CONTROLLED_TARGET_GATE: "quality_control",
          PREPARE_VERIFICATION_CONVERSATION: "intelligence_center",
          SETUP_OR_REUSE_THREAD: "quality_control",
          INGEST_CONTROLLED_INBOUND: "intelligence_center",
          CLASSIFY_TRACKED_INBOUND: "growth_department",
          GROUNDED_REPLY_SEND: "growth_department",
          CAPABILITY_READBACK: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: false, artifactId: false, experimentId: false },
      },
      GmailInboundReadVerificationRuntime: {
        runtime: "GmailInboundReadVerificationRuntime",
        missionType: "GMAIL_INBOUND_READ_VERIFICATION_V1",
        defaultRoom: "executive_office",
        stepToRoom: {
          ORCHESTRATE_GMAIL_INBOUND_READ: "executive_office",
          OAUTH_REFRESH_AND_IDENTITY: "quality_control",
          SCOPE_GRANT_INSPECTION: "quality_control",
          PRESERVE_SEND_CAPABILITY: "quality_control",
          TRACKED_THREAD_READ: "intelligence_center",
          NARROW_SEARCH: "intelligence_center",
          HISTORY_CHECKPOINT: "intelligence_center",
          REPLY_INGEST_DRY: "quality_control",
          CLASSIFY_TRACKED_INBOUND: "growth_department",
          EVIDENCE_CONTRACT_AUDIT: "quality_control",
        },
        usesCanonicalMissionWrapper: true,
        usesCanonicalStepWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
        authorizationSemantics: "MISSION_BLOCKED",
        lineage: { ventureId: true, candidateId: true, artifactId: true, experimentId: true },
      },
    },
    runtimes: {
      MarketValidationAcquisitionRuntime: {
        runtime: "MarketValidationAcquisitionRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: false,
        adoption: "PARTIAL",
        futureUsesMissionWrapper: true,
      },
      CreBoundedOutreachRuntime: {
        runtime: "CreBoundedOutreachRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      PublicWebResearchRuntime: {
        runtime: "PublicWebResearchRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: false,
        adoption: "PARTIAL",
        consumedByQuestionDiscovery: true,
      },
      AutonomousVentureWebsiteBuildRuntime: {
        runtime: "AutonomousVentureWebsiteBuildRuntime",
        usesStepWrapper: false,
        usesMissionWrapper: false,
        adoption: "NOT_INTEGRATED",
        futureSiteRepairUsesMissionWrapper: true,
      },
      CreFullPageAutorepairRuntime: {
        runtime: "CRE_FULL_PAGE_RENDER_VALIDATE_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreFullPageAutorepairDeployRuntime: {
        runtime: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreFullPageAutorepairDeployV2Runtime: {
        runtime: "GOVERNED_CRE_FULL_PAGE_AUTOREPAIR_DEPLOYMENT_V2",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreHubLayoutRepairDeployRuntime: {
        runtime: "GOVERNED_CRE_HUB_LAYOUT_REPAIR_DEPLOYMENT_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      FounderFullSiteVisualAcceptanceRuntime: {
        runtime: "FOUNDER_PHYSICAL_FULL_SITE_VISUAL_ACCEPTANCE_AND_OUTREACH_UNLOCK_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      VentureScaleAndCommercializationFoundationRuntime: {
        runtime: "VentureScaleAndCommercializationFoundationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      ParallelCreCommercializationExecutionRuntime: {
        runtime: "ParallelCreCommercializationExecutionRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreProductionDomainAcquisitionRuntime: {
        runtime: "CreProductionDomainAcquisitionRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreStripeCapabilityAndPaymentConfigurationReadinessRuntime: {
        runtime: "CreStripeCapabilityAndPaymentConfigurationReadinessRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreStripeReverificationAndCommercialConfigurationRuntime: {
        runtime: "CreStripeReverificationAndCommercialConfigurationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareRegistrarLiveVerificationV2Runtime: {
        runtime: "CreCloudflareRegistrarLiveVerificationV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareRegistrarShortlistPricingV1Runtime: {
        runtime: "CreCloudflareRegistrarShortlistPricingV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvDomainPurchaseV2Runtime: {
        runtime: "CreOccupancynpvDomainPurchaseV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvDomainPurchaseRetryAfterCloudflarePrerequisitesV1Runtime: {
        runtime: "CreOccupancynpvDomainPurchaseRetryAfterCloudflarePrerequisitesV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareDnsVercelBindingV1Runtime: {
        runtime: "CreCloudflareDnsVercelBindingV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareDnsWriteRetryAfterTokenExpansionV3Runtime: {
        runtime: "CreCloudflareDnsWriteRetryAfterTokenExpansionV3Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareDnsLiveWriteVerificationV2Runtime: {
        runtime: "CreCloudflareDnsLiveWriteVerificationV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareDns403RootCauseDiagnosticV1Runtime: {
        runtime: "CreCloudflareDns403RootCauseDiagnosticV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCloudflareUserDnsTokenVerifyV1Runtime: {
        runtime: "CreCloudflareUserDnsTokenVerifyV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvProductionDnsVercelSslExecutionV4Runtime: {
        runtime: "CreOccupancynpvProductionDnsVercelSslExecutionV4Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvLegalStripeCommercializationAuditV2Runtime: {
        runtime: "CreOccupancynpvLegalStripeCommercializationAuditV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvLegalConfigurationV1Runtime: {
        runtime: "CreOccupancynpvLegalConfigurationV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvStripeProductPriceConfigurationV1Runtime: {
        runtime: "CreOccupancynpvStripeProductPriceConfigurationV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvCheckoutWebhookAnalyticsConfigurationV1Runtime: {
        runtime: "CreOccupancynpvCheckoutWebhookAnalyticsConfigurationV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvStripeWebhookConfigurationV1Runtime: {
        runtime: "CreOccupancynpvStripeWebhookConfigurationV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvVentureSpecificCommercialFulfillmentArchitectureV1Runtime: {
        runtime: "CreOccupancynpvVentureSpecificCommercialFulfillmentArchitectureV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvPaymentSafetyRollbackV1Runtime: {
        runtime: "CreOccupancynpvPaymentSafetyRollbackV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvFirstPaymentActivationV1Runtime: {
        runtime: "CreOccupancynpvFirstPaymentActivationV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvDurableCommercialProviderMutationAuthorityV1Runtime: {
        runtime: "CreOccupancynpvDurableCommercialProviderMutationAuthorityV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvStripeWebhookWriteRetryV2Runtime: {
        runtime: "CreOccupancynpvStripeWebhookWriteRetryV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvVercelDeploymentBindingRepairV1Runtime: {
        runtime: "CreOccupancynpvVercelDeploymentBindingRepairV1Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreOccupancynpvSslFinalizationCheckV2Runtime: {
        runtime: "CreOccupancynpvSslFinalizationCheckV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreStripeAccountReverificationAndConfigurationV2Runtime: {
        runtime: "CreStripeAccountReverificationAndConfigurationV2Runtime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreCommercialProviderAccessRepairRuntime: {
        runtime: "CreCommercialProviderAccessRepairRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreDomainProviderAndStripeConfigurationRuntime: {
        runtime: "CreDomainProviderAndStripeConfigurationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreContextRichChallengerOutcomeObservationRuntime: {
        runtime: "CreContextRichChallengerOutcomeObservationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      GovernedCreContextRichOutreachExecutionRuntime: {
        runtime: "GOVERNED_CRE_CONTEXT_RICH_OUTREACH_EXECUTION_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      ContextRichConsultativeOutreachOptimizationRuntime: {
        runtime: "CONTEXT_RICH_CONSULTATIVE_OUTREACH_OPTIMIZATION_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreSemanticNavWidthMutedTextDeployRuntime: {
        runtime: "GOVERNED_CRE_SEMANTIC_NAV_WIDTH_MUTED_TEXT_DEPLOYMENT_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreHomepageHeroLinkContrastDeployRuntime: {
        runtime: "GOVERNED_CRE_HOMEPAGE_LINK_CONTRAST_DEPLOYMENT_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreSiteChromeLinkContrastDeployRuntime: {
        runtime: "GOVERNED_CRE_SITE_CHROME_LINK_CONTRAST_DEPLOYMENT_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreSemanticNavWidthUtilizationRepairRuntime: {
        runtime: "CRE_SEMANTIC_NAV_WIDTH_UTILIZATION_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreHomepageHeroLinkAndHqInfinityCoreRepairRuntime: {
        runtime: "CRE_HOMEPAGE_LINK_CONTRAST_AND_HQ_INFINITY_CORE_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreSiteChromeLinkContrastRepairRuntime: {
        runtime: "CRE_SITE_CHROME_LINK_CONTRAST_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CrePricingPrerenderRepairRuntime: {
        runtime: "CRE_PROVIDER_EQUIVALENT_PRICING_BUILD_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      CreHubQuestionBoardLayoutRepairRuntime: {
        runtime: "CRE_HUB_QUESTION_BOARD_LAYOUT_REPAIR_V1",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      QuestionKnowledgeGraphQcRuntime: {
        runtime: "QUESTION_KNOWLEDGE_GRAPH_ANSWER_AUTHORITY_QC",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      deploymentRuntime: {
        runtime: "deploymentRuntime",
        usesStepWrapper: false,
        usesMissionWrapper: false,
        adoption: "NOT_INTEGRATED",
        futureUsesMissionWrapper: true,
      },
      PerformanceIntelligence: {
        runtime: "PerformanceIntelligence",
        usesStepWrapper: false,
        usesMissionWrapper: false,
        adoption: "NOT_INTEGRATED",
        futureUsesMissionWrapper: true,
      },
      marketValidationExperimentRuntime: {
        runtime: "marketValidationExperimentRuntime",
        usesStepWrapper: false,
        usesMissionWrapper: false,
        adoption: "PARTIAL",
      },
      futureSiteRepairRuntime: {
        runtime: "futureSiteRepairRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      InboundCommunicationRuntime: {
        runtime: "InboundCommunicationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      GovernedCreInboundObservationRuntime: {
        runtime: "GovernedCreInboundObservationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      GmailInboundReadVerificationRuntime: {
        runtime: "GmailInboundReadVerificationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      AutonomousEmailReplyWriteVerificationRuntime: {
        runtime: "AutonomousEmailReplyWriteVerificationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
      AutonomousEmailReplyWriteVerificationContinuationRuntime: {
        runtime: "AutonomousEmailReplyWriteVerificationContinuationRuntime",
        usesStepWrapper: true,
        usesMissionWrapper: true,
        adoption: "USES_CANONICAL_MISSION_WRAPPER",
      },
    },
  };
}
