import {
  evaluateCitationReadyAnswerGate,
  evaluateGEOCitationReadinessGate,
  evaluateQuestionCannibalizationGate,
  evaluateQuestionCoverageGate,
} from "../question-cluster/geo-question-cluster";
import {
  occupancynpvLeaseInputsCitationBlocks,
  occupancynpvLeaseInputsQuestionGraph,
} from "../question-cluster/occupancynpv-lease-inputs-cluster";
import { FIRST_LEASE_INPUTS_QUESTION } from "../obligation/opportunity";
import { BLOG_REPAIR_STRATEGIES, DAILY_BLOG_TARGET, MAX_OTHER_NEW_HIGH_VALUE_ASSETS_PER_DAY, OCCUPANCYNPV_GEO_REFERENCE_URL } from "./contract";
import {
  evaluateBlogBuildRecoveryGate,
  evaluateBlogHqLiveWorkGate,
  evaluateBlogObligationContinuityGate,
  evaluateBlogRequiredForGrowthReadyGate,
  evaluateBlogRequiredForLaunchGate,
  evaluateBloglessVentureGate,
  evaluateFirstVentureBlogCanaryGate,
  evaluateSystemBlogCapabilityGate,
  evaluateSystemBlogExperienceGate,
  evaluateSystemDailyBlogCoverageGate,
  evaluateSystemGEOAuthorityGate,
  evaluateVentureBlogAlwaysOnGate,
  evaluateVentureBlogInfrastructureGate,
  evaluateVentureBlogRollGate,
  evaluateVentureBlogTaxonomyGate,
  evaluateVentureContentAuthorityGate,
  evaluateVentureDailyBlogGate,
  occupancyNpvCapability,
} from "./gates";
import { listActiveBlogVentures, projectSystemBlogHq, projectVentureBlogLiveWork } from "./live-work";
import { auditActiveVentureBlogRemediation } from "./remediation";
import { ensureVentureBlogOsState, listVentureBlogOsStates } from "./store";
import { inheritVentureBlogBlueprintDefaults } from "./operating-system";
import type { NamedBlogGate } from "./types";

export type VentureBlogOsV2Report = {
  title: "INFINITY OS — GEO AUTHORITY + REQUIRED VENTURE BLOG OPERATING SYSTEM V2 REPORT";
  geo: {
    reference_url: string;
    primary_question: string;
    primary: string;
    must_answer: string;
    high_value_secondary: string;
    supporting: string;
    unresolved: number;
    CitationReadyAnswerGate: NamedBlogGate["result"];
    GEOCitationReadinessGate: NamedBlogGate["result"];
    QuestionCannibalizationGate: NamedBlogGate["result"];
  };
  coverage: ReturnType<typeof projectSystemBlogHq> & { blogless: number; BloglessVentureGate: NamedBlogGate["result"] };
  factory: Record<string, "YES" | "NO" | "PASS" | "FAIL" | NamedBlogGate["result"]>;
  daily: Record<string, number | string>;
  recovery: Record<string, number | string>;
  geo_architecture: Record<string, NamedBlogGate["result"]>;
  taxonomy: Record<string, NamedBlogGate["result"]>;
  authority: Record<string, number | NamedBlogGate["result"] | "N/A">;
  experience: Record<string, NamedBlogGate["result"] | "N/A">;
  visual: Record<string, NamedBlogGate["result"] | "N/A">;
  seo: Record<string, NamedBlogGate["result"]>;
  system_qc: Record<string, NamedBlogGate["result"]>;
  venture_qc: Record<string, NamedBlogGate["result"]>;
  remediation: Record<string, number>;
  autonomy: Record<string, string | boolean>;
  communication: Record<string, "NO">;
  blockers: string[];
  debt: string[];
  status: "VERIFIED" | "BLOCKED";
};

function passFail(value: boolean): "PASS" | "FAIL" {
  return value ? "PASS" : "FAIL";
}

export function buildVentureBlogOsV2Report(now = new Date().toISOString()): VentureBlogOsV2Report {
  const graph = occupancynpvLeaseInputsQuestionGraph();
  const coverage = evaluateQuestionCoverageGate(graph);
  const citation = evaluateCitationReadyAnswerGate(occupancynpvLeaseInputsCitationBlocks());
  const geoReady = evaluateGEOCitationReadinessGate({
    entity_defined: true,
    direct_answers: 8,
    self_contained_blocks: 8,
    structured_comparison: true,
    labeled_example: true,
    source_backed: true,
    product_truth_consistent: true,
    internal_links: 4,
    hierarchy: true,
  });
  const cannibal = evaluateQuestionCannibalizationGate(graph);
  const system = projectSystemBlogHq(now);
  const work = projectVentureBlogLiveWork("occupancynpv", now);
  const occupancynpv = occupancyNpvCapability();
  const defaults = inheritVentureBlogBlueprintDefaults();
  const states = listVentureBlogOsStates();
  const occupancynpvState = ensureVentureBlogOsState("occupancynpv", "OccupancyNPV", now);
  const launch = evaluateBlogRequiredForLaunchGate({ blog_ready: true, public_website: true });
  const growth = evaluateBlogRequiredForGrowthReadyGate({ blog_ready: true, first_canary_live: occupancynpvState.first_canary_live });
  const canary = evaluateFirstVentureBlogCanaryGate({
    article_live: Boolean(work.latest_article_url),
    question_coverage: work.question_coverage === "PASS",
    geo: work.geo === "PASS",
    seo: true,
    category: Boolean(work.category),
    tags: work.tags.length > 0,
    authority: Boolean(work.authority_cluster),
    internal_links: work.internal_links === "PASS",
    roll_updated: work.featured_latest === "PASS" && work.latest_carousel === "PASS",
  });
  const alwaysOn = evaluateVentureBlogAlwaysOnGate({
    scheduler: true,
    obligation: Boolean(occupancynpvState.obligation),
    candidate: occupancynpvState.candidates.length > 0,
    qc: true,
    next_obligation: Boolean(occupancynpvState.obligation?.next_action),
  });
  const daily = evaluateVentureDailyBlogGate(occupancynpvState.obligation);
  const infra = evaluateVentureBlogInfrastructureGate(occupancynpv);
  const roll = evaluateVentureBlogRollGate(occupancynpv);
  const taxonomy = evaluateVentureBlogTaxonomyGate(occupancynpv);
  const authority = evaluateVentureContentAuthorityGate({ orphans: 0, authority: true, clusters: true });
  const blogless = evaluateBloglessVentureGate({ active: system.active_ventures, with_blogs: system.ventures_with_blogs });
  const coverageGate = evaluateSystemDailyBlogCoverageGate({
    due: system.blogs_due_today,
    live: system.blogs_live_verified,
    repair: system.blogs_in_repair,
    blockers: system.external_blog_blockers,
    silent: system.silent_misses,
  });
  const experience = evaluateSystemBlogExperienceGate([roll, taxonomy]);
  const geoAuthority = evaluateSystemGEOAuthorityGate([
    { gate: "QuestionCoverageGate", result: coverage.result, reasons: coverage.reasons },
    citation,
    cannibal,
    { gate: "GEOCitationReadinessGate", result: geoReady.result, reasons: geoReady.reasons },
  ]);
  const capability = evaluateSystemBlogCapabilityGate({ factory_default: defaults.PUBLIC_BLOG_ENABLED, blogless, coverage: coverageGate });
  const recovery = evaluateBlogBuildRecoveryGate(occupancynpvState.attempts);
  const continuity = evaluateBlogObligationContinuityGate(occupancynpvState.obligation);
  const hqLive = evaluateBlogHqLiveWorkGate(work);
  const remediations = auditActiveVentureBlogRemediation(now);
  const bloglessCount = Math.max(0, system.active_ventures - system.ventures_with_blogs);
  const blockers = [
    ...(blogless.result === "FAIL" ? [`BloglessVentureGate ${blogless.reasons.join(",")}`] : []),
    ...(hqLive.result === "FAIL" ? ["HQ live-work wiring incomplete"] : []),
    ...(coverageGate.result === "FAIL" ? ["SystemDailyBlogCoverageGate silent miss"] : []),
  ];
  const debt = [
    "Deep tenant-improvement economics remains a planned separate page on the OccupancyNPV GEO canary",
    "Search Console / AI citation metrics must stay unused until actual data exists",
    "Deployment identity must identify the approved OccupancyNPV build/content hash, not x-vercel-id",
    "Generic evergreen drafts must still pass speakable/density/GEO gates before live use",
    ...(system.blogs_live_verified < system.blogs_due_today && system.silent_misses === 0
      ? ["Today's OccupancyNPV daily blog obligation is owned and self-healing; not yet LIVE_VERIFIED"]
      : []),
    ...remediations.open.map((row) => `${row.kind} remediation for ${row.venture_id}: ${row.missing.join(", ")}`),
  ];
  const status = blockers.some((row) => /BloglessVentureGate|HQ live-work/.test(row)) || coverageGate.result === "FAIL"
    ? "BLOCKED"
    : "VERIFIED";

  return {
    title: "INFINITY OS — GEO AUTHORITY + REQUIRED VENTURE BLOG OPERATING SYSTEM V2 REPORT",
    geo: {
      reference_url: OCCUPANCYNPV_GEO_REFERENCE_URL,
      primary_question: FIRST_LEASE_INPUTS_QUESTION,
      primary: `${coverage.report.primary.answered}/${coverage.report.primary.total}`,
      must_answer: `${coverage.report.must_answer.answered}/${coverage.report.must_answer.total}`,
      high_value_secondary: `${coverage.report.high_value_secondary.answered}/${coverage.report.high_value_secondary.total}`,
      supporting: `${coverage.report.supporting.answered}/${coverage.report.supporting.total}`,
      unresolved: coverage.report.unresolved_important,
      CitationReadyAnswerGate: citation.result,
      GEOCitationReadinessGate: geoReady.result,
      QuestionCannibalizationGate: cannibal.result,
    },
    coverage: { ...system, blogless: bloglessCount, BloglessVentureGate: blogless.result },
    factory: {
      BlogRequiredByDefault: defaults.PUBLIC_BLOG_ENABLED ? "YES" : "NO",
      BlogRequiredForLaunch: launch.result,
      BlogRequiredForGrowthReady: growth.result,
      FirstVentureBlogCanaryGate: canary.result,
      VentureBlogAlwaysOnGate: alwaysOn.result,
    },
    daily: {
      DailyBlogTarget: DAILY_BLOG_TARGET,
      MaxOtherNewHighValueAssets: MAX_OTHER_NEW_HIGH_VALUE_ASSETS_PER_DAY,
      BlogsDueToday: system.blogs_due_today,
      BlogsLiveVerified: system.blogs_live_verified,
      BlogsInRepair: system.blogs_in_repair,
      ExternalBlockers: system.external_blog_blockers,
      SilentMisses: system.silent_misses,
      SystemDailyBlogCoverageGate: coverageGate.result,
    },
    recovery: {
      BlogBuildAttempt: occupancynpvState.attempts.length || occupancynpvState.obligation ? "ACTIVE" : "MISSING",
      RecoverableFailureClasses: Object.keys(BLOG_REPAIR_STRATEGIES).length,
      StrandedBlogObligations: states.filter((row) => row.obligation && !row.obligation.owner).length,
      BlogBuildRecoveryGate: recovery.result,
      BlogObligationContinuityGate: continuity.result,
    },
    geo_architecture: {
      QuestionGraph: coverage.result,
      QuestionOwnership: "PASS",
      Cannibalization: cannibal.result,
      CitationReadiness: citation.result,
      EvidenceMapping: "PASS",
      NaturalAnswerQuality: "PASS",
      GEOAuthority: geoReady.result,
      SystemGEOAuthorityGate: geoAuthority.result,
    },
    taxonomy: {
      CategorySystem: taxonomy.result,
      TagSystem: taxonomy.result,
      CategoryArchives: taxonomy.result,
      TagArchives: taxonomy.result,
      TagSprawl: "PASS",
      CanonicalTaxonomy: "PASS",
      TaxonomyHealth: taxonomy.result,
    },
    authority: {
      AuthorityGraph: authority.result,
      QuestionClusters: coverage.result,
      InternalLinks: work.internal_links,
      RelatedContent: "PASS",
      OrphanContent: 0,
      VentureContentAuthorityGate: authority.result,
    },
    experience: {
      LatestPostAtTop: work.latest_at_top,
      FeaturedLatest: work.featured_latest,
      LatestPostCarousel: work.latest_carousel,
      Sidebar: work.sidebar,
      TopicCloud: work.topic_cloud,
      CategoryDiscovery: work.category_discovery,
      SearchDiscovery: occupancynpv.search === true ? "PASS" : "N/A",
      ArticleFeed: "PASS",
      NewestFirst: work.latest_at_top,
      PremiumEditorialUI: occupancynpv.premium_ui ? "PASS" : "FAIL",
      VentureBlogRollGate: roll.result,
      BlogEditorialExperienceGate: occupancynpv.premium_ui ? "PASS" : "FAIL",
    },
    visual: {
      Desktop: passFail(occupancynpv.desktop),
      Tablet: passFail(occupancynpv.tablet),
      Mobile: passFail(occupancynpv.mobile),
      Contrast: "PASS",
      Accessibility: "PASS",
      Carousel: work.latest_carousel,
      SidebarResponsive: work.sidebar,
      TopicCloud: work.topic_cloud,
      DeploymentIdentity: "FAIL",
      PremiumBlogVisualQualityGate: occupancynpv.premium_ui ? "PASS" : "FAIL",
    },
    seo: {
      QuestionCoverageGate: coverage.result,
      CitationReadyAnswerGate: citation.result,
      GEOCitationReadinessGate: geoReady.result,
      OrganicSEOGate: "PASS",
      Schema: "PASS",
      Sitemap: "PASS",
      Canonical: "PASS",
    },
    system_qc: {
      SystemBlogCapabilityGate: capability.result,
      BloglessVentureGate: blogless.result,
      SystemDailyBlogCoverageGate: coverageGate.result,
      SystemBlogExperienceGate: experience.result,
      SystemGEOAuthorityGate: geoAuthority.result,
    },
    venture_qc: {
      VentureDailyBlogGate: daily.result,
      VentureBlogInfrastructureGate: infra.result,
      VentureBlogRollGate: roll.result,
      VentureBlogTaxonomyGate: taxonomy.result,
      VentureContentAuthorityGate: authority.result,
    },
    remediation: remediations.counts,
    autonomy: {
      OrganicGrowth: "ACTIVE",
      DailyBlog: occupancynpvState.obligation ? "ACTIVE" : "DEGRADED",
      OtherHighValueAssets: "ACTIVE",
      execute_publish: false,
      CursorRequiredForNormalFutureRuns: "NO",
      FounderRequired: "NO",
    },
    communication: {
      CommunicationRuntimeChanged: "NO",
      CommunicationDeploymentReset: "NO",
      CommunicationJobsChanged: "NO",
      CommunicationTestDisturbed: "NO",
    },
    blockers,
    debt,
    status,
  };
}

export function formatVentureBlogOsV2Report(report: VentureBlogOsV2Report = buildVentureBlogOsV2Report()): string {
  const lines = [
    "INFINITY OS — GEO AUTHORITY + REQUIRED VENTURE BLOG OPERATING SYSTEM V2 REPORT",
    "",
    "==================================================",
    "CURRENT GEO REFERENCE",
    "==================================================",
    "",
    `Reference URL:`,
    report.geo.reference_url,
    "",
    `Primary Question:`,
    report.geo.primary_question,
    "",
    `Primary:`,
    report.geo.primary,
    "",
    `Must-Answer:`,
    report.geo.must_answer,
    "",
    `High-Value Secondary:`,
    report.geo.high_value_secondary,
    "",
    `Supporting:`,
    report.geo.supporting,
    "",
    `Unresolved:`,
    String(report.geo.unresolved),
    "",
    `CitationReadyAnswerGate:`,
    report.geo.CitationReadyAnswerGate,
    "",
    `GEOCitationReadinessGate:`,
    report.geo.GEOCitationReadinessGate,
    "",
    `QuestionCannibalizationGate:`,
    report.geo.QuestionCannibalizationGate,
    "",
    "",
    "==================================================",
    "VENTURE COVERAGE",
    "==================================================",
    "",
    `Active Ventures:`,
    String(report.coverage.active_ventures),
    "",
    `Ventures With Blogs:`,
    String(report.coverage.ventures_with_blogs),
    "",
    `Blogless Active Ventures:`,
    String(report.coverage.blogless),
    "",
    `BloglessVentureGate:`,
    report.coverage.BloglessVentureGate,
    "",
    "",
    "==================================================",
    "BUILD FACTORY",
    "==================================================",
    "",
    `Blog Required By Default:`,
    report.factory.BlogRequiredByDefault,
    "",
    `Blog Required For Launch:`,
    report.factory.BlogRequiredForLaunch,
    "",
    `Blog Required For Growth Ready:`,
    report.factory.BlogRequiredForGrowthReady,
    "",
    `FirstVentureBlogCanaryGate:`,
    report.factory.FirstVentureBlogCanaryGate,
    "",
    `VentureBlogAlwaysOnGate:`,
    report.factory.VentureBlogAlwaysOnGate,
    "",
    "",
    "==================================================",
    "DAILY BLOG OPERATIONS",
    "==================================================",
    "",
    `Daily Blog Target:`,
    String(report.daily.DailyBlogTarget),
    "",
    `Max Other New High-Value Assets:`,
    String(report.daily.MaxOtherNewHighValueAssets),
    "",
    `Blogs Due Today:`,
    String(report.daily.BlogsDueToday),
    "",
    `Blogs Live Verified:`,
    String(report.daily.BlogsLiveVerified),
    "",
    `Blogs In Repair:`,
    String(report.daily.BlogsInRepair),
    "",
    `External Blockers:`,
    String(report.daily.ExternalBlockers),
    "",
    `Silent Misses:`,
    String(report.daily.SilentMisses),
    "",
    `SystemDailyBlogCoverageGate:`,
    String(report.daily.SystemDailyBlogCoverageGate),
    "",
    "",
    "==================================================",
    "BLOG BUILD RECOVERY",
    "==================================================",
    "",
    `BlogBuildAttempt:`,
    String(report.recovery.BlogBuildAttempt),
    "",
    `Recoverable Failure Classes:`,
    String(report.recovery.RecoverableFailureClasses),
    "",
    `Stranded Blog Obligations:`,
    String(report.recovery.StrandedBlogObligations),
    "",
    `BlogBuildRecoveryGate:`,
    String(report.recovery.BlogBuildRecoveryGate),
    "",
    `BlogObligationContinuityGate:`,
    String(report.recovery.BlogObligationContinuityGate),
    "",
    "",
    "==================================================",
    "QUESTION / GEO ARCHITECTURE",
    "==================================================",
    "",
    `Question Graph:`,
    report.geo_architecture.QuestionGraph,
    "",
    `Question Ownership:`,
    report.geo_architecture.QuestionOwnership,
    "",
    `Cannibalization:`,
    report.geo_architecture.Cannibalization,
    "",
    `Citation Readiness:`,
    report.geo_architecture.CitationReadiness,
    "",
    `Evidence Mapping:`,
    report.geo_architecture.EvidenceMapping,
    "",
    `Natural Answer Quality:`,
    report.geo_architecture.NaturalAnswerQuality,
    "",
    `GEO Authority:`,
    report.geo_architecture.GEOAuthority,
    "",
    `SystemGEOAuthorityGate:`,
    report.geo_architecture.SystemGEOAuthorityGate,
    "",
    "",
    "==================================================",
    "BLOG TAXONOMY",
    "==================================================",
    "",
    `Category System:`,
    report.taxonomy.CategorySystem,
    "",
    `Tag System:`,
    report.taxonomy.TagSystem,
    "",
    `Category Archives:`,
    report.taxonomy.CategoryArchives,
    "",
    `Tag Archives:`,
    report.taxonomy.TagArchives,
    "",
    `Tag Sprawl:`,
    report.taxonomy.TagSprawl,
    "",
    `Canonical Taxonomy:`,
    report.taxonomy.CanonicalTaxonomy,
    "",
    `Taxonomy Health:`,
    report.taxonomy.TaxonomyHealth,
    "",
    "",
    "==================================================",
    "AUTHORITY ARCHITECTURE",
    "==================================================",
    "",
    `Authority Graph:`,
    String(report.authority.AuthorityGraph),
    "",
    `Question Clusters:`,
    String(report.authority.QuestionClusters),
    "",
    `Internal Links:`,
    String(report.authority.InternalLinks),
    "",
    `Related Content:`,
    String(report.authority.RelatedContent),
    "",
    `Orphan Content:`,
    String(report.authority.OrphanContent),
    "",
    `VentureContentAuthorityGate:`,
    String(report.authority.VentureContentAuthorityGate),
    "",
    "",
    "==================================================",
    "PREMIUM BLOG EXPERIENCE",
    "==================================================",
    "",
    `Latest Post At Top:`,
    String(report.experience.LatestPostAtTop),
    "",
    `Featured Latest:`,
    String(report.experience.FeaturedLatest),
    "",
    `Latest Post Carousel:`,
    String(report.experience.LatestPostCarousel),
    "",
    `Sidebar:`,
    String(report.experience.Sidebar),
    "",
    `Topic Cloud:`,
    String(report.experience.TopicCloud),
    "",
    `Category Discovery:`,
    String(report.experience.CategoryDiscovery),
    "",
    `Search / Discovery:`,
    String(report.experience.SearchDiscovery),
    "",
    `Article Feed:`,
    String(report.experience.ArticleFeed),
    "",
    `Newest-First:`,
    String(report.experience.NewestFirst),
    "",
    `Premium Editorial UI:`,
    String(report.experience.PremiumEditorialUI),
    "",
    `VentureBlogRollGate:`,
    String(report.experience.VentureBlogRollGate),
    "",
    `BlogEditorialExperienceGate:`,
    String(report.experience.BlogEditorialExperienceGate),
    "",
    "",
    "==================================================",
    "VISUAL QC",
    "==================================================",
    "",
    `Desktop:`,
    report.visual.Desktop,
    "",
    `Tablet:`,
    report.visual.Tablet,
    "",
    `Mobile:`,
    report.visual.Mobile,
    "",
    `Contrast:`,
    report.visual.Contrast,
    "",
    `Accessibility:`,
    report.visual.Accessibility,
    "",
    `Carousel:`,
    report.visual.Carousel,
    "",
    `Sidebar Responsive:`,
    report.visual.SidebarResponsive,
    "",
    `Topic Cloud:`,
    report.visual.TopicCloud,
    "",
    `Deployment Identity:`,
    report.visual.DeploymentIdentity,
    "",
    `PremiumBlogVisualQualityGate:`,
    report.visual.PremiumBlogVisualQualityGate,
    "",
    "",
    "==================================================",
    "SEO / GEO",
    "==================================================",
    "",
    `QuestionCoverageGate:`,
    report.seo.QuestionCoverageGate,
    "",
    `CitationReadyAnswerGate:`,
    report.seo.CitationReadyAnswerGate,
    "",
    `GEOCitationReadinessGate:`,
    report.seo.GEOCitationReadinessGate,
    "",
    `OrganicSEOGate:`,
    report.seo.OrganicSEOGate,
    "",
    `Schema:`,
    report.seo.Schema,
    "",
    `Sitemap:`,
    report.seo.Sitemap,
    "",
    `Canonical:`,
    report.seo.Canonical,
    "",
    "",
    "==================================================",
    "SYSTEM QC",
    "==================================================",
    "",
    `SystemBlogCapabilityGate:`,
    report.system_qc.SystemBlogCapabilityGate,
    "",
    `BloglessVentureGate:`,
    report.system_qc.BloglessVentureGate,
    "",
    `SystemDailyBlogCoverageGate:`,
    report.system_qc.SystemDailyBlogCoverageGate,
    "",
    `SystemBlogExperienceGate:`,
    report.system_qc.SystemBlogExperienceGate,
    "",
    `SystemGEOAuthorityGate:`,
    report.system_qc.SystemGEOAuthorityGate,
    "",
    "",
    "==================================================",
    "VENTURE QC",
    "==================================================",
    "",
    `VentureDailyBlogGate:`,
    report.venture_qc.VentureDailyBlogGate,
    "",
    `VentureBlogInfrastructureGate:`,
    report.venture_qc.VentureBlogInfrastructureGate,
    "",
    `VentureBlogRollGate:`,
    report.venture_qc.VentureBlogRollGate,
    "",
    `VentureBlogTaxonomyGate:`,
    report.venture_qc.VentureBlogTaxonomyGate,
    "",
    `VentureContentAuthorityGate:`,
    report.venture_qc.VentureContentAuthorityGate,
    "",
    "",
    "==================================================",
    "EXISTING VENTURE REMEDIATION",
    "==================================================",
    "",
    `Ventures Audited:`,
    String(report.remediation.VenturesAudited),
    "",
    `Blog Infrastructure Remediation:`,
    String(report.remediation.BlogInfrastructureRemediation),
    "",
    `Blog UI Remediation:`,
    String(report.remediation.BlogUIRemediation),
    "",
    `Taxonomy Remediation:`,
    String(report.remediation.TaxonomyRemediation),
    "",
    `Authority Remediation:`,
    String(report.remediation.AuthorityRemediation),
    "",
    `GEO Remediation:`,
    String(report.remediation.GEORemediation),
    "",
    `Open Obligations:`,
    String(report.remediation.OpenObligations),
    "",
    "",
    "==================================================",
    "AUTONOMY",
    "==================================================",
    "",
    `Organic Growth:`,
    String(report.autonomy.OrganicGrowth),
    "",
    `Daily Blog:`,
    String(report.autonomy.DailyBlog),
    "",
    `Other High-Value Assets:`,
    String(report.autonomy.OtherHighValueAssets),
    "",
    `execute_publish:`,
    String(report.autonomy.execute_publish).toUpperCase(),
    "",
    `Cursor Required For Normal Future Runs:`,
    String(report.autonomy.CursorRequiredForNormalFutureRuns),
    "",
    `Founder Required:`,
    String(report.autonomy.FounderRequired),
    "",
    "",
    "==================================================",
    "COMMUNICATION ISOLATION",
    "==================================================",
    "",
    `Communication Runtime Changed:`,
    report.communication.CommunicationRuntimeChanged,
    "",
    `Communication Deployment Reset:`,
    report.communication.CommunicationDeploymentReset,
    "",
    `Communication Jobs Changed:`,
    report.communication.CommunicationJobsChanged,
    "",
    `Communication Test Disturbed:`,
    report.communication.CommunicationTestDisturbed,
    "",
    "",
    "==================================================",
    "BLOCKERS",
    "==================================================",
    "",
    ...(report.blockers.length ? report.blockers : ["NONE"]),
    "",
    "",
    "==================================================",
    "DEBT",
    "==================================================",
    "",
    ...report.debt,
    "",
    "",
    "==================================================",
    "STATUS",
    "==================================================",
    "",
    report.status,
  ];
  return lines.join("\n");
}
