import type {
  CitationReadyAnswer,
  OrganicQuestionCluster,
  OrganicQuestionCoverageNode,
} from "./geo-question-cluster";
import { FIRST_LEASE_INPUTS_QUESTION, FIRST_LEASE_INPUTS_ROUTE } from "../obligation/opportunity";

const NOW = "2026-09-20T09:20:00.000Z";
const GRAPH_ID = "qcg:occupancynpv-lease-inputs-v1";
const ASSET = "occupancynpv-lease-inputs";
const URL = FIRST_LEASE_INPUTS_ROUTE;

const PROCESS = "/lease-comparison/how-do-you-compare-two-commercial-lease-options/";
const NPV = "/commercial-lease-npv/what-is-npv-in-a-commercial-lease/";
const CAM = "/occupancy-costs/what-is-cam-in-a-commercial-lease/";
const PRICING = "/pricing";

function node(partial: Omit<OrganicQuestionCoverageNode, "graph_id" | "venture_id" | "asset_id" | "canonical_url" | "primary_question" | "canonical_intent" | "created_at" | "updated_at">): OrganicQuestionCoverageNode {
  return {
    graph_id: GRAPH_ID,
    venture_id: "occupancynpv",
    asset_id: ASSET,
    canonical_url: URL,
    primary_question: FIRST_LEASE_INPUTS_QUESTION,
    canonical_intent: "gather the cash inputs needed to compare two commercial leases",
    created_at: NOW,
    updated_at: NOW,
    ...partial,
  };
}

export function occupancynpvLeaseInputsQuestionGraph(): OrganicQuestionCoverageNode[] {
  return [
    node({
      question: FIRST_LEASE_INPUTS_QUESTION,
      question_class: "PRIMARY",
      question_intent: "input checklist for a two-lease comparison",
      semantic_relationship: "PRIMARY",
      importance_score: 100,
      search_signal: "PRIMARY_INTENT",
      voc_signal: "WHAT_DO_I_NEED",
      sales_signal: "WHAT_DO_I_NEED",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#direct-answer",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Do you only need rent to compare two commercial leases?",
      question_class: "MUST_ANSWER",
      question_intent: "scope of comparison inputs",
      semantic_relationship: "REFINES_PRIMARY",
      importance_score: 96,
      search_signal: "PAA",
      voc_signal: "HOW_DO_I_COMPARE",
      sales_signal: "WHAT_DOES_THIS_COST",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#only-rent",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What lease terms should you gather before comparing options?",
      question_class: "MUST_ANSWER",
      question_intent: "term window",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 90,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#lease-term",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What recurring costs should be included?",
      question_class: "MUST_ANSWER",
      question_intent: "recurring occupancy cash",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 92,
      search_signal: "RELATED",
      voc_signal: "WHAT_DOES_THIS_COST",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#recurring-vs-onetime",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What one-time costs should be included?",
      question_class: "MUST_ANSWER",
      question_intent: "one-time occupancy cash",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 92,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#one-time-costs",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How do annual rent increases affect the comparison?",
      question_class: "MUST_ANSWER",
      question_intent: "escalations",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 88,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#rent-increases",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Should CAM or operating expenses be included?",
      question_class: "MUST_ANSWER",
      question_intent: "net extras",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 90,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#cam",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How should free rent or rent abatement be treated?",
      question_class: "MUST_ANSWER",
      question_intent: "concession timing",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 88,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#free-rent",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Do tenant improvement allowances affect the comparison?",
      question_class: "MUST_ANSWER",
      question_intent: "TI cash",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 86,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#ti",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Should moving costs be included?",
      question_class: "MUST_ANSWER",
      question_intent: "relocation cash",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 88,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#moving-costs",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How does downtime affect a relocation comparison?",
      question_class: "MUST_ANSWER",
      question_intent: "downtime assumption",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 84,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#downtime",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What numbers should come directly from the lease proposal?",
      question_class: "MUST_ANSWER",
      question_intent: "document source",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 93,
      search_signal: "RELATED",
      voc_signal: "WHAT_DO_I_NEED",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#from-the-lease",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: true,
      evidence_state: "EXTERNAL",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What should you do if one proposal leaves out a number?",
      question_class: "MUST_ANSWER",
      question_intent: "missing data",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 91,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#missing-number",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Why can the lease with the lower rent still cost more?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "rent-only trap",
      semantic_relationship: "DECISION_QUALITY",
      importance_score: 90,
      search_signal: "PAA",
      voc_signal: "WHAT_DOES_THIS_COST",
      sales_signal: "WHAT_DOES_THIS_COST",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#lower-rent-higher-cost",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What is the difference between base rent and total occupancy cost?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "occupancy cost definition",
      semantic_relationship: "DEFINITION",
      importance_score: 80,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#only-rent",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How should landlord concessions be treated?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "concessions",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 78,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#ti",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Do security deposits belong in the comparison?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "deposits",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 72,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#one-time-costs",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How do buildout costs affect the comparison?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "buildout",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 76,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#one-time-costs",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How should recurring costs differ from one-time costs?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "classification",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 82,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#recurring-vs-onetime",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Does the timing of lease payments matter?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "timing",
      semantic_relationship: "BRIDGES_TO_NPV",
      importance_score: 84,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#timing",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How do you compare a renewal against a relocation?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "stay vs move inputs",
      semantic_relationship: "SAME_TASK_BRIEF",
      importance_score: 85,
      search_signal: "RELATED",
      voc_signal: "HOW_DO_I_COMPARE",
      sales_signal: "NONE",
      existing_page_owner: PROCESS,
      coverage_state: "ANSWERED",
      answer_location: "#renewal-vs-relocation",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: true,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How do you compare two lease proposals with different terms?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "unequal terms",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 80,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#lease-term",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Should taxes and insurance be included?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "tenant-paid extras",
      semantic_relationship: "CHILD_OF_PRIMARY",
      importance_score: 78,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#tax-insurance",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What are common mistakes when comparing leases?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "mistakes",
      semantic_relationship: "DECISION_QUALITY",
      importance_score: 86,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#mistakes",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What information does OccupancyNPV need?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "product inputs",
      semantic_relationship: "PRODUCT",
      importance_score: 82,
      search_signal: "PRODUCT",
      voc_signal: "HOW_DO_I_START",
      sales_signal: "HOW_DO_I_START",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#occupancynpv-needs",
      answer_quality: "EVIDENCE_BACKED",
      citation_ready: true,
      evidence_required: true,
      evidence_state: "PRODUCT_TRUTH",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Can OccupancyNPV compare real lease proposals?",
      question_class: "HIGH_VALUE_SECONDARY",
      question_intent: "product capability",
      semantic_relationship: "PRODUCT",
      importance_score: 80,
      search_signal: "PRODUCT",
      voc_signal: "HOW_DO_I_START",
      sales_signal: "HOW_DO_I_START",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#occupancynpv-needs",
      answer_quality: "EVIDENCE_BACKED",
      citation_ready: true,
      evidence_required: true,
      evidence_state: "PRODUCT_TRUTH",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Where do you find each number in a lease proposal?",
      question_class: "SUPPORTING",
      question_intent: "source location",
      semantic_relationship: "SUPPORTS_CHECKLIST",
      importance_score: 74,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED_WITH_DEPTH",
      answer_location: "#inputs",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Which figures should not be guessed?",
      question_class: "SUPPORTING",
      question_intent: "data quality",
      semantic_relationship: "SUPPORTS_MISSING",
      importance_score: 76,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#missing-number",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Which costs are usually recurring?",
      question_class: "SUPPORTING",
      question_intent: "classification",
      semantic_relationship: "SUPPORTS_RECURRING",
      importance_score: 70,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#recurring-vs-onetime",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "Which costs are usually one-time?",
      question_class: "SUPPORTING",
      question_intent: "classification",
      semantic_relationship: "SUPPORTS_RECURRING",
      importance_score: 70,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#recurring-vs-onetime",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What happens if escalation language is percentage-based?",
      question_class: "SUPPORTING",
      question_intent: "percent increases",
      semantic_relationship: "SUPPORTS_INCREASES",
      importance_score: 68,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#rent-increases",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How should CPI-based increases be treated conceptually?",
      question_class: "SUPPORTING",
      question_intent: "CPI",
      semantic_relationship: "SUPPORTS_INCREASES",
      importance_score: 66,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#rent-increases",
      answer_quality: "EXPLAINED",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "What should you verify before making a decision?",
      question_class: "SUPPORTING",
      question_intent: "verification",
      semantic_relationship: "SUPPORTS_LEASE_SOURCE",
      importance_score: 75,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: URL,
      coverage_state: "ANSWERED",
      answer_location: "#from-the-lease",
      answer_quality: "ACTIONABLE",
      citation_ready: true,
      evidence_required: true,
      evidence_state: "EXTERNAL",
      separate_page_candidate: false,
      ownership: "SAME_PAGE",
    }),
    node({
      question: "How do you calculate NPV for a commercial lease?",
      question_class: "SEPARATE_PAGE",
      question_intent: "NPV education",
      semantic_relationship: "DISTINCT_TASK",
      importance_score: 88,
      search_signal: "PRIMARY_OTHER_PAGE",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: NPV,
      coverage_state: "ROUTED_TO_EXISTING_PAGE",
      answer_location: "#timing",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "EXISTING_PAGE",
    }),
    node({
      question: "How does NPV compare commercial lease options?",
      question_class: "SEPARATE_PAGE",
      question_intent: "comparison process",
      semantic_relationship: "DISTINCT_TASK",
      importance_score: 90,
      search_signal: "PRIMARY_OTHER_PAGE",
      voc_signal: "HOW_DO_I_COMPARE",
      sales_signal: "NONE",
      existing_page_owner: PROCESS,
      coverage_state: "ROUTED_TO_EXISTING_PAGE",
      answer_location: "#timing",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "EXISTING_PAGE",
    }),
    node({
      question: "How do you compare renewal versus relocation in detail?",
      question_class: "SEPARATE_PAGE",
      question_intent: "deep stay-vs-move",
      semantic_relationship: "DEEPER_TASK",
      importance_score: 82,
      search_signal: "RELATED",
      voc_signal: "HOW_DO_I_COMPARE",
      sales_signal: "NONE",
      existing_page_owner: PROCESS,
      coverage_state: "ROUTED_TO_EXISTING_PAGE",
      answer_location: "#renewal-vs-relocation",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: true,
      ownership: "EXISTING_PAGE",
    }),
    node({
      question: "How do free rent concessions affect lease NPV?",
      question_class: "SEPARATE_PAGE",
      question_intent: "NPV of abatement",
      semantic_relationship: "DEEPER_TASK",
      importance_score: 74,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: NPV,
      coverage_state: "ROUTED_TO_EXISTING_PAGE",
      answer_location: "#free-rent",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: false,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "EXISTING_PAGE",
    }),
    node({
      question: "How do tenant improvement allowances affect lease economics?",
      question_class: "SEPARATE_PAGE",
      question_intent: "deep TI economics",
      semantic_relationship: "DEEPER_TASK",
      importance_score: 72,
      search_signal: "RELATED",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: null,
      coverage_state: "PLANNED_SEPARATE_PAGE",
      answer_location: "#ti",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: false,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: true,
      ownership: "NEW_SEPARATE_PAGE",
    }),
    node({
      question: "How do CAM expenses affect total occupancy cost?",
      question_class: "SEPARATE_PAGE",
      question_intent: "CAM definition",
      semantic_relationship: "DISTINCT_DEFINITION",
      importance_score: 80,
      search_signal: "PRIMARY_OTHER_PAGE",
      voc_signal: "NONE",
      sales_signal: "NONE",
      existing_page_owner: CAM,
      coverage_state: "ROUTED_TO_EXISTING_PAGE",
      answer_location: "#cam",
      answer_quality: "DIRECT_ANSWER",
      citation_ready: true,
      evidence_required: false,
      evidence_state: "REASONING",
      separate_page_candidate: false,
      ownership: "EXISTING_PAGE",
    }),
  ];
}

export function occupancynpvLeaseInputsCitationBlocks(): CitationReadyAnswer[] {
  return [
    {
      question: FIRST_LEASE_INPUTS_QUESTION,
      heading_id: "direct-answer",
      answer: "Collect the same cash figures from each lease: starting rent, term, increases, free rent, tenant-improvement money, extras the tenant still pays, and any move or downtime cost. Rent alone is not a comparison.",
      self_contained: true,
      claims: ["Rent alone is not a commercial lease comparison."],
      evidence_requirement: "REASONING",
      sources: [{ href: "https://www.sba.gov/business-guide/manage-your-business/rent-commercial-space", authority: "SBA" }],
      citation_suitability: "READY",
    },
    {
      question: "Do you only need rent to compare two commercial leases?",
      heading_id: "only-rent",
      answer: "No. Base rent is only one cash line in a commercial lease comparison. Rent increases, operating extras the tenant pays, concessions, moving costs, buildout costs, and downtime can change which option costs less over the term.",
      self_contained: true,
      claims: ["Base rent is only one part of occupancy cost."],
      evidence_requirement: "REASONING",
      sources: [{ href: "https://www.sba.gov/business-guide/manage-your-business/rent-commercial-space", authority: "SBA" }],
      citation_suitability: "READY",
    },
    {
      question: "What numbers should come directly from the lease proposal?",
      heading_id: "from-the-lease",
      answer: "Take starting rent, term dates, increase language, free-rent dates, tenant-improvement amounts, and who pays taxes, insurance, and CAM from the proposals or the signed lease. Estimate only items the documents do not state, and label those estimates.",
      self_contained: true,
      claims: ["Documented lease terms should be taken from the proposal or lease."],
      evidence_requirement: "EXTERNAL",
      sources: [
        { href: "https://www.gsa.gov/real-estate/real-estate-services/leasing-policy", authority: "GSA" },
        { href: "https://www.sba.gov/business-guide/manage-your-business/rent-commercial-space", authority: "SBA" },
      ],
      citation_suitability: "READY",
    },
    {
      question: "What should you do if one proposal leaves out a number?",
      heading_id: "missing-number",
      answer: "Leave the cell blank. Do not invent a market average, a standard 3 percent increase, or a typical move cost to finish the sheet. A blank cell shows the ranking is incomplete. A guessed cell hides that.",
      self_contained: true,
      claims: ["Missing inputs should stay blank rather than guessed."],
      evidence_requirement: "REASONING",
      sources: [],
      citation_suitability: "READY",
    },
    {
      question: "Why can the lease with the lower rent still cost more?",
      heading_id: "lower-rent-higher-cost",
      answer: "A lower monthly rent can still be the more expensive occupancy path once increases, extras the tenant pays, move costs, buildout, or downtime sit on the same timeline. Year-one cash can be higher even when the rent line looks cheaper.",
      self_contained: true,
      claims: ["Lower face rent can still produce higher occupancy cash."],
      evidence_requirement: "REASONING",
      sources: [],
      citation_suitability: "READY",
    },
    {
      question: "Should CAM or operating expenses be included?",
      heading_id: "cam",
      answer: "Yes, when the tenant pays common-area maintenance, utilities, or a share of operating expenses. Those lines belong on the same timeline as rent. A lower face rent on a net deal can lose to a higher full-service rent once extras are included.",
      self_contained: true,
      claims: ["Tenant-paid CAM belongs in the occupancy comparison."],
      evidence_requirement: "REASONING",
      sources: [{ href: CAM, authority: "OccupancyNPV CAM explainer" }],
      citation_suitability: "READY",
    },
    {
      question: "What information does OccupancyNPV need?",
      heading_id: "occupancynpv-needs",
      answer: "OccupancyNPV needs the same cash fields you would put on one timeline: rent, term, increases, concessions, extras the tenant pays, and one-time occupancy costs such as moving or downtime. It does not invent missing bids. The live offer is a 3-day free trial with no credit card and no automatic billing at /pricing.",
      self_contained: true,
      claims: ["OccupancyNPV uses entered occupancy-cost cash on one timeline.", "The live offer is a 3-day free trial with no credit card and no automatic billing."],
      evidence_requirement: "PRODUCT_TRUTH",
      sources: [{ href: PRICING, authority: "VentureProductTruth" }],
      citation_suitability: "READY",
    },
    {
      question: "Does the timing of lease payments matter?",
      heading_id: "timing",
      answer: "Yes. Money paid in month one is not the same as money paid in year five. Free rent, tenant-improvement checks, and move bids usually hit early. Escalations hit later. A later occupancy-cost comparison places those dollars on a timeline. Full NPV method lives on the lease NPV page.",
      self_contained: true,
      claims: ["Payment timing changes present occupancy cost."],
      evidence_requirement: "REASONING",
      sources: [{ href: NPV, authority: "OccupancyNPV NPV explainer" }],
      citation_suitability: "READY",
    },
  ];
}

export function occupancynpvLeaseInputsCluster(): OrganicQuestionCluster {
  const graph = occupancynpvLeaseInputsQuestionGraph();
  return {
    cluster_id: "cluster:occupancynpv-lease-inputs",
    venture_id: "occupancynpv",
    topic: "commercial lease comparison inputs",
    primary_asset: URL,
    supporting_assets: [PROCESS, NPV, CAM, PRICING, "/compare-commercial-leases"],
    questions_owned: graph.filter((row) => row.ownership === "SAME_PAGE").map((row) => row.question),
    questions_routed: graph.filter((row) => row.ownership === "EXISTING_PAGE" || row.ownership === "NEW_SEPARATE_PAGE").map((row) => row.question),
    commercial_path: PRICING,
    internal_link_graph: [
      { from: URL, to: PROCESS, reason: "comparison process" },
      { from: URL, to: NPV, reason: "timing / NPV education" },
      { from: URL, to: CAM, reason: "CAM definition" },
      { from: URL, to: PRICING, reason: "trial" },
    ],
    coverage_score: 0.95,
    authority_score: 0.9,
    updated_at: NOW,
  };
}

export function occupancynpvLeaseInputsRequiredLinks(): string[] {
  return [PROCESS, NPV, CAM, PRICING];
}
